/**
 * The FAST, browser-free half of the gate: mounts an app's spec + view in a linkedom DOM and catches the
 * render-time class of bugs (a throwing view, an unclosed tag, a missing i18n key, a blank render) plus
 * the farm's static bans (spinners, hand-rolled sheets/transports, app-authored shadows, foreign icon
 * sets, emoji) before the CI round-trip. A gate script with no exports.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/gates/preflight.mjs — edit the JSDoc there, never this file.
export {};
