/**
 * # see — the working tree, served for the eye
 *
 * The eye (`vps/eye.sh` in the edge repo: a real Chromium in Docker on the VPS) can only look at a URL. Every
 * gate before the push is browser-free, and every browser before this tool looked at the DEPLOYED site — so
 * the first screen a human saw was the one the owner opened from the store. `see` serves a checkout the way
 * the gates do — apps at `/<id>/`, the runtime at `/_rt/` OVERLAY-first (the product's `rt/` shadows the
 * framework file of the same name, as the build copies it) — on a fixed port, and keeps serving while files
 * change underneath it. Pair it with the eye on `http://127.0.0.1:<port>/<app>/?mock` and a screen is seen
 * BEFORE it is pushed (owner, 2026-09-03: "більше сирий ui не продуманий не видавати"). A gate script with
 * no exports.
 *
 * ![The see line: the working tree rsynced to the box, served by see, shot by the eye's Chromium, the PNG back on the phone](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/see.svg)
 *
 * ## Usage
 * ```sh
 * deno run -A jsr:@microspec/core/see [--root apps] [--port 8790] [--host 127.0.0.1]
 * ```
 * The product runs it through its dispatcher (`deno run -A .microspec/core.mjs see`) from the product root,
 * so `rt/` is found and `node_modules` holds the framework's runtime files. In the edge repo `vps/see.sh
 * <app> [eye flags]` rsyncs the working tree to the box, keeps one such server running there
 * (`microspec-see`, the Deno image the edge core already uses, host network) and shoots it with the eye's
 * own `shot.mjs`.
 *
 * ## Flags and arguments
 * | flag | default | meaning |
 * | --- | --- | --- |
 * | `--root <dir>` | `apps` | the directory whose children are the apps: `/<id>/` maps to `<root>/<id>/` |
 * | `--port <n>` | `8790` | the fixed port — the eye's URL names it |
 * | `--host <addr>` | `127.0.0.1` | the bind address; `0.0.0.0` when the shooter runs in another network namespace |
 *
 * ## What it serves
 * - `/<id>/…` — static files of `<root>/<id>` (the same `serveDir` the verify gate uses; `?mock` and
 *   `?theme=` are the app's own query, untouched).
 * - `/_rt/…` — the product's `rt/` first (theme, sprites, domain modules), then the framework runtime.
 * - `/feed?url=` — the gates' CORS passthrough, so a card list under `?mock` behaves as in verify.
 * No caching headers are added and nothing is bundled: the page is the source, as in the Chromium gate —
 * which means this is NOT the built site (`dist-eye` is), and a class the compat build drops is still
 * invisible here.
 *
 * ## Named failures
 * - `see: <root> is not a directory` — run it from the product root, or pass `--root`.
 * - `AddrInUse` — a server is already on the port; the eye can use that one.
 *
 * ## Exit codes
 * - 0 — the server stopped on SIGINT/SIGTERM.
 * - 2 — the root does not exist.
 *
 * ## Where it sits
 * A gate-side tool beside `verify` (the same handler, `serve-handler.mjs`) and `dist-eye` (the built tree).
 * Not part of the 8n8 DAG: it is a server, not a check.
 *
 * ## Why
 * The farm had no way to look at a screen between "gates green" and "deployed", and the store's Today
 * rubric makes a newborn app public the minute it deploys. A branch-per-look costs a CI run and still shows
 * one shape; a preview server hand-built on the VPS was refused once already (2026-09-01) because it was a
 * second serving path. This is the gate's own handler on a port — the same files, the same overlay — and the
 * eye that already exists.
 *
 * @module
 */
// GENERATED by tools/dts.mjs from packages/gates/see.mjs — edit the JSDoc there, never this file.
export {};
