/**
 * The deep gate: every DOM check across an app's STATES in one Chromium session — loading/skeleton,
 * settled (design + responsive matrix + shots), e2e, animated — with runtime-error surveillance the whole
 * time, plus the farm-wide haptic and PWA-installability checks. Exit code is the failure count. A CLI
 * script — it exports nothing.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/gates/verify.mjs — edit the JSDoc there, never this file.
export {};
