/**
 * Author-time contract gate: the compiled ajv validator for spec.json against the microspec JSON Schema
 * (draft 2020-12). Exports `validateSchema`, the same validator the generator runs in its retry loop, so a
 * bad spec never reaches the runtime; as a CLI it composes each spec with its i18n/ and reports errors.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/schema/validate.mjs — edit the JSDoc there, never this file.
/**
 * The compiled ajv validator for a composed spec (spec.json + i18n): returns true when the spec meets the
 * schema, otherwise false with the failures in `validateSchema.errors`.
 */
export const validateSchema: any;
