/**
 * # counts — the app count measured once, written everywhere it is claimed
 *
 * The farm's app count, derived from the store catalog and written into every place that states it —
 * the README badge, the CTA link, the prose, the Show HN draft — so a hand-typed number can never drift.
 * A script, not a library: it exports nothing. Without a flag it rewrites the claims from the source of
 * truth; `--check` turns it into the gate that fails on a stale claim instead of fixing it. A README that
 * overstates the farm is the same class of defect as an app that overstates its a11y: a claim nobody
 * measured. So it gets a gate like everything else here.
 *
 * ![The counts node in the 8n8 pipeline](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/pipeline-counts.svg)
 *
 * ## Usage
 * ```sh
 * deno run -A jsr:@microspec/core/counts            # rewrite the claims from the source of truth
 * deno run -A jsr:@microspec/core/counts --check    # fail instead of writing (CI)
 * ```
 * `deno task gates` runs it as the 8n8 node `counts`, with `--check`; verify.yml runs the same step before
 * the build check.
 *
 * ## Flags and arguments
 * | flag | effect |
 * | --- | --- |
 * | `--check` | report stale claims and exit 1; write nothing |
 *
 * Two files in the tree it is run in shape the rest:
 * - apps/store/apps.json — the catalog, what a user can actually install. Its length (array or keys) is N.
 *   Absent, as in the appless core, N is the number of apps/<id>/ directories carrying a spec.json.
 * - counts.rules.json, optional — `[{ "file", "pattern", "flags" }]`, the pattern with the number as its
 *   second group. A product tree claims the count in its own words, so its rules REPLACE the built-ins.
 *
 * ## What it checks and writes
 * The built-in rules are the public framework repo's own claims — five in README.md (the `live-N%20apps`
 * badge, `farm — N installable apps]`, `The N-app farm`, `and all N apps were written`,
 * `the reference farm: N apps`) and one in docs/SHOW_HN.md (`the proof: N apps live`). Each is anchored
 * on its surrounding words so a count is never confused with an efficacy score or any other digit.
 * - a rule whose number differs from N is stale: `README.md: "The 25-app farm" → should be 28`.
 * - a rule that matches nothing is stale too: `pattern … matched nothing — the claim was reworded, fix
 *   this rule`. Rewording a claim means updating its rule; the gate refuses to let the two part.
 * - with `--check` the report ends `✗ app-count claims are stale (farm has N installable apps)` and
 *   `fix: deno run -A deploy/counts.mjs`; green is `✓ app-count claims match the farm (N installable apps)`.
 * - without it every ruled file is rewritten in place: `✓ updated k claim(s) → N apps`, or
 *   `✓ already correct (N apps)`.
 *
 * ## Exit codes
 * - 0 — every claim equals N, or the claims were rewritten to N.
 * - 1 — `--check` and at least one claim is stale or a rule no longer matches; also when a ruled file
 *   cannot be read (an uncaught error).
 *
 * ## Where it sits
 * gate · script · needs: demo · needed by: push — one of the five nodes the DAG itself gates the push on
 * (validate, preflight, unit, sw, counts), and a target of the `gates` flow. cwd, not import.meta: the
 * catalog, the rules file and the README all belong to the consumer's tree.
 *
 * ## Why
 * App-count claims in the docs, checked against the directory. Prose rots; this makes it fail. The number
 * was claimed in six hand-typed places and read "25" in one file, "26" in another and 28 in the build log,
 * all at the same time.
 * @module
 */
// GENERATED by tools/dts.mjs from deploy/counts.mjs — edit the JSDoc there, never this file.
export {};
