/**
 * The farm's app count, derived once from the store catalog and written everywhere it is claimed (README,
 * Show HN draft), so a hand-typed number can never drift. A script, not a library: it exports nothing;
 * `--check` turns it into the CI gate that fails on a stale claim instead of rewriting it.
 * @module
 */
// GENERATED by tools/dts.mjs from deploy/counts.mjs — edit the JSDoc there, never this file.
export {};
