/**
 * # listing — an app has not shipped until its store card has: an icon, screenshots, words for people
 *
 * The store is where a person meets an app, and three things about that card were nobody's job: the icon,
 * the screenshots and the description. Every gate was green for an app with a placeholder glyph, no
 * pictures and a description written for its author ("WebGL field", "WebAssembly module", "k-anonymity") —
 * so each new app shipped that way and the owner asked for the same three fixes every time. This gate makes
 * them part of "done". It exports nothing.
 *
 * ![The listing node in the 8n8 pipeline](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/pipeline-listing.svg)
 *
 * ## Usage
 * ```sh
 * deno run -A jsr:@microspec/core/listing --check
 * ```
 * `deno task gates` runs it as the 8n8 node `listing`. A tree with no `apps/store` has no card to check and passes.
 *
 * ## What it checks, per listed app
 * - **icon** — `icon.webp` (the art master), once any app in the tree has one.
 * - **screenshots** — `apps/store/assets/shot-<id>--<tab>.webp` and `…--light.webp` for every non-profile
 *   tab. `deno run -A jsr:@microspec/core/store-shots <id>` takes them from the working tree.
 * - **description** — `profTagline` in every locale: at most 240 characters; a first sentence of 12–90
 *   characters (the store shows it alone as the subtitle); and none of the words in `JARGON`. A description
 *   says what the person gets; how it is built belongs in RESEARCH.md.
 * - **catalog** — `apps/store/apps.json` agrees with the tree on icon, shots, titles and taglines (run
 *   `manifest` after changing any of them).
 * - **changelog** — `apps/store/changelog.json`, when the store keeps one: newest first; every entry has a
 *   dated id, an existing app and a sentence per locale that passes the same word rules (at most 200
 *   characters); and every app added since the changelog began is announced in it. The entries are what a
 *   person is told after an update, so they say what changed for them and nothing about how.
 *
 * ## Exit codes
 * - `0` — every card is complete, or there is no store.
 * - `1` — at least one card is not; each line names the app, the locale and the offending words.
 * @module
 */
// GENERATED by tools/dts.mjs from deploy/listing.mjs — edit the JSDoc there, never this file.
/**
 * What is wrong with one description, as the store will show it.
 * @param text the `profTagline` of one locale
 * @returns the problems, empty when the description is fit for a person
 */
export function taglineProblems(text: any): string[];
/**
 * Whether a catalog entry shows what the tree would show: icon, screenshots, titles, descriptions.
 * Locale ORDER is not compared — it follows directory order, which differs between filesystems.
 * @param listed the entry from `apps/store/apps.json` (or undefined)
 * @param fresh the entry `buildManifest` produces now
 * @returns true when the card is current
 */
export function sameCard(listed: any, fresh: any): boolean;
/**
 * What is wrong with the store's changelog.
 * @param entries the parsed `changelog.json` — newest first, `{ id, date, app, uk, en }`
 * @param apps the catalog entries (`{ id, added? }`); the store itself counts as an app
 * @returns the problems, empty when every entry is fit to be shown
 */
export function changelogProblems(entries: any, apps: any): string[];
/** Words that describe how an app is built instead of what a person gets from it. */
export const JARGON: RegExp;
