/**
 * # manifest — the launcher list: an app's identity outside its own folder
 *
 * The store is the farm's front door, and it cannot read sixty spec files at load. This script scans every
 * app directory with a spec.json (the store itself excluded — a store does not list itself), reads its
 * locales, brand and icon material, and writes the grid items the store renders to apps/store/apps.json.
 * A tile reproduces the app's real icon from brand colours plus the glyph, so dev and prod look identical
 * with no image dependency. Every other string in the farm has en+uk parity; the launcher was the exception
 * and listed sixty Ukrainian names under English chrome, so the manifest now carries titles and taglines
 * per locale and the view picks. It also carries the hardware an app cannot work without, because the
 * store owes that disclosure before the tap, not after.
 *
 * ![The manifest node in the 8n8 pipeline](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/pipeline-manifest.svg)
 *
 * ## Usage
 * ```sh
 * deno run -A jsr:@microspec/core/manifest
 * ```
 * No consumer task; `deno task 8n8 manifest` runs it as the 8n8 node `manifest`. deploy/build.mjs imports
 * {@link buildManifest} and writes the same file itself when the tree has an apps/store.
 *
 * ## Flags and arguments
 * None — it reads the tree it is run in (apps/ under the current directory).
 *
 * ## What it checks / produces
 * - Writes apps/store/apps.json: an array sorted by title with Ukrainian collation, one entry per app:
 *   `id`, `title` (uk-first fallback), `titles` and `taglines` per locale (from `title` / `profTagline`),
 *   `glyph` (profile icon, else the first tab's icon, else `lucide:box`), `art` (brand.svg text),
 *   `icon` (whether icon.webp exists), `screens` (per-locale tab labels, profile tabs excluded), `shots`
 *   (tab ids that have apps/store/assets/shot-id--tab.webp, in tab order), `bg` / `fg` (brand.json, or
 *   `#1f2430` / `#a78bfa`), `href`, `version`, `category` (`feeds` by default), `needs` (the sorted union
 *   of every tab's `needs`), and `deviceNote` when the spec names one.
 * - `version` is `spec.version`, or `1.` plus the number of commits touching the app — the same count
 *   deploy/build.mjs uses, so the store can flag a new version. Outside a git tree the count is 0.
 * - A directory without spec.json is skipped, never an error. brand.json, brand.svg and icon.webp are
 *   optional; a missing one falls back to the defaults above.
 * - Prints the app count, the output path and the ids it wrote.
 *
 * ## Exit codes
 * - 0 — apps/store/apps.json written.
 * - 1 — an uncaught throw: no apps/ directory, a spec or locale file that is not valid JSON, or no
 *   apps/store directory to write into (the standalone run does not create it; build.mjs guards on it).
 *
 * ## Where it sits
 * ship · script (frozen 2026-06-19) · needs: scaffold · needed by: no node lists it, and it is not in the
 * `gates` flow — it is reached through the `all` flow, by name, or through the build:
 *
 * ![apps + /_rt → dist → dist-eye → rsync → live](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/build.svg)
 *
 * ## Why
 * The launcher list (apps/store/apps.json) — the app's identity outside its own folder.
 * @module
 */
// GENERATED by tools/dts.mjs from deploy/manifest.mjs — edit the JSDoc there, never this file.
/**
 * Scans apps/ (every directory with a spec.json, the store itself excluded) and builds the launcher's grid items.
 * @returns the app entries sorted by title (uk collation), ready to be written as apps/store/apps.json
 */
export function buildManifest(): Promise<{
    deviceNote?: any;
    id: any;
    title: any;
    titles: any;
    tagline: any;
    taglines: any;
    glyph: any;
    art: any;
    icon: boolean;
    screens: any;
    shots: any[];
    bg: any;
    fg: any;
    href: string;
    version: any;
    category: any;
    needs: any[];
}[]>;
