/**
 * Per-app README generator and gate: builds one deterministic, one-screen README.md for every app from
 * its own spec.json + i18n + brand, so no app's page drifts from its copy. `--check` fails when a spec or
 * its strings changed but the README did not. A CLI script — it exports nothing.
 * @module
 */
// GENERATED by tools/dts.mjs from deploy/readme.mjs — edit the JSDoc there, never this file.
export {};
