// microspec — generate each app's service-worker stub (apps/<id>/sw.js) from the REAL import graph.
//
//   deno run -A deploy/sw.mjs           # (re)write every app's stub
//   deno run -A deploy/sw.mjs --check   # fail if any stub is stale (a local gate, like counts.mjs --check)
//
// A per-app sw.js file is unavoidable — a worker's scope is derived from its own path and GitHub Pages can't
// send `Service-Worker-Allowed` — but it holds no logic: just the app's identity and the precache manifest,
// then `importScripts("/_rt/sw-core.js")` (build.mjs rewrites /_rt/ → ../_rt/ like every other app file).
//
// The manifest is the app's SHELL: everything needed to boot with the network unplugged.
//   · the app's own files, reached from index.html through the import graph (spec.json, i18n/*.json, view.js…)
//   · the /_rt/ modules that closure reaches
//   · what index.html loads by tag (theme.css, icon.svg, the CDN <script>/<link>s)
//   · the CDN URLs behind bare specifiers the closure imports STATICALLY (preact, htm, nanostores, motion)
// Deliberately NOT in it: apps/<id>/assets/* (card scans, wasm, sample kits) and anything reached only by a
// guarded dynamic import("three"). Those are cached on first use; the shell is a small fixed install cost,
// media is not.
//
// The version is a hash of the manifest itself, NOT of the files' contents — a runtime edit must not rewrite
// 57 stubs (and drag the whole farm through verify) when stale-while-revalidate already refreshes content.
// The cache name only has to change when the SHAPE of the shell changes.

import { buildClosure, htmlAssets, importMapOf, resolveSpec, RT, staticSpecs } from "../tools/graph.mjs";

const read = (f) => { try { return Deno.readTextFileSync(f); } catch { return null; } };
const exists = (f) => read(f) != null;

// Follow imports through code only. buildClosure regexes whatever read() returns, and an i18n string that
// happens to contain `from "…"` would otherwise invent a phantom dependency.
const codeOnly = (f) => (/\.(js|mjs|html)$/.test(f) ? read(f) : read(f) == null ? null : "");

async function hash(s) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return [...new Uint8Array(buf)].slice(0, 5).map((b) => b.toString(16).padStart(2, "0")).join("");
}

export function manifestFor(id, { read: rd = read } = {}) {
  const dir = `apps/${id}`;
  const html = rd(`${dir}/index.html`);
  if (html == null) return null;
  const urls = new Set(["./", "./index.html", "./manifest.json"]);

  // 1) what index.html loads by tag — same-origin (theme.css, icon.svg) and CDN alike
  for (const a of htmlAssets(html)) {
    if (/^https?:\/\//.test(a)) urls.add(a);
    else if (a.startsWith("/_rt/")) urls.add(a);
    else if (!a.startsWith("/")) urls.add(a.startsWith("./") ? a : `./${a}`);
  }

  // 2) the module closure of index.html: the app's own files + the /_rt/ modules they reach
  const closure = [...buildClosure(`${dir}/index.html`, codeOnly)].filter((f) => rd(f) != null).sort();
  for (const f of closure) {
    if (f.startsWith(RT)) urls.add(`/_rt/${f.slice(RT.length)}`);
    else if (f.startsWith(`${dir}/`) && f !== `${dir}/index.html`) urls.add(`./${f.slice(dir.length + 1)}`);
  }

  // 3) bare specifiers the closure imports statically → their CDN URLs, via the page's own import map
  const imports = importMapOf(html);
  for (const f of closure) {
    const src = rd(f);
    if (!src || !/\.(js|mjs|html)$/.test(f)) continue;
    for (const spec of staticSpecs(src)) {
      if (resolveSpec(spec, f)) continue;                       // local — already handled above
      const url = imports[spec] || imports[spec.replace(/\/.*$/, "/")];
      if (url) urls.add(url);
    }
  }

  // 4) the WebGPU hero shader. It is part of the shell — a few hundred bytes the stage cannot start
  // without — but it arrives by fetch() rather than import, so the closure above is blind to it. The
  // environment map beside it stays OUT, like every other assets/* payload: it is megabytes, and SWR
  // caches it on the first online run.
  if (rd(`${dir}/hero.wgsl`) != null) urls.add("./hero.wgsl");

  return [...urls].sort();
}

const STUB = (id, version, precache) =>
  `// GENERATED by deploy/sw.mjs — do not edit by hand (\`deno run -A deploy/sw.mjs\`; --check gates it).\n` +
  `// Scope comes from this file's own path, so every app needs its own worker; the logic lives once in\n` +
  `// /_rt/sw-core.js. \`precache\` is this app's shell — enough to boot with the network unplugged.\n` +
  `self.MS = {\n  app: ${JSON.stringify(id)},\n  version: ${JSON.stringify(version)},\n  precache: [\n` +
  precache.map((u) => `    ${JSON.stringify(u)},\n`).join("") +
  `  ],\n};\nimportScripts("/_rt/sw-core.js");\n`;

export async function stubFor(id) {
  const precache = manifestFor(id);
  return precache && STUB(id, await hash(JSON.stringify(precache)), precache);
}

if (import.meta.main) {
  const ids = [...Deno.readDirSync("apps")].filter((e) => e.isDirectory && exists(`apps/${e.name}/spec.json`)).map((e) => e.name).sort();
  const check = Deno.args.includes("--check");
  const stale = [];
  let written = 0;

  for (const id of ids) {
    const want = await stubFor(id);
    if (!want) { console.warn(`${id}: no index.html — skipped`); continue; }
    const path = `apps/${id}/sw.js`;
    if (read(path) === want) continue;
    if (check) { stale.push(id); continue; }
    Deno.writeTextFileSync(path, want);
    written++;
  }

  if (check) {
    if (stale.length) {
      console.error(`stale service workers (run: deno run -A deploy/sw.mjs): ${stale.join(", ")}`);
      Deno.exit(1);
    }
    console.log(`sw: ${ids.length} stubs up to date`);
  } else {
    console.log(`sw: ${written} stub(s) written, ${ids.length - written} unchanged`);
  }
}
