// GENERATED by packages/gen/authorless.mjs from books.json — deterministic, no LLM.
import { viaProxy, isJsonObject } from "/_rt/feed.js";
import { isGate, gate } from "/_rt/gate.js";
import { letterTile } from "/_rt/tile.js";
const pick = (o, path) => path.split(".").reduce((v, k) => (v == null ? v : v[k]), o);
const compact = (n) => { n = Number(n) || 0; if (n >= 1e6) return (n / 1e6).toFixed(n >= 1e7 ? 0 : 1).replace(/\.0$/, "") + "M"; if (n >= 1e3) return (n / 1e3).toFixed(n >= 1e5 ? 0 : 1).replace(/\.0$/, "") + "K"; return String(n); };
const COMPACT = new Set(["downloads"]);
const JOIN = new Set(["subjects","shelves","lang"]);
const JOIN_CAP = 6;
const joinList = (v) => Array.isArray(v) ? v.slice(0, JOIN_CAP).join(", ") : (v ?? "");
const MAP = {"id":"id","title":"title","author":"authors.0.name","desc":"summaries.0","downloads":"download_count","subjects":"subjects","shelves":"bookshelves","lang":"languages","readUrl":"formats.text/html","epubUrl":"formats.application/epub+zip","cover":"formats.image/jpeg"};
const URLT = "https://www.gutenberg.org/ebooks/{id}";

// Gate fixture: gutendex goes thin/down and reds the run on a live-data e2e. In the gate we serve a
// deterministic set that responds to the search box (self-contained SVG covers), so the run is stable.
const bcover = (t, hue) => letterTile(t, { hue, sat: 30, light: 24 });
const GATE_BOOKS = [
  { id: 1342, title: "Pride and Prejudice", author: "Jane Austen", desc: "Elizabeth Bennet and the proud Mr Darcy." },
  { id: 84, title: "Frankenstein", author: "Mary Shelley", desc: "A scientist creates, then abandons, life." },
  { id: 1661, title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", desc: "Twelve cases of the Baker Street detective." },
  { id: 2701, title: "Moby-Dick", author: "Herman Melville", desc: "Captain Ahab's hunt for the white whale." },
  { id: 11, title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", desc: "A girl falls down a rabbit hole." },
  { id: 1080, title: "A Modest Proposal", author: "Jonathan Swift", desc: "A savage satire on poverty and policy." },
].map((b, i) => ({ ...b, downloads: `${(9 - i) * 4}K`, subjects: "Fiction", shelves: "Best Books", lang: "en", readUrl: `https://www.gutenberg.org/ebooks/${b.id}.html.images`, epubUrl: `https://www.gutenberg.org/ebooks/${b.id}.epub.images`, cover: bcover(b.title, (i * 53) % 360), url: `https://www.gutenberg.org/ebooks/${b.id}` }));

export async function load(filters = {}) {
  const q = (filters.q || "").trim();
  if (isGate) {
    const ql = q.toLowerCase();
    const items = ql ? GATE_BOOKS.filter((b) => (b.title + " " + b.author + " " + b.desc).toLowerCase().includes(ql)) : GATE_BOOKS;
    return { items, meta: {} };
  }
  const url = "https://gutendex.com/books/" + (q ? "?search=" + encodeURIComponent(q) : "");
  const raw = await viaProxy(url, isJsonObject); const data = JSON.parse(raw);
  const rows = pick(data, "results") || [];
  const items = rows.map((r) => {
    const it = {};
    for (const k in MAP) { let v = pick(r, MAP[k]); if (JOIN.has(k)) v = joinList(v); if (COMPACT.has(k)) v = compact(v); it[k] = v == null ? "" : v; }
    it.url = URLT ? URLT.replace(/\{(\w+)\}/g, (_, f) => pick(r, f) ?? "") : it.url;
    return it;
  }).filter((it) => it.id != null && it.title);
  return { items, meta: {} };
}
