/**
 * # icon-import — a chosen 1024² picture becomes an app's icon
 *
 * Writes the two files an app's icon is made of: `icon.webp` (the opaque 1024² master, quality 90, which the
 * build turns into every PWA / APK size) and `icon.svg` (a 256² WebP on a rounded black tile, what the README
 * and `<link rel="icon">` consume). The picture itself is generated and judged first — recipe, prompt block
 * and the geometry gate are the product's (`docs/research/luminous-icons.md`).
 *
 * ## Usage
 * ```sh
 * deno run -A jsr:@microspec/core/icon-import <app>=<picture.png> [<app>=<picture.png> …] [--out=<apps dir>]
 * ```
 * Run from the product root; `--out` defaults to the tree's apps directory. Fails on a picture that is not
 * 1024×1024 or an app directory that does not exist.
 * @module
 */
// GENERATED by tools/dts.mjs from tools/art/icon-import.mjs — edit the JSDoc there, never this file.
/**
 * The SVG wrapper: a 256² WebP on a rounded black tile (rx 20 %, the farm's icon radius).
 * @param webp256 the encoded 256×256 WebP bytes
 * @returns the SVG document text
 */
export function iconSvgFor(webp256: any): string;
/**
 * Writes `icon.webp` and `icon.svg` for one app from a 1024×1024 PNG.
 * @param id the app directory name
 * @param pngPath path of the chosen picture
 * @returns the byte sizes written: `{ master, svg }`
 */
export function importIcon(id: any, pngPath: any): Promise<{
    master: number;
    svg: number;
}>;
