/**
 * The ACCOUNT card at the top of the profile tab, for apps that sign a reader in: who is signed in (avatar,
 * name, login, provider) with one quiet sign-out, or the farm's SignIn surface in the same card — so no app
 * grows its own sign-out or a second sign-in wall. Exports the `Account` component.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/account.js — edit the JSDoc there, never this file.
/**
 * @param github  "quiet" (default) | "primary" — passed through to SignIn
 * @param loc     UI locale
 * @param onChange called after a sign-in / sign-out settles (the runtime reloads the tab data)
 */
export function Account({ github, loc, onChange }: {
    github?: string;
    loc: any;
    onChange: any;
}): any;
