/**
 * The shared machinery under every AI capability (POST /feed/ai, key held on the VPS): the one wire call
 * (`askAI`), the localStorage-backed cache per (namespace, locale) (`cacheFor`, `persist`), the global
 * in-flight set (`pending`), the single `aiTick` atom, and `reading(ns, mode)` — the factory that turns those
 * into a cached, deduped, fail-open sync-get / async-warm capability so no domain module hand-writes the triple.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/ai-core.js — edit the JSDoc there, never this file.
/**
 * The cache dict for one (namespace, locale), read synchronously from memory or hydrated once from localStorage.
 * @param ns capability namespace ("" for polish, which keeps its historic key)
 * @param locale UI locale the entries were produced in
 * @returns the mutable cache object (key → text)
 */
export function cacheFor(ns: any, locale: any): any;
/**
 * Write a cache dict back to localStorage; silently a no-op on quota / private mode (the memory cache still works).
 * @param ns capability namespace ("" for polish)
 * @param locale UI locale
 * @param obj the cache object returned by `cacheFor`
 */
export function persist(ns: any, locale: any, obj: any): void;
/**
 * The one wire call to the AI route; throws on a non-ok status.
 * @param text the input the server-side prompt works on
 * @param locale the language the answer should come back in
 * @param mode selects the server-side system prompt
 * @param extra extra body fields that mode needs (`level`, `turns`, `locked`)
 * @returns `{ text, truncated, ungrounded }` — the trimmed answer plus the two "not worth caching" flags
 */
export function askAI(text: any, locale: any, mode: any, extra: any): Promise<{
    text: any;
    truncated: boolean;
    ungrounded: boolean;
}>;
/**
 * Build a cached, deduped, fail-open synthesis capability for one namespace and server mode.
 * @param ns cache namespace (also the in-flight tag prefix)
 * @param mode the server-side system prompt this capability asks for
 * @returns `{ get, has, warm }` — sync getter, sync "is it cached", async fetch-once-and-cache
 */
export function reading(ns: any, mode: any): {
    get: (key: any, locale: any) => any;
    has: (key: any, locale: any) => boolean;
    warm: (key: any, text: any, locale: any, extra: any) => Promise<void>;
};
/** Atom bumped whenever any AI cache gains an entry; `useStore(aiTick)` re-renders the subscriber. */
export const aiTick: any;
/** Tags of requests currently in flight, shared across every capability so two warms of one key make one request. */
export const pending: Set<any>;
