/**
 * The LANGUAGE capabilities on top of ai-core: `polish` (lightly rewrite wooden machine translation into
 * natural prose, same language), `suggest` (a one-shot creative line, deliberately uncached) and `summary`
 * (collapse a structured block of facts into one short reading), each with its sync "is it there yet" and
 * async warm. Re-exports `aiTick` so a view can subscribe without importing ai-core.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/ai-text.js — edit the JSDoc there, never this file.
/**
 * One-shot creative generation for the "surprise me" wand; never cached, "" on any failure.
 * @param mode "dream" (a vivid scene prompt) or "edit" (a short photo-edit instruction)
 * @param spark the caller's random seed text that drives variety
 * @param locale the language to generate in
 * @returns the generated line, or "" so the caller keeps its field unchanged
 */
export function suggest(mode: any, spark: any, locale: any): Promise<any>;
/**
 * The cached natural rewrite of a machine-translated string, synchronously.
 * @param text the literal translation to look up
 * @param locale the UI locale it was translated into
 * @returns the rewrite, or the input on a miss / for the content language
 */
export function polish(text: any, locale: any): any;
/**
 * Whether a string's rewrite is already cached (false while still in flight).
 * @param text the literal translation
 * @param locale the UI locale
 * @returns true when cached, empty, or a content-language passthrough
 */
export function isPolished(text: any, locale: any): boolean;
/**
 * Rewrite every not-yet-cached string in a batch (concurrency 2), then bump `aiTick` once.
 * @param texts the literal translations to warm
 * @param locale the UI locale; a no-op for the content language
 */
export function warmPolish(texts: any, locale: any): Promise<void>;
/** Sync: the cached reading for a facts signature `key` in `locale`, or "" on a miss. */
export const summary: any;
/** Sync: whether a reading for `key` in `locale` is cached (false while in flight). */
export const isSummarized: any;
/** Async: synthesise the reading for `key` from `text` once, cache it and bump `aiTick`. */
export const warmSummary: any;
