/**
 * # runtime/audio.js — Web Audio toolkit; everything is synthesised, no audio files
 *
 * The farm's sound apps ship no samples: every tone and every bed of noise is computed in the browser. This
 * module is the shared kit — a lazy AudioContext created on the first user gesture and fully guarded so the
 * UI still works where Web Audio does not exist (the headless gate, the linkedom pre-flight), the canonical
 * coloured-noise generators, small node helpers, an enveloped "strike" tone for bells, chimes, plucks and
 * kalimba tines, and equal-temperament note math. It was written for ambient (a mixer) and kalimba (an
 * instrument) and is shared by every sound app since. Refs: noise.js (zacharydenton), Noisehack, MDN.
 *
 * ![The audio module's map: gesture, engine, noise, strike, note math](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-audio.svg)
 *
 * ## Import
 * ```js
 * import { audioSupported, createEngine, midiToFreq } from "/_rt/audio.js";                    // an app's page: the import map resolves /_rt/
 * import { noiseBuffer, noteFreq } from "@microspec/core/runtime/audio.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * **Environment**
 * - {@link AC} — the AudioContext constructor (standard or webkit-prefixed), or null where Web Audio is unavailable.
 * - {@link audioSupported} — `!!AC`; false in the headless gate and the linkedom pre-flight.
 *
 * **Engine**
 * - {@link createEngine} — `({ master = 0.85, noise = true })` → `{ ctx, master, buffers, strike, resume, close }`, or null where audio is unavailable; the context is opened with `latencyHint: "interactive"`.
 *
 * **Noise and nodes**
 * - {@link noiseBuffer} — `(ctx, type, seconds = 4)` → a mono AudioBuffer of "white", "pink" (Paul Kellett's filter) or brown (leaky integrator, any other type string) noise.
 * - {@link noiseSource} — `(ctx, buf)` → a looping AudioBufferSourceNode over that buffer, not started.
 * - {@link filter} — `(ctx, type, freq, q)` → a BiquadFilterNode with type, frequency and optional Q set.
 * - {@link lfo} — `(ctx, hz, depth, target, base)` → a running OscillatorNode modulating an AudioParam by ±depth around base; stop it to end the modulation.
 *
 * **Tone**
 * - {@link strike} — `(ctx, dest, freq, { type, dur, attack, peak, partials })` — a struck/plucked tone whose partials `[ratio, gain, decayScale?]` each decay on their own curve; fire-and-forget, the nodes free themselves on `onended`.
 *
 * **Note math**
 * - {@link midiToFreq} — MIDI number → Hz (A4 = 69 = 440 Hz).
 * - {@link noteToMidi} — "C#4" / "Bb-1" → MIDI number, or null when the name does not parse.
 * - {@link noteFreq} — note name → Hz via the two above, or null.
 *
 * ## In practice
 * ```js
 * import { audioSupported, midiToFreq, createEngine } from "/_rt/audio.js";          // apps/kalimba/view.js
 *
 * const eng = useRef(null);
 * // Called from the tap handler — the context is created inside the gesture, then resumed.
 * const ensure = () => {
 *   if (!audioSupported) return null;
 *   if (!eng.current) eng.current = createEngine({ master: 0.7, noise: false });
 *   eng.current.resume();
 *   return eng.current;
 * };
 * const hit = (e, tine) => { if (e && tine) e.strike(tine.freq, timbre); };   // timbre = { type, dur, partials }
 * // On unmount: close the context so the tab frees its audio thread.
 * useEffect(() => () => { if (eng.current) eng.current.close(); }, []);
 * ```
 *
 * ## How it fits
 * A leaf: it imports nothing from the runtime and no runtime module imports it. 13 farm apps import it —
 * ambient, drift, flux, grain, handpan, hunt, kalimba, outpost, rave, sonar, sopilka, swarm, synesth — and
 * three product rt/ modules build on it (rt/ambient.js takes `midiToFreq`, rt/scifi.js `noteFreq`,
 * rt/wind.js `noiseBuffer` for a sustained voice that `strike` cannot express).
 *
 * ## Invariants and pitfalls
 * - Call `createEngine()` INSIDE a gesture handler, then `engine.resume()` — a context created outside a user gesture starts suspended.
 * - `createEngine()` returns null where audio is unavailable; callers guard: `if (!eng.current) eng.current = createEngine()` and keep the UI working without sound.
 * - Under the gate and the linkedom pre-flight `AC` is null and `audioSupported` is false — never assume a context exists.
 * - `noise: true` (the default) pre-renders three 4-second buffers on engine creation; an instrument that plays no noise passes `noise: false`.
 * - `strike` is fire-and-forget: it schedules its own stop and disconnects the nodes on `onended`, because Web Audio nodes do not GC fast.
 * - A partial's `decayScale` shortens ITS decay relative to `dur` — bright inharmonic overtones ping in the attack and die while the fundamental sustains.
 * - `noiseSource` returns a node that is not started; `lfo` returns one that already is.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/audio.js — edit the JSDoc there, never this file.
/**
 * A few-second mono buffer of coloured noise, meant to be looped.
 * @param ctx the AudioContext
 * @param type "white", "pink" (Paul Kellett's filter) or anything else for brown (leaky integrator)
 * @param seconds buffer length (default 4)
 * @returns the AudioBuffer
 */
export function noiseBuffer(ctx: any, type: any, seconds?: number): any;
/**
 * Play a struck/plucked tone: fundamental + partials, each with its own exponential decay. Fire-and-forget.
 * @param ctx the AudioContext
 * @param dest the node to connect the voices to
 * @param freq the fundamental frequency in Hz
 * @param opts `{ type, dur, attack, peak, partials }` — partials are `[ratio, gain, decayScale?]`
 */
export function strike(ctx: any, dest: any, freq: any, { type, dur, attack, peak, partials }?: {
    type?: string;
    dur?: number;
    attack?: number;
    peak?: number;
    partials?: number[][];
}): void;
/**
 * Parse a note name like "C#4" or "Bb-1" into a MIDI note number.
 * @param note the note name (letter, optional # or b, octave)
 * @returns the MIDI number, or null when the name does not parse
 */
export function noteToMidi(note: any): any;
/**
 * Create a lazy audio engine (context + master gain + optional noise buffers); call inside a gesture handler.
 * @param opts `{ master, noise }` — master gain (default 0.85) and whether to pre-render the noise buffers
 * @returns `{ ctx, master, buffers, strike, resume, close }`, or null where Web Audio is unavailable
 */
export function createEngine({ master, noise }?: {
    master?: number;
    noise?: boolean;
}): {
    ctx: any;
    master: any;
    buffers: {
        white: any;
        pink: any;
        brown: any;
    } | {
        white?: undefined;
        pink?: undefined;
        brown?: undefined;
    };
    strike: (freq: any, opts: any) => void;
    resume: () => any;
    close: () => void;
};
/**
 * # runtime/audio.js — Web Audio toolkit; everything is synthesised, no audio files
 *
 * The farm's sound apps ship no samples: every tone and every bed of noise is computed in the browser. This
 * module is the shared kit — a lazy AudioContext created on the first user gesture and fully guarded so the
 * UI still works where Web Audio does not exist (the headless gate, the linkedom pre-flight), the canonical
 * coloured-noise generators, small node helpers, an enveloped "strike" tone for bells, chimes, plucks and
 * kalimba tines, and equal-temperament note math. It was written for ambient (a mixer) and kalimba (an
 * instrument) and is shared by every sound app since. Refs: noise.js (zacharydenton), Noisehack, MDN.
 *
 * ![The audio module's map: gesture, engine, noise, strike, note math](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-audio.svg)
 *
 * ## Import
 * ```js
 * import { audioSupported, createEngine, midiToFreq } from "/_rt/audio.js";                    // an app's page: the import map resolves /_rt/
 * import { noiseBuffer, noteFreq } from "@microspec/core/runtime/audio.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * **Environment**
 * - {@link AC} — the AudioContext constructor (standard or webkit-prefixed), or null where Web Audio is unavailable.
 * - {@link audioSupported} — `!!AC`; false in the headless gate and the linkedom pre-flight.
 *
 * **Engine**
 * - {@link createEngine} — `({ master = 0.85, noise = true })` → `{ ctx, master, buffers, strike, resume, close }`, or null where audio is unavailable; the context is opened with `latencyHint: "interactive"`.
 *
 * **Noise and nodes**
 * - {@link noiseBuffer} — `(ctx, type, seconds = 4)` → a mono AudioBuffer of "white", "pink" (Paul Kellett's filter) or brown (leaky integrator, any other type string) noise.
 * - {@link noiseSource} — `(ctx, buf)` → a looping AudioBufferSourceNode over that buffer, not started.
 * - {@link filter} — `(ctx, type, freq, q)` → a BiquadFilterNode with type, frequency and optional Q set.
 * - {@link lfo} — `(ctx, hz, depth, target, base)` → a running OscillatorNode modulating an AudioParam by ±depth around base; stop it to end the modulation.
 *
 * **Tone**
 * - {@link strike} — `(ctx, dest, freq, { type, dur, attack, peak, partials })` — a struck/plucked tone whose partials `[ratio, gain, decayScale?]` each decay on their own curve; fire-and-forget, the nodes free themselves on `onended`.
 *
 * **Note math**
 * - {@link midiToFreq} — MIDI number → Hz (A4 = 69 = 440 Hz).
 * - {@link noteToMidi} — "C#4" / "Bb-1" → MIDI number, or null when the name does not parse.
 * - {@link noteFreq} — note name → Hz via the two above, or null.
 *
 * ## In practice
 * ```js
 * import { audioSupported, midiToFreq, createEngine } from "/_rt/audio.js";          // apps/kalimba/view.js
 *
 * const eng = useRef(null);
 * // Called from the tap handler — the context is created inside the gesture, then resumed.
 * const ensure = () => {
 *   if (!audioSupported) return null;
 *   if (!eng.current) eng.current = createEngine({ master: 0.7, noise: false });
 *   eng.current.resume();
 *   return eng.current;
 * };
 * const hit = (e, tine) => { if (e && tine) e.strike(tine.freq, timbre); };   // timbre = { type, dur, partials }
 * // On unmount: close the context so the tab frees its audio thread.
 * useEffect(() => () => { if (eng.current) eng.current.close(); }, []);
 * ```
 *
 * ## How it fits
 * A leaf: it imports nothing from the runtime and no runtime module imports it. 13 farm apps import it —
 * ambient, drift, flux, grain, handpan, hunt, kalimba, outpost, rave, sonar, sopilka, swarm, synesth — and
 * three product rt/ modules build on it (rt/ambient.js takes `midiToFreq`, rt/scifi.js `noteFreq`,
 * rt/wind.js `noiseBuffer` for a sustained voice that `strike` cannot express).
 *
 * ## Invariants and pitfalls
 * - Call `createEngine()` INSIDE a gesture handler, then `engine.resume()` — a context created outside a user gesture starts suspended.
 * - `createEngine()` returns null where audio is unavailable; callers guard: `if (!eng.current) eng.current = createEngine()` and keep the UI working without sound.
 * - Under the gate and the linkedom pre-flight `AC` is null and `audioSupported` is false — never assume a context exists.
 * - `noise: true` (the default) pre-renders three 4-second buffers on engine creation; an instrument that plays no noise passes `noise: false`.
 * - `strike` is fire-and-forget: it schedules its own stop and disconnects the nodes on `onended`, because Web Audio nodes do not GC fast.
 * - A partial's `decayScale` shortens ITS decay relative to `dur` — bright inharmonic overtones ping in the attack and die while the fundamental sustains.
 * - `noiseSource` returns a node that is not started; `lfo` returns one that already is.
 * @module
 */
/** The AudioContext constructor (standard or webkit-prefixed), or null where Web Audio is unavailable. */
export const AC: any;
/** Whether Web Audio exists in this environment (false in the headless gate / linkedom pre-flight). */
export const audioSupported: boolean;
/**
 * A looping buffer source over a noise buffer (not started).
 * @param ctx the AudioContext
 * @param buf the buffer from `noiseBuffer`
 * @returns the AudioBufferSourceNode
 */
export function noiseSource(ctx: any, buf: any): any;
/**
 * A biquad filter node with its type, frequency and optional Q set.
 * @param ctx the AudioContext
 * @param type the BiquadFilterType ("lowpass", "bandpass", …)
 * @param freq cutoff / centre frequency in Hz
 * @param q resonance; left at the default when null
 * @returns the BiquadFilterNode
 */
export function filter(ctx: any, type: any, freq: any, q: any): any;
/**
 * Start a low-frequency oscillator that modulates an AudioParam by ±depth around base.
 * @param ctx the AudioContext
 * @param hz the LFO rate
 * @param depth modulation amplitude in the target's units
 * @param target the AudioParam to modulate
 * @param base the target's centre value; left untouched when null
 * @returns the running OscillatorNode (stop it to end the modulation)
 */
export function lfo(ctx: any, hz: any, depth: any, target: any, base: any): any;
/**
 * Equal-temperament frequency of a MIDI note number (A4 = 69 = 440 Hz).
 * @param m the MIDI note number
 * @returns the frequency in Hz
 */
export function midiToFreq(m: any): number;
/**
 * Frequency of a note name via `noteToMidi` + `midiToFreq`.
 * @param note the note name
 * @returns the frequency in Hz, or null when the name does not parse
 */
export function noteFreq(note: any): number;
