/**
 * # runtime/bghold.js — hold the shell's foreground service while a long job runs
 *
 * Android 12+ (and One UI sooner) FREEZES a backgrounded app that has no foreground service, and a frozen
 * WebView polls nothing — so a generation "died" the moment the owner switched apps (measured 2026-08-18).
 * The shell's `bg.start` is a real Service with a persistent notification; while it is up, the process stays
 * warm and the page's timers keep ticking (MainActivity never pauses the WebView). This module wraps that as
 * one ref-counted hold: the first hold starts the service, the last release stops it, so two concurrent runs
 * share one notification. In a browser there is no shell and the whole thing is a no-op — Chrome throttles
 * but does not freeze a PWA for the few minutes a job takes.
 *
 * ![The bghold module's map: holds, the shell's service, release](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-bghold.svg)
 *
 * ## Import
 * ```js
 * import { holdBackground } from "/_rt/bghold.js";                    // an app's page: the import map resolves /_rt/
 * import { holdBackground } from "@microspec/core/runtime/bghold.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link holdBackground} — `({ title = "", body = "" })` takes one hold, with the persistent notification's text, and returns a `release()` that drops it; idempotent per release, a no-op without a shell.
 *
 * ## In practice
 * ```js
 * import { holdBackground } from "/_rt/bghold.js";                                            // apps/imagine/view.js
 *
 * const follow = async (job, run) => {
 *   const release = holdBackground({ title: T(t, "title"), body: T(t, "eGenerating") });   // keep the process warm in the APK while we poll
 *   holdRef.current = release;                                                              // so an unmount can release it too
 *   try {
 *     for (let i = 0; i < 100; i++) {                                                       // ~150s of 1.5s polls
 *       await sleep(1500);
 *       const j = await (await fetch(`${VPS_PROXY}/image/get?job=${job}`)).json();
 *       if (j.done) break;
 *     }
 *   } finally { release(); }                                                                // the last release stops the service
 * };
 * ```
 *
 * ## How it fits
 * Imports `shell` from shell.js and asks it for `bg.start` and `bg.stop` (`shell.present && shell.has(…)`);
 * no runtime module imports it. 2 farm apps import it — imagine and mirage, the two that poll a generation
 * for minutes; mirage keeps one release per mode so Make and Rework share a single hold.
 *
 * ## Invariants and pitfalls
 * - Ref-counted: two runs share one hold, and only the last release calls `bg.stop` — never stop the service directly from an app.
 * - Every `holdBackground()` needs its `release()` on every exit path (finish, error, unmount), or the notification outlives the job.
 * - `release()` is idempotent — calling it twice drops one hold, not two.
 * - Without a shell, or where the shell lacks `bg.start` / `bg.stop`, both the hold and the release are no-ops; the count is untouched.
 * - A failed `bg.start` resets `up`, so the next hold tries again rather than believing the service is running.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/bghold.js — edit the JSDoc there, never this file.
/**
 * Take one ref-counted hold on the shell's foreground service; the first hold starts it, the last release stops it.
 * Idempotent per release; safe to call without a shell (then a no-op).
 * @param opts `{ title, body }` — the persistent notification's text
 * @returns a `release()` function that drops this hold
 */
export function holdBackground({ title, body }?: {
    title?: string;
    body?: string;
}): () => void;
