/**
 * Deploy stamp: `BUILD` (git short-SHA of the deployed commit) and `CORE` (the core version), rewritten
 * by deploy/build.mjs at build time and left as placeholders in local dev and the gate.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/build.js — edit the JSDoc there, never this file.
/**
 * Deploy stamp: `BUILD` (git short-SHA of the deployed commit) and `CORE` (the core version), rewritten
 * by deploy/build.mjs at build time and left as placeholders in local dev and the gate.
 * @module
 */
/** Git short-SHA of the deployed commit; "dev" until deploy/build.mjs stamps it. */
export const BUILD: "dev";
/** Core (runtime) version counter; placeholder until deploy/build.mjs stamps it. */
export const CORE: "1.0";
