/**
 * # runtime/calendar.js — one month grid for any tool view, data-agnostic
 *
 * A month calendar: the month's own days in a 7-column grid, a dot on every day the caller marked, one
 * selected day, and arrows that page the month within optional bounds. It is SYSTEMIC in the same sense
 * `globe.js` is — it knows nothing about what a day CONTAINS. The caller hands it `marks` (which days have
 * something) and gets back the day that was tapped; what appears under the grid is the app's business.
 * Weekday and month names come from `Intl`, so the calendar speaks whatever locale the document is in
 * without a single i18n key from the app, and its own two buttons take their names from the SYS dictionary
 * (the `close`-button rule: the component that paints a control owns its label).
 *
 * The grid renders ONLY the month's own days — the leading and trailing cells are blanks, not the
 * neighbouring months' numbers. A number you can read but must not trust is worse than a gap.
 *
 * ![The calendar map: a month key into a week matrix, the caller's marks as dots, and the three outputs — the picked day, the paged month, the bounds that grey the arrows](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-calendar.svg)
 *
 * ## Import
 * ```js
 * import { Calendar, monthGrid, dayKey, monthKey, addMonths } from "/_rt/calendar.js";                    // an app's page: the import map resolves /_rt/
 * import { Calendar, monthGrid, dayKey, monthKey, addMonths } from "@microspec/core/runtime/calendar.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link Calendar} — the Preact component: `month` ("YYYY-MM", uncontrolled when `onMonth` is absent),
 *   `value` (selected "YYYY-MM-DD"), `marks` (day keys as an array or a `{ key: count }` map), `onPick(key)`,
 *   `onMonth(ym)`, `min` / `max` ("YYYY-MM" bounds for the arrows), `pick` ("all" | "marked"), `locale`.
 * - {@link monthGrid} — `monthGrid("2026-09")` → `{ year, month, weeks }`, the weeks being rows of 7 cells,
 *   each cell a `{ key, day }` or null. Pure, so the layout is unit-tested without a DOM.
 * - {@link dayKey} / {@link monthKey} — a Date or timestamp → its LOCAL "YYYY-MM-DD" / "YYYY-MM" ("" when invalid).
 * - {@link addMonths} — `addMonths("2026-12", 1)` → "2027-01", the month arithmetic the arrows ride on.
 * - {@link markMap} — normalise `marks` (array | object | Map) into a `Map<dayKey, count>`.
 *
 * ## In practice
 * ```js
 * // launches — a month of rocket launches; only days that actually carry one are pickable
 * import { Calendar, dayKey, monthKey } from "/_rt/calendar.js";
 * const marks = {};                                    // "2026-09-23": 2
 * for (const l of dated) marks[l.day] = (marks[l.day] || 0) + 1;
 * html`<${Calendar} month=${ym} onMonth=${setYm} marks=${marks} value=${day} pick="marked"
 *        onPick=${(k) => setDay(k === day ? null : k)} min=${monthKey(Date.now())} />`;
 * ```
 *
 * ## How it fits
 * Imports `htm/preact`, `preact/hooks` and `i18n.js` (`sys` — the two arrow labels and "Today" from the SYS
 * dictionary). Nothing else: no date library, no CSS of its own. It reads the density tokens
 * (`--ms-gap`, `--ms-r`, `--ms-r-in`, `--ms-label`) and paints a marked day with `--app-accent` as a DOT,
 * never as a text-bearing fill — the kit's colour rule, which is why the selected day uses `bg-primary`
 * instead.
 *
 * ## Invariants and pitfalls
 * - Days are LOCAL, never UTC. A launch at 23:30Z is tomorrow in Kyiv, and a calendar that keys on the ISO
 *   string's first ten characters puts it on the wrong square for half the planet. `dayKey` goes through
 *   `getFullYear`/`getMonth`/`getDate` for exactly that reason.
 * - The week starts on Monday (`weekStart`, default 1). `Intl` has no stable first-day-of-week across
 *   engines, so it is a prop with a European default rather than a guess that differs per browser.
 * - A month has 4–6 week rows and the grid renders the rows it needs, so February starting on a Monday
 *   does not leave a blank strip at the bottom.
 * - `pick="marked"` renders an unmarked day as plain text, not a disabled button: a control that can be
 *   focused and does nothing is a dead affordance the a11y gate cannot see.
 * - The component is controlled when `onMonth` is passed and self-driving when it is not; `month` is still
 *   honoured as the initial month in the second case, so both callers write the same prop.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/calendar.js — edit the JSDoc there, never this file.
/**
 * A Date / timestamp / date string → its LOCAL day key "YYYY-MM-DD".
 * @param d a Date, a millisecond timestamp or anything `new Date()` parses
 * @returns the local day key, or "" when the date is invalid
 */
export function dayKey(d: any): string;
/**
 * Month arithmetic on a "YYYY-MM" key — the step the arrows take, December → January included.
 * @param ym a month key "YYYY-MM"
 * @param n months to add (may be negative)
 * @returns the shifted month key, or "" when `ym` is not a month key
 */
export function addMonths(ym: any, n: any): string;
/**
 * The month's layout: week rows of seven cells, each a `{ key, day }` or null for a blank.
 * Pure — the grid is unit-tested without a DOM.
 * @param ym a month key "YYYY-MM"
 * @param weekStart the weekday the row begins on (0 = Sunday, default 1 = Monday)
 * @returns `{ year, month, weeks }` — `month` is 1-based; `weeks` has as many rows as the month needs
 */
export function monthGrid(ym: any, weekStart?: number): {
    year: number;
    month: number;
    weeks: {
        key: string;
        day: number;
    }[][];
};
/**
 * Normalise the `marks` prop into counts per day.
 * @param marks an array of day keys, an object `{ key: count }`, or a Map
 * @returns a `Map<dayKey, count>` (an array of repeated keys counts its repeats)
 */
export function markMap(marks: any): Map<any, any>;
/**
 * The month calendar (Preact): a 7-column grid of the month's own days, a dot on every marked day, one
 * selected day and arrows that page the month.
 * @param month    displayed month "YYYY-MM"; without `onMonth` it is only the INITIAL month
 * @param value    the selected day key "YYYY-MM-DD", or null
 * @param marks    day keys carrying something — an array, a `{ key: count }` object or a Map
 * @param onPick   fired with the tapped day key
 * @param onMonth  fired with the new month key; passing it makes the month controlled
 * @param min      earliest month the arrows reach ("YYYY-MM")
 * @param max      latest month the arrows reach ("YYYY-MM")
 * @param pick     "all" (default) or "marked" — whether an empty day is a button at all
 * @param weekStart the weekday a row starts on (0 = Sunday, default 1 = Monday)
 * @param locale   locale code for the month and weekday names (defaults to `<html lang>`)
 * @returns the calendar's VNode
 */
export function Calendar({ month, value, marks, onPick, onMonth, min, max, pick, weekStart, locale }: {
    month: any;
    value: any;
    marks: any;
    onPick: any;
    onMonth: any;
    min: any;
    max: any;
    pick?: string;
    weekStart?: number;
    locale: any;
}): any;
/**
 * A Date / timestamp / date string → its LOCAL month key "YYYY-MM".
 * @param d a Date, a millisecond timestamp or anything `new Date()` parses
 * @returns the local month key, or "" when the date is invalid
 */
export function monthKey(d: any): string;
