/**
 * The permission priming screen for the camera and the microphone: explains WHAT the hardware is for
 * before the native prompt, and only the user's tap triggers the real getUserMedia call. Exports the
 * `Prime` view plus the `CameraPrime` / `MicPrime` presets; chrome strings (uk/en) are built in.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/camprime.js — edit the JSDoc there, never this file.
/**
 * Render the priming screen for one hardware capability, including its blocked / unavailable states.
 * @param props `{ kind, loc, reason, onEnable, onSettings, denied?, unavailable?, privacy?, privacyIcon? }` — see the note above
 * @returns the preact vnode of the full-bleed priming overlay
 */
export function Prime({ kind, loc, reason, onEnable, onSettings, denied, unavailable, privacy, privacyIcon }: {
    kind?: string;
    loc: any;
    reason: any;
    onEnable: any;
    onSettings: any;
    denied: any;
    unavailable: any;
    privacy: any;
    privacyIcon: any;
}): any;
/** `Prime` preset for the camera. */
export function CameraPrime(props: any): any;
/** `Prime` preset for the microphone. */
export function MicPrime(props: any): any;
