/**
 * # runtime/camstage.js — the camera in a canvas, once, for every mirror app
 *
 * Every camera app of the farm used to open the stream itself: the priming screen, `camera.start` with its
 * retry, the wake lock, the flip, the pinch that zooms the track, the tap that focuses it and draws a ring,
 * the fullscreen of the stage subtree — a hundred lines copied from podoba into portal into the next one
 * (owner, 2026-09-05: "здається у нас кожна апка реалізовує ядро камери і це не ок"). `CamStage` is that
 * hundred lines as ONE element of the kit. It owns the hidden `<video>` and the whole lifecycle, and hands the
 * playing element OUT through `onVideo` — the app draws it wherever it draws (a GlStage's `cam`, a pixi
 * texture, a 2D canvas). Its children are the app's drawing surface, rendered INSIDE the stage element so a
 * fullscreen of the stage shows the picture alone (the top layer draws one subtree; the chrome outside it is
 * gone — vydyvo's show recipe).
 *
 * ![CamStage: priming, the stream, the gesture layer, the fullscreen subtree](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-camstage.svg)
 *
 * ## Import
 * ```js
 * import { CamStage } from "/_rt/camstage.js";                     // an app's page: the import map resolves /_rt/
 * import { CamStage, camPoint } from "@microspec/core/runtime/camstage.js";   // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link CamStage} — the element. Props:
 *   `loc`, `reason`, `onSettings` (the priming screen's, see camprime.js); `facing` ("environment" | "user",
 *   controlled — flip by changing it); `torch` (boolean, controlled; ignored when the track has no LED);
 *   `still` (a URL — in the gate, where headless has no hardware, an `<img>` of it plays the camera's part);
 *   `onVideo(el | null, { facing, mirror })` — the playing `<video>` (or the still's `<img>`), once per stream,
 *   `null` when it stops; `onState({ ready, caps, fullscreen, err })` — what the track declares (`caps` of
 *   {@link camControls}: torch · zoom · focus), whether the stage is fullscreen, the priming error;
 *   `fullscreen` (default true — a tap on the stage toggles the fullscreen of the stage subtree);
 *   `gestures` (default true — a pinch zooms within what the track declares, a tap focuses under the finger
 *   and draws one ring); `className` for the stage element; `children` — the app's surface.
 * - {@link camPoint} — `(u, v, vw, vh, mirror) → { x, y }`: a viewport point (0..1) to the sensor point it
 *   shows under a cover fit — the maths a tap-to-focus needs, pure.
 *
 * ## In practice
 * ```js
 * import { CamStage } from "/_rt/camstage.js";   // apps/portal/view.js
 *
 * // The stage owns the camera; the app owns the drawing. `facing` is the app's state — the flip button sets it.
 * <${CamStage} loc=${loc} reason=${T(t, "primeReason")} onSettings=${() => S.screen.set("perms")}
 *     facing=${facing} torch=${torch} still=${gate ? mockURL : null}
 *     onVideo=${(el, { mirror }) => el ? mount(P.Texture.from(el), mirror) : unmount()}
 *     onState=${(s) => { setCaps(s.caps); setFull(s.fullscreen); }}>
 *   <canvas ref=${canvasRef} class="fixed inset-0 z-0 w-full h-full pointer-events-none"></canvas>
 * <//>
 * ```
 *
 * ## The contract
 * - The camera never opens cold: the priming screen is rendered until the person taps Enable (in the gate it
 *   is skipped and the still plays). `onVideo` fires on the `playing` event — the first frame exists.
 * - A flip (a new `facing`) stops the stream, then opens the other camera; the kit's retry after the hardware
 *   lets go (sensors.js, core ≥ 1.2.32) is inside `camera.start`.
 * - The tap does two things at once, on purpose: it focuses the track at the point under the finger and
 *   toggles the fullscreen of the stage (owner: "кліком по полотну включити на весь екран і кліком вимкнути").
 *   The browser leaving fullscreen on its own (Back, ESC, the system gesture) is mirrored into `onState`.
 * - The pinch sends ONE constraint per frame, never per event — the track's `applyConstraints` is slow.
 * - The wake lock is held while the stream runs and released with it.
 *
 * ## Why
 * A camera app is its picture and its verbs; the stream is plumbing, and plumbing copied is plumbing that
 * drifts — the flip bug of 2026-09-05 was fixed in the kit and then again in an app that had its own copy.
 * One element, one lifecycle, one set of gestures, every mirror the same to the hand.
 *
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/camstage.js — edit the JSDoc there, never this file.
/**
 * A viewport point to the sensor point it shows: the cover fit of a `vw × vh` picture over the viewport, in JS,
 * so a tap focuses on what is under the finger and not on the sensor's own corner.
 * @param u 0..1 across the viewport
 * @param v 0..1 down the viewport
 * @param vw the picture's width (px)
 * @param vh the picture's height (px)
 * @param mirror the picture is shown mirrored (the front camera)
 * @param asp the viewport's aspect (width / height; defaults to the window's)
 * @returns `{ x, y }` in 0..1 of the sensor
 */
export function camPoint(u: any, v: any, vw: any, vh: any, mirror: any, asp: any): {
    x: number;
    y: number;
};
/**
 * The camera stage: the priming screen, the stream's lifecycle, the gestures and the fullscreen of the stage
 * subtree, once — the app draws the `<video>` it is handed.
 * @param props see the module note
 * @returns the stage element with the app's surface inside it
 */
export function CamStage({ loc, reason, onSettings, facing, torch, still, onVideo, onState, fullscreen, gestures, className, children }: {
    loc: any;
    reason: any;
    onSettings: any;
    facing?: string;
    torch?: boolean;
    still?: any;
    onVideo: any;
    onState: any;
    fullscreen?: boolean;
    gestures?: boolean;
    className?: string;
    children: any;
}): any;
