/**
 * Pixel → colour maths for the camera picker and any app reading a frame: pure, zero-dependency and
 * unit-tested on plain `[r,g,b]` triples and RGBA buffers, so everything runs in the headless gate.
 * Exports conversions (`rgbToHex`, `rgbToHsl`, `hexRgb`), `luminance` / `ink` for readable text over a
 * swatch, `avgColor` and the median-cut `palette`, and the theme-adaptive `iconTint`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/colour.js — edit the JSDoc there, never this file.
/**
 * Convert an RGB triple to HSL.
 * @param rgb `[r, g, b]` 0..255
 * @returns `[h 0..360, s 0..100, l 0..100]`, rounded
 */
export function rgbToHsl([r, g, b]: [
    any,
    any,
    any
]): number[];
/**
 * Mean colour of an RGBA pixel buffer; alpha is ignored.
 * @param px RGBA bytes (Uint8ClampedArray or number[])
 * @returns `[r, g, b]`, or `[0, 0, 0]` for an empty buffer
 */
export function avgColor(px: any): number[];
/**
 * WCAG relative luminance of an RGB triple.
 * @param rgb `[r, g, b]` 0..255
 * @returns luminance 0..1
 */
export function luminance([r, g, b]: [
    any,
    any,
    any
]): number;
/**
 * Parse a hex colour string into an RGB triple, tolerantly.
 * @param hex "#rgb" or "#rrggbb" (the '#' is optional)
 * @returns `[r, g, b]` 0..255; unparsable channels become 0
 */
export function hexRgb(hex: any): number[];
/**
 * Derive a theme-adaptive `{ tile, glyph }` pair for an app icon from its brand colours.
 * @param bg the app's dark brand background (hex)
 * @param fg the app's accent (hex)
 * @param dark whether the dark theme is active
 * @returns `{ tile, glyph }` CSS colour strings (color-mix / gradients), resolved by the browser
 */
export function iconTint(bg: any, fg: any, dark: any): {
    tile: string;
    glyph: any;
};
/**
 * Dominant palette of an RGBA buffer via deterministic median cut.
 * @param px RGBA bytes (Uint8ClampedArray or number[])
 * @param k how many colours to extract (default 5)
 * @returns up to `k` `[r, g, b]` triples; fewer only if the image has fewer colours
 */
export function palette(px: any, k?: number): number[][];
/**
 * Clamp a number into a rounded 0..255 channel value.
 * @param n any number
 * @returns an integer 0..255
 */
export function clamp8(n: any): number;
/**
 * `[r,g,b]` 0..255 → upper-case "#RRGGBB"; channels are clamped first.
 * @param rgb `[r, g, b]`
 * @returns the hex string
 */
export function rgbToHex([r, g, b]: [
    any,
    any,
    any
]): string;
/**
 * Readable ink over a swatch: black on light colours, white on dark ones.
 * @param rgb `[r, g, b]` 0..255
 * @returns "#000000" or "#FFFFFF"
 */
export function ink(rgb: any): "#000000" | "#FFFFFF";
