/**
 * The farm's game shell, once: ONE handheld device (body, recessed aperture, D-pad, action keys) drawn as
 * large as the viewport allows, with only the deck's CONTENT and the `plate` decided per game. Exports the
 * `GameConsole` view; it owns no input logic — the pointer behaviour is `useTouchDeck` in dpad.js and the
 * key geometry is deck.js.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/console.js — edit the JSDoc there, never this file.
/**
 * `<GameConsole>`
 *
 * @param deck      the spread from useTouchDeck() — this component never handles pointers itself
 * @param pad       [{ id, pad: "up"|"down"|"left"|"right", bit, icon, label }]
 *                  Every key exposes ONE hook, data-key=<id>, and pad keys mirror it as data-pad
 *                  so a test can count the cross without knowing what the app called its keys.
 *                  Lifting this shell out of its first game changed those hooks and broke three
 *                  e2e cases: a shared component owns its DOM contract too, not only its markup.
 * @param actions   [{ id, bit, icon, label, latch? }]   — 1…4; the shell decides the arrangement
 * @param menu      [{ id, act, icon, label, pressed? }] — sound, records: momentary, small
 * @param centre    [{ id, act, text|icon, label }]      — the START column under the menu row
 * @param plate     the game's own backplate colour, shown where the picture does not reach. Omit it
 *                  and the aperture is a neutral well, which is what a COLOUR game wants.
 * @param onKeyboard called for keyboard / assistive activation only (the deck owns pointers)
 * @param overlay   extra nodes drawn above everything (a game-over card)
 */
export function GameConsole({ deck, pad, actions, menu, centre, t, onKeyboard, onPointerDown, children, overlay, plate }: {
    deck: any;
    pad?: any[];
    actions?: any[];
    menu?: any[];
    centre?: any[];
    t: any;
    onKeyboard: any;
    onPointerDown: any;
    children: any;
    overlay?: any;
    plate?: any;
}): any;
