/**
 * # runtime/db.js — tiny IndexedDB collections, one store, no version bumps
 *
 * Persist structured data across sessions — bigger and more robust than localStorage, and async. There is
 * ONE shared database (`microspec`, version 1) with ONE object store `kv`; `collection(name)` namespaces
 * its records inside it by an indexed `coll` field, so an app that adds a new collection adds nothing to
 * the schema and never triggers an upgrade. Records are keyed by a string `id`, stamped on every put, and
 * come back newest-first. The guard `idbSupported` is the whole story where IndexedDB is absent (the
 * headless preflight, SSR): every call rejects, and the caller shows an empty state instead of crashing.
 *
 * ![The db module: one IndexedDB, one kv store, collections as a namespace index](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-db.svg)
 *
 * ## Import
 * ```js
 * import { collection, idbSupported } from "/_rt/db.js";                    // an app's page: the import map resolves /_rt/
 * import { collection, idbSupported } from "@microspec/core/runtime/db.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link idbSupported} — `true` when `indexedDB` exists in this runtime; `false` under the headless preflight / SSR.
 * - {@link collection} — `collection(name)` returns `{ all, get, put, remove, clear }`, async CRUD over records `{ id, ...value, _ts }`.
 *
 * ## In practice
 * ```js
 * import { collection, idbSupported } from "/_rt/db.js";                    // apps/wish
 * const listsColl = collection("wishlists");
 * const wishesColl = collection("wishes");
 *
 * const ls = await listsColl.all();                                         // newest-first, each { id, ...value, _ts }
 * try { await listsColl.put(id, rec); } catch { }                           // rejects where there is no IndexedDB
 * try { await wishesColl.remove(id); } catch { }
 *
 * ${idbSupported ? null : html`<div class="text-xs text-warning mt-2">${T(t, "noStore")}</div>`}
 * ```
 *
 * ## How it fits
 * The module imports nothing — it is a thin promise wrapper over the IndexedDB API, and the connection is
 * opened lazily on the first call and shared by every collection on the page. Inside the runtime,
 * `render.js` imports it for the `playPos` collection that lets a video resume where it stopped. In the farm
 * 15 apps import it — wish, habits, rave, v2m, reel, hoard, pins, trail, grain, sonar, iching, store, sigil,
 * ruler, handpan — every app that has something to save.
 *
 * ## Invariants and pitfalls
 * - One database, one store, one version. A collection is a namespace inside `kv` (the key is `"<coll> <id>"`),
 *   so adding one never needs `onupgradeneeded` and never bumps the version.
 * - Records are `{ id, ...value, _ts }`; `_ts` is set by `put` (`Date.now()`) and is what `all()` sorts by, newest-first.
 * - `put(id, value)` replaces the whole record — there is no merge; read, spread, write.
 * - Where `idbSupported` is `false` every call rejects with `no-indexeddb`. Callers catch and fall back to an
 *   empty state; the gate runs headless, so a page that throws here never reaches the screenshot.
 * - `clear()` is `all()` followed by one `remove` per row, not a store clear — it touches only its own collection.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/db.js — edit the JSDoc there, never this file.
/**
 * Open a named collection in the shared IndexedDB store.
 * @param coll the collection name (namespaces the record keys)
 * @returns `{ all, get, put, remove, clear }` — async CRUD over records `{ id, ...value, _ts }`; `all()` is newest-first
 */
export function collection(coll: any): {
    all(): Promise<any>;
    get(id: any): Promise<any>;
    put(id: any, v: any): Promise<any>;
    remove(id: any): Promise<void>;
    clear(): Promise<void>;
};
/**
 * # runtime/db.js — tiny IndexedDB collections, one store, no version bumps
 *
 * Persist structured data across sessions — bigger and more robust than localStorage, and async. There is
 * ONE shared database (`microspec`, version 1) with ONE object store `kv`; `collection(name)` namespaces
 * its records inside it by an indexed `coll` field, so an app that adds a new collection adds nothing to
 * the schema and never triggers an upgrade. Records are keyed by a string `id`, stamped on every put, and
 * come back newest-first. The guard `idbSupported` is the whole story where IndexedDB is absent (the
 * headless preflight, SSR): every call rejects, and the caller shows an empty state instead of crashing.
 *
 * ![The db module: one IndexedDB, one kv store, collections as a namespace index](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-db.svg)
 *
 * ## Import
 * ```js
 * import { collection, idbSupported } from "/_rt/db.js";                    // an app's page: the import map resolves /_rt/
 * import { collection, idbSupported } from "@microspec/core/runtime/db.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link idbSupported} — `true` when `indexedDB` exists in this runtime; `false` under the headless preflight / SSR.
 * - {@link collection} — `collection(name)` returns `{ all, get, put, remove, clear }`, async CRUD over records `{ id, ...value, _ts }`.
 *
 * ## In practice
 * ```js
 * import { collection, idbSupported } from "/_rt/db.js";                    // apps/wish
 * const listsColl = collection("wishlists");
 * const wishesColl = collection("wishes");
 *
 * const ls = await listsColl.all();                                         // newest-first, each { id, ...value, _ts }
 * try { await listsColl.put(id, rec); } catch { }                           // rejects where there is no IndexedDB
 * try { await wishesColl.remove(id); } catch { }
 *
 * ${idbSupported ? null : html`<div class="text-xs text-warning mt-2">${T(t, "noStore")}</div>`}
 * ```
 *
 * ## How it fits
 * The module imports nothing — it is a thin promise wrapper over the IndexedDB API, and the connection is
 * opened lazily on the first call and shared by every collection on the page. Inside the runtime,
 * `render.js` imports it for the `playPos` collection that lets a video resume where it stopped. In the farm
 * 15 apps import it — wish, habits, rave, v2m, reel, hoard, pins, trail, grain, sonar, iching, store, sigil,
 * ruler, handpan — every app that has something to save.
 *
 * ## Invariants and pitfalls
 * - One database, one store, one version. A collection is a namespace inside `kv` (the key is `"<coll> <id>"`),
 *   so adding one never needs `onupgradeneeded` and never bumps the version.
 * - Records are `{ id, ...value, _ts }`; `_ts` is set by `put` (`Date.now()`) and is what `all()` sorts by, newest-first.
 * - `put(id, value)` replaces the whole record — there is no merge; read, spread, write.
 * - Where `idbSupported` is `false` every call rejects with `no-indexeddb`. Callers catch and fall back to an
 *   empty state; the gate runs headless, so a page that throws here never reaches the screenshot.
 * - `clear()` is `all()` followed by one `remove` per row, not a store clear — it touches only its own collection.
 * @module
 */
/** Whether IndexedDB exists in this runtime (false in the headless preflight / SSR). */
export const idbSupported: boolean;
