/**
 * Tiny IndexedDB collections: ONE shared DB + object store "kv", namespaced by an indexed `coll` field so a
 * new collection needs no version bump. Exports `collection(name)` (async CRUD keyed by a string id) and
 * the `idbSupported` guard; where IndexedDB is absent calls reject and callers fall back to an empty state.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/db.js — edit the JSDoc there, never this file.
/**
 * Open a named collection in the shared IndexedDB store.
 * @param coll the collection name (namespaces the record keys)
 * @returns `{ all, get, put, remove, clear }` — async CRUD over records `{ id, ...value, _ts }`; `all()` is newest-first
 */
export function collection(coll: any): {
    all(): Promise<any>;
    get(id: any): Promise<any>;
    put(id: any, v: any): Promise<any>;
    remove(id: any): Promise<void>;
    clear(): Promise<void>;
};
/**
 * Tiny IndexedDB collections: ONE shared DB + object store "kv", namespaced by an indexed `coll` field so a
 * new collection needs no version bump. Exports `collection(name)` (async CRUD keyed by a string id) and
 * the `idbSupported` guard; where IndexedDB is absent calls reject and callers fall back to an empty state.
 * @module
 */
/** Whether IndexedDB exists in this runtime (false in the headless preflight / SSR). */
export const idbSupported: boolean;
