/**
 * A game control deck on Pointer Events: the deck root owns the pointer and resolves the pressed key by
 * POSITION on every move, several fingers at once, state written by ref rather than re-render. Exports
 * `useTouchDeck` (the deck as one touch surface), `useKeyboardPad` + `KEYS` / `ACTION_KEYS` (the desktop
 * layout), the `PAD` bit mask shared with the simulations, and the `keyboardOnly` activation guard.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/dpad.js — edit the JSDoc there, never this file.
/**
 * The whole control deck as ONE touch surface — see the note above.
 * @param opts `{ onAct, latchMs, minPress }` — momentary-action callback `(act, el)`, the double-tap latch window in ms, the minimum press length in ms
 * @returns `{ mask, deckProps, release, pulse, setKeys }` — the held-bits ref, the props to spread on the deck root, and the keyboard / assistive feeders
 */
export function useTouchDeck({ onAct, latchMs, minPress }?: {
    latchMs?: number;
    minPress?: number;
    onAct?: any;
}): {
    mask: any;
    deckProps: {
        ref: any;
        style: {
            touchAction: string;
        };
        onPointerDown: (e: any) => void;
        onPointerMove: (e: any) => void;
        onPointerUp: (e: any) => void;
        onPointerCancel: (e: any) => void;
    };
    release: any;
    pulse: any;
    setKeys: any;
};
/**
 * Feeds the deck's mask from the keyboard. It reports the WHOLE held set on every change rather
 * than toggling a bit, so the deck stays the single owner of the mask and a key held while a
 * finger is also down cannot erase it.
 *
 * A key event goes to the focused element, and nothing here is focused when the page loads, so
 * this listens on the window — but it steps aside for text entry, or typing in any field anywhere
 * in the app would drive the player.
 */
export function useKeyboardPad(setKeys: any, onAction: any): void;
export function markPointer(el: any): void;
export function fromPointer(el: any, within?: number): boolean;
export function keyboardOnly(fn: any): (e: any) => void;
export namespace PAD {
    let LEFT: number;
    let RIGHT: number;
    let JUMP: number;
    let RUN: number;
    let DOWN: number;
    let SHOOT: number;
}
export namespace KEYS {
    import ArrowLeft = PAD.LEFT;
    export { ArrowLeft };
    import KeyA = PAD.LEFT;
    export { KeyA };
    import ArrowRight = PAD.RIGHT;
    export { ArrowRight };
    import KeyD = PAD.RIGHT;
    export { KeyD };
    import ArrowDown = PAD.DOWN;
    export { ArrowDown };
    import KeyS = PAD.DOWN;
    export { KeyS };
    import ArrowUp = PAD.JUMP;
    export { ArrowUp };
    import KeyW = PAD.JUMP;
    export { KeyW };
    import Space = PAD.JUMP;
    export { Space };
    import KeyZ = PAD.JUMP;
    export { KeyZ };
    import ShiftLeft = PAD.RUN;
    export { ShiftLeft };
    import ShiftRight = PAD.RUN;
    export { ShiftRight };
    import KeyX = PAD.RUN;
    export { KeyX };
    import KeyC = PAD.SHOOT;
    export { KeyC };
    import ControlLeft = PAD.SHOOT;
    export { ControlLeft };
    import ControlRight = PAD.SHOOT;
    export { ControlRight };
}
export namespace ACTION_KEYS {
    let Enter: string;
    let KeyM: string;
}
