/**
 * A game control deck on Pointer Events: the deck root owns the pointer and resolves the pressed key by
 * POSITION on every move, several fingers at once, state written by ref rather than re-render. Exports
 * `useTouchDeck` (the deck as one touch surface), `useKeyboardPad` + `KEYS` / `ACTION_KEYS` (the desktop
 * layout), the `PAD` bit mask shared with the simulations, and the `keyboardOnly` activation guard.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/dpad.js — edit the JSDoc there, never this file.
/**
 * The whole control deck as ONE touch surface — see the note above.
 * @param opts `{ onAct, latchMs, minPress }` — momentary-action callback `(act, el)`, the double-tap latch window in ms, the minimum press length in ms
 * @returns `{ mask, deckProps, release, pulse, setKeys }` — the held-bits ref, the props to spread on the deck root, and the keyboard / assistive feeders
 */
export function useTouchDeck({ onAct, latchMs, minPress }?: {
    latchMs?: number;
    minPress?: number;
    onAct?: any;
}): {
    mask: any;
    deckProps: {
        ref: any;
        style: {
            touchAction: string;
        };
        onPointerDown: (e: any) => void;
        onPointerMove: (e: any) => void;
        onPointerUp: (e: any) => void;
        onPointerCancel: (e: any) => void;
    };
    release: any;
    pulse: any;
    setKeys: any;
};
/**
 * Feeds the deck's mask from the keyboard. It reports the WHOLE held set on every change rather
 * than toggling a bit, so the deck stays the single owner of the mask and a key held while a
 * finger is also down cannot erase it.
 *
 * A key event goes to the focused element, and nothing here is focused when the page loads, so
 * this listens on the window — but it steps aside for text entry, or typing in any field anywhere
 * in the app would drive the player.
 */
export function useKeyboardPad(setKeys: any, onAction: any): void;
/**
 * Record that a pointer gesture just handled this element, so the click that follows can be ignored.
 * @param el the key element (nullable)
 */
export function markPointer(el: any): void;
/**
 * Whether a pointer gesture handled this element recently.
 * @param el the key element (nullable)
 * @param within the window in ms (default 500)
 * @returns true if a pointer marked it inside the window
 */
export function fromPointer(el: any, within?: number): boolean;
/** The activation guard every app's onClick should use: keyboard and AT only. */
export function keyboardOnly(fn: any): (e: any) => void;
/** The input bit mask — the contract between a deck and a simulation, mirrored in every game. */
export const PAD: {};
/** Keyboard `code` → `PAD` bit: arrows or WASD to move, Z/Space to jump, X/Shift to run, C/Ctrl to throw. */
export const KEYS: {};
/** Momentary keys — the ones a console has as buttons rather than as directions. */
export const ACTION_KEYS: {};
