/**
 * # runtime/dust.js — the DUST field, a particle cloud that scatters and gathers while an image is made
 *
 * The generation / wait stage: 800 fine points rest in a phyllotaxis orb, breathe outward into dust and
 * draw back in, and as `progress` rises toward 1 the cloud gathers tighter — anticipation before the
 * image reveals. Adapted from a 21st.dev particle field (lovesickfromthe6ix/particle-text): the soft
 * radial glow point and the spring-to-target physics are theirs; the scatter / gather choreography, the
 * phyllotaxis orb and the zero-build preact wrapper are ours. No post-processing (bloom, aberration) —
 * a glow over a dark vignette reads premium and holds 60fps on a phone, and the stage is always dark (a
 * darkroom while developing), so it looks right in both themes. It is gate-safe by construction: under a
 * screenshot / e2e run there is no animation and no WebGL, a static gathered orb renders as plain CSS, the
 * gate is deterministic and axe sees a stable frame.
 *
 * ![The dust module: a phyllotaxis orb breathing out into dust and gathering as progress rises](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-dust.svg)
 *
 * ## Import
 * ```js
 * import { Dust } from "/_rt/dust.js";                    // an app's page: the import map resolves /_rt/
 * import { Dust } from "@microspec/core/runtime/dust.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link Dust} — `Dust({ active = true, progress = null })`, the stage component: a dark vignette with a gold glow orb and, off the gate, the WebGL cloud. `progress` is 0..1 or `null` for the idle breathe; `active` is kept for API compatibility and is not read.
 *
 * ## In practice
 * ```js
 * import { Dust } from "/_rt/dust.js";                                          // apps/imagine
 *
 * // the stage fills its parent — it is `absolute inset-0`, so the parent is positioned and sized
 * html`<div class="absolute inset-0">
 *   ${phase === "done" && slides.length
 *     ? html`<div class="absolute inset-0 flex overflow-x-auto snap-x snap-mandatory">…</div>`
 *     : html`<${Dust} active=${phase === "generating"} progress=${genProgress} />`}   // genProgress: 0..1 or null
 * </div>`;
 * ```
 *
 * ## How it fits
 * It imports `html` from `htm/preact`, `useRef` / `useEffect` from `preact/hooks`, and `gate` from
 * `./gate.js` (runtime modules import RELATIVELY — `/_rt/` 404s under `/microspec/`). Nothing in the
 * runtime imports it; it is a leaf. Two farm apps import it — imagine, where it is the generating stage
 * under the image, and mirage, where it fills the slide frame while a style card is being made.
 *
 * ## Invariants and pitfalls
 * - Mount / unmount ONLY: the effect has no dependencies. It used to depend on `[active]`; the idle → generating
 *   flip re-ran it, the cleanup had just called `loseContext()` on the one canvas, `getContext()` handed back
 *   that same DEAD context, every GL call became a no-op and Chrome painted an opaque white sheet with a
 *   broken-image glyph (measured on the VPS eye and the owner's phone, 2026-08-17). `progress` arrives through a ref.
 * - Under `gate` there is no canvas at all — the vignette and the CSS glow orb are the whole frame, so a
 *   screenshot is byte-stable and a device without WebGL gets the same premium fallback.
 * - The tint is a FIXED warm gold, not `var(--app-accent)`: imagine's accent is near-white and turned the
 *   whole cloud (and the backdrop glow) white. The stage is its own cinematic element.
 * - NORMAL blend, not additive: additive piled dense dust into a white blob; `SRC_ALPHA, ONE_MINUS_SRC_ALPHA`
 *   composites toward the tint and never past it. The fragment colour is mostly tint for the same reason.
 * - 800 points, DPR capped at 2 — many overlaps blow out, so the cloud stays sparse and cheap on a phone.
 * - The orb is kept circular whatever the canvas aspect; the canvas is resized through a `ResizeObserver`,
 *   and the cleanup cancels the frame, disconnects the observer and loses the context.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/dust.js — edit the JSDoc there, never this file.
/**
 * The dust stage component: a dark vignette with a gold glow orb and, off the gate, a WebGL particle cloud
 * that gathers tighter as `progress` rises toward 1.
 * @param props component props
 * @param props.active kept for API compatibility; the field breathes in idle and while generating alike
 * @param props.progress 0..1 generation progress, or null for the idle breathe
 * @returns the rendered stage
 */
export function Dust({ active, progress }: {
    active?: boolean;
    progress?: any;
}): any;
