/**
 * CORS strategy with graceful fallback for a static host with no backend: `viaProxy` tries direct, then the
 * dev `/feed` proxy (localhost only), then our own allowlisted VPS proxy, skipping any response a validator
 * rejects. Also exports `fetchJson` (proxy chain + shape-checked JSON.parse), `pool` (bounded-concurrency
 * map), the `isJsonArray`/`isJsonObject` validators, and the `VPS_PROXY` URL with its pinned `SEALED_KEY`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/feed.js — edit the JSDoc there, never this file.
/**
 * Fetches a URL as text through the proxy chain (direct → dev proxy → VPS proxy), moving to the next hop on
 * a non-OK status, a timeout, or a response the validator rejects.
 * @param url the upstream URL
 * @param validate predicate on the response text; a false result skips to the next proxy
 * @param timeout per-hop abort timeout in ms
 * @returns the first response text that passed validation; throws the last error when every hop failed
 */
export function viaProxy(url: any, validate?: (x: any) => boolean, timeout?: number): Promise<any>;
/**
 * Fetches JSON through the proxy chain, validating the shape before parsing.
 * @param url the upstream URL
 * @param opts options
 * @param opts.array expect a JSON array instead of an object
 * @param opts.timeout per-hop abort timeout in ms
 * @returns the parsed JSON
 */
export function fetchJson(url: any, { array, timeout }?: {
    array?: boolean;
    timeout?: number;
}): Promise<any>;
/**
 * Runs an async function over items with at most `n` in flight at once.
 * @param items the items to process
 * @param n maximum concurrency
 * @param fn async worker called once per item
 * @returns resolves when every item has been processed
 */
export function pool(items: any, n: any, fn: any): Promise<void>;
/** Our hardened, host-allowlisted CORS proxy (microspec-edge on the VPS) — the last hop of the proxy chain. */
export const VPS_PROXY: "https://dreamstudio.mooo.com/feed";
/** The backend's pinned long-term public key (base64url), used by sealedfetch.js to seal calls to VPS_PROXY. */
export const SEALED_KEY: "BLP-06vCYzSiakKos1Sk7Yqzneb0MrbBjozH3EQ_YRgvzqc_0hcZeeFXoDzMhHlXL3awFtjOMFg08dzcKUmbNOM";
export function isJsonArray(x: any): any;
export function isJsonObject(x: any): any;
