/**
 * Squeezing real accuracy out of W3C Geolocation fixes by statistics, honestly: averaging a stationary
 * tail of fixes shrinks the random error by √N but never the bias, so `meanFix` measures the scatter and
 * keeps a conservative floor under what it cannot observe. Exports `stationaryTail`, `meanFix`, the
 * `segErr`/`totalErr` quadrature helpers, the `usableFix` vertex filter and the `BIAS_FRAC`/`ACC_LIMIT`
 * constants. Every accuracy in and out is a 95% radius in metres.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/geofix.js — edit the JSDoc there, never this file.
/**
 * Returns the tail of a fix buffer that represents standing still at one spot, walking back from the
 * newest fix until one is too old or too far away.
 * @param buf fixes in arrival order (`{ lat, lng, accuracy, t }`)
 * @param {object} [opts] options
 * @param [opts.now] reference time in ms; defaults to the newest fix's `t`
 * @param [opts.maxAgeMs] oldest a fix may be, relative to `now`, to still count
 * @param [opts.radiusM] "same spot" radius in metres; defaults to 1.5× the newest fix's accuracy (min 3 m)
 * @returns the stationary fixes, oldest first (empty for an empty buffer)
 */
export function stationaryTail(buf: any, { now, maxAgeMs, radiusM }?: {
    now?: any;
    maxAgeMs?: any;
    radiusM?: any;
}): any[];
/**
 * Averages fixes of one spot into a single fix whose accuracy is the measured standard error of the mean
 * (95%), floored by the bias fraction and never better than a single fix.
 * @param ss fixes of the same spot, as returned by `stationaryTail`
 * @returns `{ lat, lng, accuracy, n, altitude? }`, or null for no samples
 */
export function meanFix(ss: any): {
    lat: number;
    lng: number;
    accuracy: any;
    n: any;
};
/**
 * Squeezing real accuracy out of W3C Geolocation fixes by statistics, honestly: averaging a stationary
 * tail of fixes shrinks the random error by √N but never the bias, so `meanFix` measures the scatter and
 * keeps a conservative floor under what it cannot observe. Exports `stationaryTail`, `meanFix`, the
 * `segErr`/`totalErr` quadrature helpers, the `usableFix` vertex filter and the `BIAS_FRAC`/`ACC_LIMIT`
 * constants. Every accuracy in and out is a 95% radius in metres.
 * @module
 */
/** Fraction of a fix's reported accuracy treated as unremovable bias — the floor `meanFix` never claims below. */
export const BIAS_FRAC: 0.5;
/**
 * 95% error of one measured segment: both endpoints' accuracies added in quadrature.
 * @param a first endpoint fix
 * @param b second endpoint fix
 * @returns the segment error in metres
 */
export function segErr(a: any, b: any): number;
/**
 * 95% error of a total distance: the segment errors added in quadrature.
 * @param errs per-segment errors in metres
 * @returns the total error in metres
 */
export function totalErr(errs: any): number;
/** Default accuracy ceiling in metres for a fix to be accepted as a vertex. */
export const ACC_LIMIT: 30;
/**
 * Whether a fix is precise enough to be a vertex of a measured line.
 * @param p the fix
 * @param limit accuracy ceiling in metres
 * @returns true when the fix has a positive accuracy at or under the limit
 */
export function usableFix(p: any, limit?: number): boolean;
