/**
 * The Earth's magnetic field from the World Magnetic Model (WMM2025), so a compass can turn a magnetic
 * bearing into a true one — the declination depends on where you are and drifts every year, and it is
 * proven against NOAA's 100 official test points rather than a demo. Exports `field` (X/Y/Z/H/F plus
 * declination and inclination), `declination`, `trueFrom`, `decimalYear`, `inRange` and the
 * `EPOCH`/`VALID_UNTIL` bounds.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/geomag.js — edit the JSDoc there, never this file.
/**
 * Evaluates the WMM2025 field at a geodetic point.
 * @param latDeg geodetic latitude in degrees
 * @param lonDeg longitude in degrees
 * @param altKm altitude in kilometres above the WGS84 ellipsoid
 * @param year decimal year (see `decimalYear`)
 * @returns `{ X, Y, Z, H, F, declination, inclination }` — components in nT, angles in degrees
 *   (declination positive when magnetic north lies east of true north)
 */
export function field(latDeg: any, lonDeg: any, altKm?: number, year?: number): {
    X: number;
    Y: number;
    Z: number;
    H: number;
    F: number;
    declination: number;
    inclination: number;
};
/**
 * The Earth's magnetic field from the World Magnetic Model (WMM2025), so a compass can turn a magnetic
 * bearing into a true one — the declination depends on where you are and drifts every year, and it is
 * proven against NOAA's 100 official test points rather than a demo. Exports `field` (X/Y/Z/H/F plus
 * declination and inclination), `declination`, `trueFrom`, `decimalYear`, `inRange` and the
 * `EPOCH`/`VALID_UNTIL` bounds.
 * @module
 */
/** The model epoch as a decimal year; secular variation is applied relative to it. */
export const EPOCH: 2025;
/** End of the model's validity as a decimal year (exclusive); beyond it the coefficients are extrapolation. */
export const VALID_UNTIL: 2030;
export function declination(lat: any, lon: any, altKm?: number, year?: number): number;
export function decimalYear(d?: Date): number;
export function inRange(year?: number): boolean;
export function trueFrom(magneticDeg: any, dec: any): number;
