/**
 * Mobile touch gestures shared by the runtime and apps: `useSheetDrag` (drag a bottom sheet down by its
 * grip to dismiss), `usePanX` (a pane that follows the finger left/right and commits to prev/next),
 * `useSwipe` (a four-way flick on a surface that does not move), `useTap` (single-vs-double tap), the pure
 * `pastDismiss` decision and the re-exported `swipeDir`. Pointer Events cover mouse + touch in one path, and
 * every callback is guarded so a gesture can never throw into the render.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/gesture.js — edit the JSDoc there, never this file.
/**
 * Single-vs-double tap discriminator for one element; a double tap cancels the pending single.
 * @param opts options
 * @param opts.onSingle called with `{x,y}` (relative to the element) after `delay` ms with no second tap
 * @param opts.onDouble called with `{x,y}` on a second tap inside the window
 * @param opts.delay double-tap window in ms
 * @returns a click handler to bind to the element's onClick
 */
export function useTap({ onSingle, onDouble, delay }?: {
    delay?: number;
    onSingle?: any;
    onDouble?: any;
}): (e: any) => void;
/**
 * A bottom sheet dragged down by its grip: follows the finger 1:1, then flies out (calling `onClose`) or
 * springs back on release.
 * @param onClose called after the fly-out animation when the drag passes the dismiss threshold
 * @returns `{ boxRef, grip }` — attach `boxRef` to the sheet box and render `grip` at its top
 */
export function useSheetDrag(onClose: any): {
    boxRef: any;
    grip: any;
};
/**
 * A horizontally pannable pane that follows the finger with edge resistance and commits to prev/next on
 * release, swallowing the click the same drag would have fired.
 * @param opts options
 * @param opts.onNext called on a committed leftward pan
 * @param opts.onPrev called on a committed rightward pan
 * @param opts.canNext whether a next item exists (heavy resistance at the edge otherwise)
 * @param opts.canPrev whether a previous item exists
 * @param opts.threshold px of travel needed to commit
 * @param opts.onDrag optional live progress in px, called with 0 on release
 * @returns `{ paneRef, pan }` — attach `paneRef` to the pane and spread `pan` on the element
 */
export function usePanX({ onNext, onPrev, canNext, canPrev, threshold, onDrag }?: {
    canNext?: boolean;
    canPrev?: boolean;
    threshold?: number;
    onNext?: any;
    onPrev?: any;
    onDrag?: any;
}): {
    paneRef: any;
    pan: {
        onPointerDown: (e: any) => void;
        onPointerMove: (e: any) => void;
        onPointerUp: () => void;
        onPointerCancel: () => void;
        onClickCapture: (e: any) => void;
    };
};
/**
 * A four-way flick on a surface that does not move: commits on release and swallows the click the same
 * drag would fire.
 * @param opts options
 * @param opts.onLeft called on a leftward flick
 * @param opts.onRight called on a rightward flick
 * @param opts.onUp called on an upward flick
 * @param opts.onDown called on a downward flick
 * @param opts.threshold px of travel needed to count as a flick
 * @returns pointer/click handlers to spread on the element
 */
export function useSwipe({ onLeft, onRight, onUp, onDown, threshold }?: {
    threshold?: number;
    onLeft?: any;
    onRight?: any;
    onUp?: any;
    onDown?: any;
}): {
    onPointerDown: (e: any) => void;
    onPointerMove: (e: any) => void;
    onPointerUp: () => void;
    onPointerCancel: () => void;
    onClickCapture: (e: any) => void;
};
export function pastDismiss(dy: any, vy: any): boolean;
