/**
 * Reusable interactive globe for any tool view: a canvas orthographic Earth (d3-geo, no WebGL, so it
 * renders in the headless gate too) with country outlines, drag-to-spin, pinch/wheel zoom, idle rotation
 * and tap-to-select. Data-agnostic — the app decides what a pick means. Exports the `Globe` component
 * plus `countryAt`/`worldReady`, which reuse the world topology any Globe on the page has already fetched.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/globe.js — edit the JSDoc there, never this file.
/**
 * Look up which country a lat/lon falls in, using the already-loaded world topology.
 * @param lat latitude in degrees
 * @param lon longitude in degrees
 * @returns `{ id, name }` of the containing country, or null for ocean / topology not loaded yet
 */
export function countryAt(lat: any, lon: any): {
    id: string;
    name: any;
};
/**
 * Whether the world topology has finished loading (so `countryAt` can answer).
 * @returns true once /_rt/world-110m.json has been fetched and parsed
 */
export function worldReady(): boolean;
/**
 * The interactive globe component (Preact). Shows a skeleton until the world topology is loaded, then
 * runs one continuous rAF loop that only redraws when something is dirty.
 * @param onPick   fired on a tap with `{ lat, lon, id, name, point }` — `point` is the hit overlay point, if any
 * @param selected country id to highlight with the accent
 * @param marker   `{ lat, lon }` pin for a chosen location
 * @param focus    `{ lat, lon }` — animate the globe to centre it (used as the initial view when supplied at mount)
 * @param points   `[{ lat, lon, r, color, pulse }]` overlay dots; `pulse: true` draws expanding rings on the canvas
 * @param spin     idle auto-rotation (default true; pauses while dragging, zoomed, selected or marked)
 * @param height   max size in px (the globe is square)
 * @returns the globe's VNode
 */
export function Globe({ onPick, selected, marker, focus, points, spin, height }: {
    onPick: any;
    selected: any;
    marker: any;
    focus: any;
    points: any;
    spin?: boolean;
    height?: number;
}): any;
