/**
 * # runtime/godotstage.js — the Godot engine as a stage under the page
 *
 * Inside the shell's `godot` flavour (the APK that links the Godot engine as a library, 2026-09-05) a page can
 * put a whole Godot project UNDER itself: the engine renders into the window behind a transparent WebView, the
 * page stays the UI. `GodotStage` is that arrangement as ONE element of the kit, the way `CamStage` is the
 * camera: mount it and the engine starts the project pack you name (from the page's own origin — the shell
 * refuses any other), hand it `params` and every change reaches the project as a `set` signal, forward the
 * gestures on the stage, save a frame, and read what the engine reports through `onState`. Unmount it and the
 * engine stops. Where there is no engine (every browser, the lighter shells) `available()` is false and the
 * element renders nothing — an app draws its web stage instead.
 *
 * ![GodotStage: the pack from the page's origin, the engine under a transparent WebView, set/input/save in, state out](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-godotstage.svg)
 *
 * ## Import
 * ```js
 * import { GodotStage, godotAvailable, godotSave } from "/_rt/godotstage.js";   // an app's page
 * import { godotAvailable } from "@microspec/core/runtime/godotstage.js";        // a product rt/ module or a test
 * ```
 *
 * ## What it exports
 * - {@link GodotStage} — the element. Props: `pack` (URL of the project's .pck on the page's origin), `params`
 *   (an object: every key whose value changed since the last render is sent as `godot.set`), `onState(frame)`
 *   (the engine's `godot.state` frames: `{state, fps, width, height, detail}`), `gestures` (default true: a tap
 *   and a pinch on the stage go to the project as `godot.input`), `className`, `children` (drawn OVER the
 *   engine, e.g. a scrim).
 * - {@link godotAvailable} — `() → boolean`: is there an engine to start here (the shell carries `godot.start`)?
 * - {@link godotSave} — `(name?) → Promise<{name, bytes}>`: the current frame as a PNG in Downloads.
 *
 * ## The contract
 * - While a GodotStage is mounted the document is marked `data-engine="godot"` and its ground is transparent
 *   (the runtime's own stylesheet rule), so the engine's picture shows through everything but the chrome.
 * - One engine per process (Godot's rule): a second GodotStage with another pack is refused by the shell.
 * - `params` are diffed by JSON, shallowly by key; send a new object to change a value.
 * - Under the gate the facade mocks every action from the catalogue, so a page renders the same tree there.
 *
 * ## Why
 * The stage is a capability of the shell, not of one app: the next app with a Godot project mounts the
 * same element and inherits the transparency, the origin lock, the gestures and the state stream.
 *
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/godotstage.js — edit the JSDoc there, never this file.
/** Is there an engine to start here — the shell around this page carries `godot.start`? */
export function godotAvailable(): any;
/**
 * The current frame as a PNG in Downloads (the shell writes it when the project has rendered it).
 * @param name the file name; the shell picks `portal-<time>.png` when absent
 * @returns `{ name, bytes }` — bytes is 0 until the project answers; the toast on the device says the rest
 */
export function godotSave(name: any): any;
/**
 * The Godot engine under the page: starts the pack on mount, streams its state, forwards params and gestures,
 * stops on unmount.
 * @param props see the module note
 * @returns the stage element (empty where there is no engine)
 */
export function GodotStage({ pack, params, onState, gestures, className, children }: {
    pack: any;
    params?: {};
    onState: any;
    gestures?: boolean;
    className?: string;
    children: any;
}): any;
