/**
 * Groove theory: the maths behind "generate a beat a human actually wants to move to", so no music app has
 * to reinvent it. Pure functions, zero deps, no DOM. Four results from the literature — Euclidean rhythms
 * (`bjorklund`), Longuet-Higgins & Lee syncopation (`syncopation`), Witek's inverted-U (`grooveU`) and
 * Bowling & Purves harmonicity (`harmonicity`) — feed a scored search (`generateGroove`) that beats random by
 * construction, which the unit gate asserts.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/groove.js — edit the JSDoc there, never this file.
/**
 * Euclidean rhythm (Toussaint 2005 / Bjorklund): spread k onsets over n steps as evenly as possible.
 * @param k number of onsets
 * @param n number of steps
 * @returns a boolean array of length n, true where an onset falls
 */
export function bjorklund(k: any, n: any): any[];
/**
 * Raw Longuet-Higgins & Lee syncopation score of a 16-step pattern, summed over the bar.
 * @param p boolean pattern of length N
 * @returns the summed weight difference (0 for an empty or unsyncopated pattern)
 */
export function syncopation(p: any): number;
/**
 * Syncopation per onset, normalised to 0..1 so patterns of different density compare fairly.
 * @param p boolean pattern of length N
 * @returns a value in 0..1
 */
export function syncopationNorm(p: any): number;
/**
 * Consonance of an interval (Bowling & Purves 2018), scored from its just-intonation ratio.
 * @param semitones interval from the root in semitones (any integer; reduced mod 12)
 * @returns a value in 0..1 — unison/octave/fifth high, tritone/minor-second low
 */
export function harmonicity(semitones: any): number;
/**
 * Seeded mulberry32 PRNG.
 * @param seed 32-bit integer seed
 * @returns a function yielding uniform floats in [0, 1)
 */
export function mulberry32(seed: any): () => number;
/**
 * Draw a 16-step bass riff: tonic/fifth on strong positions, harmonicity-weighted pentatonic notes elsewhere.
 * @param rng a seeded random function (see `mulberry32`)
 * @returns an array of N semitone offsets from the root
 */
export function makeRiff(rng: any): any[];
/**
 * Mean harmonicity of the riff notes that actually sound.
 * @param riff semitone offsets per step (from `makeRiff`)
 * @param bassPattern boolean pattern of the steps where a bass voice fires
 * @returns a value in 0..1, 0 when no bass step fires
 */
export function riffHarmonicity(riff: any, bassPattern: any): number;
/**
 * Draw the line-up for one generation: each role plays with probability `p`, and a low-band voice is always kept.
 * @param rng a seeded random function
 * @param roles the app's voice roles `[{ id, band, ks, rots, p }]`
 * @returns the subset of roles that will play
 */
export function sampleVoices(rng: any, roles: any): any;
/**
 * Build one candidate groove from the fixed line-up.
 * @param rng a seeded random function
 * @param voices the roles that play (from `sampleVoices`)
 * @returns `{ tracks: { [id]: bool[N] }, riff }`
 */
export function buildCandidate(rng: any, voices: any): {
    tracks: {};
    riff: any[];
};
/**
 * Score a candidate against the four literature results plus density, backbeat, floor and doubling terms.
 * @param cand a candidate from `buildCandidate`
 * @param roles the roles the candidate's tracks belong to
 * @returns the score — higher is more likely to make a human move
 */
export function scoreGroove(cand: any, roles: any): number;
/**
 * Generate a groove: fix the line-up, draw `tries` candidates from the Euclidean space and keep the best-scoring one.
 * @param roles the app's voice roles `[{ id, band, ks, rots, p, bass?, backbeat? }]`
 * @param {object} [opts]
 * @param [opts.seed] seed for reproducibility
 * @param [opts.tries] candidates to score (default 220)
 * @returns the best candidate with `voices`, `seed`, `score`, `meanScore` and `tries` attached
 */
export function generateGroove(roles: any, { seed, tries }?: {
    seed?: any;
    tries?: any;
}): {
    voices: any;
    seed: number;
    score: number;
    meanScore: number;
    tries: any;
    tracks: {};
    riff: any[];
};
/**
 * Groove theory: the maths behind "generate a beat a human actually wants to move to", so no music app has
 * to reinvent it. Pure functions, zero deps, no DOM. Four results from the literature — Euclidean rhythms
 * (`bjorklund`), Longuet-Higgins & Lee syncopation (`syncopation`), Witek's inverted-U (`grooveU`) and
 * Bowling & Purves harmonicity (`harmonicity`) — feed a scored search (`generateGroove`) that beats random by
 * construction, which the unit gate asserts.
 * @module
 */
/** Steps per bar — a 16-step 4/4 grid (sixteenths). */
export const N: 16;
/** Metric weight of each of the 16 grid positions (Longuet-Higgins & Lee): 0 on the downbeat down to -4 on a sixteenth offbeat. */
export const METRIC_WEIGHTS: number[];
/**
 * Rotate a pattern left by r steps (negative r rotates right).
 * @param p the pattern array
 * @param r number of steps to rotate
 * @returns a new array of the same length
 */
export function rotate(p: any, r: any): any;
/**
 * Fraction of steps that carry an onset.
 * @param p boolean pattern
 * @returns onsets ÷ length, 0 for an empty pattern
 */
export function density(p: any): number;
/**
 * Witek's inverted-U as a Gaussian: reward peaks at `mu` and falls off either side.
 * @param x the measured value (e.g. normalised syncopation)
 * @param mu where the reward peaks
 * @param sigma how forgiving the peak is
 * @returns a reward in 0..1
 */
export function grooveU(x: any, mu: any, sigma: any): number;
/** Per-band syncopation targets `{ mu, sigma, w }` for the low / mid / high roles — each its own inverted-U and weight. */
export const BANDS: {};
