/**
 * Radiance (.hdr) decoding for image-based lighting. A browser cannot decode Radiance, so this is the short
 * path: the asset stays the original CC0 file and the bytes come back UNCHANGED as RGBE (three mantissas
 * plus a shared exponent) for the shader to expand in one instruction. Pure functions over bytes — no DOM,
 * no GPU — so `deno test` covers the parser. Exports `decodeHDR`, `rgbeToLinear` and `downsampleRGBE`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/hdr.js — edit the JSDoc there, never this file.
/**
 * Radiance (.hdr) decoding for image-based lighting. A browser cannot decode Radiance, so this is the short
 * path: the asset stays the original CC0 file and the bytes come back UNCHANGED as RGBE (three mantissas
 * plus a shared exponent) for the shader to expand in one instruction. Pure functions over bytes — no DOM,
 * no GPU — so `deno test` covers the parser. Exports `decodeHDR`, `rgbeToLinear` and `downsampleRGBE`.
 * @module
 */
/** @returns {{ width: number, height: number, rgbe: Uint8Array }} RGBA8 bytes, alpha = shared exponent + 128 */
export function decodeHDR(bytes: any): {
    width: number;
    height: number;
    rgbe: Uint8Array;
};
/** One RGBE pixel → linear radiance. The same maths the shader does, for tests and for CPU-side checks. */
export function rgbeToLinear(r: any, g: any, b: any, e: any): number[];
/**
 * Box-downsample an RGBE image, averaging in LINEAR radiance.
 *
 * Averaging the packed bytes instead would be wrong in a way that is easy to miss: the exponent is SHARED
 * per pixel, so two neighbours at different scales cannot be mixed byte-wise. Doing it naively dims every
 * bright source — precisely the part of the map that makes a reflection look like metal.
 */
export function downsampleRGBE({ width, height, rgbe }: {
    width: any;
    height: any;
    rgbe: any;
}, outW: any): {
    width: any;
    height: number;
    rgbe: Uint8Array;
};
