/**
 * Tiny i18n (pure, zero-dependency). The whole UI is translated through `T()` over flat `{ key: string }`
 * dicts, falling back to the raw key so a miss is visible rather than a crash. Also owns the runtime's own
 * chrome strings (`SYS`/`sys`, `MEDIA`/`media`) so no app restates them, and the locale-aware time labels
 * (`whenLabel`, `sinceLabel`, `ago`) so a data.js never bakes a language into a date.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/i18n.js — edit the JSDoc there, never this file.
/**
 * Locale-aware absolute + relative label for a future timestamp (`format: "when"`).
 * @param dict the app dict carrying whenPast / whenMin / whenHours / whenDays
 * @param ts a Date-parseable timestamp
 * @param locale the active locale code
 * @param full include the relative countdown tail (default true)
 * @returns e.g. "12 Sep, 14:30 · in 3 h", or "" for an invalid date
 */
export function whenLabel(dict: any, ts: any, locale: any, full?: boolean): string;
/**
 * Fine-grained "x ago" label for live feeds (`format: "since"`), at seconds/minutes granularity.
 * @param dict the app dict carrying sinceNow / sinceSec / sinceMin / sinceHour / sinceDay
 * @param ts a millisecond timestamp
 * @param locale the active locale code
 * @returns the translated relative label
 */
export function sinceLabel(dict: any, ts: any, locale: any): any;
/**
 * Coarse relative date for card meta (`format: "ago"`): today / yesterday / days / weeks, then a locale date.
 * @param dict the app dict carrying agoToday / agoYesterday / agoDays / agoWeeks
 * @param ts a millisecond timestamp
 * @param locale the active locale code
 * @returns the translated relative label or a formatted date
 */
export function ago(dict: any, ts: any, locale: any): any;
/**
 * Translate a key through a locale dict, interpolating `{param}` tokens; a missing key returns the key itself.
 * @param dict flat `{ key: string }` locale map (may be undefined)
 * @param key the string key
 * @param params optional `{ name: value }` substitutions for `{name}` tokens
 * @returns the translated, interpolated string
 */
export function T(dict: any, key: any, params: any): any;
/**
 * Pick the dict for a locale from an app's i18n table, falling back to `en`, then to an empty dict.
 * @param i18n `{ [locale]: dict }`
 * @param locale the active locale code
 * @returns the flat dict to hand to `T`
 */
export function dictFor(i18n: any, locale: any): any;
/** Built-in runtime chrome strings, `{ key: { en, uk } }` — the shell, sheets, share, update, account and APK flows. */
export const SYS: {};
/**
 * Read a `SYS` string for a locale, falling back to English, then to "".
 * @param key a `SYS` key
 * @param locale the active locale code
 * @returns the localised string
 */
export function sys(key: any, locale: any): any;
/** Built-in video-player chrome strings, `{ key: { en, uk } }`. */
export const MEDIA: {
    player: {
        en: string;
        uk: string;
    };
    back_1: {
        en: string;
        uk: string;
    };
    back: {
        en: string;
        uk: string;
    };
    loading: {
        en: string;
        uk: string;
    };
    unavailable: {
        en: string;
        uk: string;
    };
    openExternal: {
        en: string;
        uk: string;
    };
    pip: {
        en: string;
        uk: string;
    };
    fullscreen: {
        en: string;
        uk: string;
    };
    exitFullscreen: {
        en: string;
        uk: string;
    };
};
/**
 * Read a `MEDIA` string for a locale, falling back to English, then to "".
 * @param key a `MEDIA` key
 * @param locale the active locale code
 * @returns the localised string
 */
export function media(key: any, locale: any): any;
