/**
 * Tiny i18n (pure, zero-dependency). The whole UI is translated through `T()` over flat `{ key: string }`
 * dicts, falling back to the raw key so a miss is visible rather than a crash. Also owns the runtime's own
 * chrome strings (`SYS`/`sys`, `MEDIA`/`media`) so no app restates them, and the locale-aware time labels
 * (`whenLabel`, `sinceLabel`, `ago`) so a data.js never bakes a language into a date.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/i18n.js — edit the JSDoc there, never this file.
/**
 * Locale-aware absolute + relative label for a future timestamp (`format: "when"`).
 * @param dict the app dict carrying whenPast / whenMin / whenHours / whenDays
 * @param ts a Date-parseable timestamp
 * @param locale the active locale code
 * @param full include the relative countdown tail (default true)
 * @returns e.g. "12 Sep, 14:30 · in 3 h", or "" for an invalid date
 */
export function whenLabel(dict: any, ts: any, locale: any, full?: boolean): string;
/**
 * Fine-grained "x ago" label for live feeds (`format: "since"`), at seconds/minutes granularity.
 * @param dict the app dict carrying sinceNow / sinceSec / sinceMin / sinceHour / sinceDay
 * @param ts a millisecond timestamp
 * @param locale the active locale code
 * @returns the translated relative label
 */
export function sinceLabel(dict: any, ts: any, locale: any): any;
/**
 * Coarse relative date for card meta (`format: "ago"`): today / yesterday / days / weeks, then a locale date.
 * @param dict the app dict carrying agoToday / agoYesterday / agoDays / agoWeeks
 * @param ts a millisecond timestamp
 * @param locale the active locale code
 * @returns the translated relative label or a formatted date
 */
export function ago(dict: any, ts: any, locale: any): any;
export function T(dict: any, key: any, params: any): any;
export function dictFor(i18n: any, locale: any): any;
export namespace SYS {
    namespace exit {
        let en: string;
        let uk: string;
    }
    namespace deleted {
        let en_1: string;
        export { en_1 as en };
        let uk_1: string;
        export { uk_1 as uk };
    }
    namespace undo {
        let en_2: string;
        export { en_2 as en };
        let uk_2: string;
        export { uk_2 as uk };
    }
    namespace cancel {
        let en_3: string;
        export { en_3 as en };
        let uk_3: string;
        export { uk_3 as uk };
    }
    namespace signInTitle {
        let en_4: string;
        export { en_4 as en };
        let uk_4: string;
        export { uk_4 as uk };
    }
    namespace pairBody {
        let en_5: string;
        export { en_5 as en };
        let uk_5: string;
        export { uk_5 as uk };
    }
    namespace pairDone {
        let en_6: string;
        export { en_6 as en };
        let uk_6: string;
        export { uk_6 as uk };
    }
    namespace pairFail {
        let en_7: string;
        export { en_7 as en };
        let uk_7: string;
        export { uk_7 as uk };
    }
    namespace signInBody {
        let en_8: string;
        export { en_8 as en };
        let uk_8: string;
        export { uk_8 as uk };
    }
    namespace close {
        let en_9: string;
        export { en_9 as en };
        let uk_9: string;
        export { uk_9 as uk };
    }
    namespace clean {
        let en_10: string;
        export { en_10 as en };
        let uk_10: string;
        export { uk_10 as uk };
    }
    namespace cleanExit {
        let en_11: string;
        export { en_11 as en };
        let uk_11: string;
        export { uk_11 as uk };
    }
    namespace share {
        let en_12: string;
        export { en_12 as en };
        let uk_12: string;
        export { uk_12 as uk };
    }
    namespace shareCopied {
        let en_13: string;
        export { en_13 as en };
        let uk_13: string;
        export { uk_13 as uk };
    }
    namespace updateReady {
        let en_14: string;
        export { en_14 as en };
        let uk_14: string;
        export { uk_14 as uk };
    }
    namespace restart {
        let en_15: string;
        export { en_15 as en };
        let uk_15: string;
        export { uk_15 as uk };
    }
    namespace aPlay {
        let en_16: string;
        export { en_16 as en };
        let uk_16: string;
        export { uk_16 as uk };
    }
    namespace aPause {
        let en_17: string;
        export { en_17 as en };
        let uk_17: string;
        export { uk_17 as uk };
    }
    namespace aStop {
        let en_18: string;
        export { en_18 as en };
        let uk_18: string;
        export { uk_18 as uk };
    }
    namespace aPrev {
        let en_19: string;
        export { en_19 as en };
        let uk_19: string;
        export { uk_19 as uk };
    }
    namespace aNext {
        let en_20: string;
        export { en_20 as en };
        let uk_20: string;
        export { uk_20 as uk };
    }
    namespace aSeek {
        let en_21: string;
        export { en_21 as en };
        let uk_21: string;
        export { uk_21 as uk };
    }
    namespace aRepeat {
        let en_22: string;
        export { en_22 as en };
        let uk_22: string;
        export { uk_22 as uk };
    }
    namespace aShuffle {
        let en_23: string;
        export { en_23 as en };
        let uk_23: string;
        export { uk_23 as uk };
    }
    namespace more {
        let en_24: string;
        export { en_24 as en };
        let uk_24: string;
        export { uk_24 as uk };
    }
    namespace back {
        let en_25: string;
        export { en_25 as en };
        let uk_25: string;
        export { uk_25 as uk };
    }
    namespace apkRow {
        let en_26: string;
        export { en_26 as en };
        let uk_26: string;
        export { uk_26 as uk };
    }
    namespace signOut {
        let en_27: string;
        export { en_27 as en };
        let uk_27: string;
        export { uk_27 as uk };
    }
    namespace signedOut {
        let en_28: string;
        export { en_28 as en };
        let uk_28: string;
        export { uk_28 as uk };
    }
    namespace accountVia {
        let en_29: string;
        export { en_29 as en };
        let uk_29: string;
        export { uk_29 as uk };
    }
    namespace apkTitle {
        let en_30: string;
        export { en_30 as en };
        let uk_30: string;
        export { uk_30 as uk };
    }
    namespace apkGenerate {
        let en_31: string;
        export { en_31 as en };
        let uk_31: string;
        export { uk_31 as uk };
    }
    namespace apkGenerating {
        let en_32: string;
        export { en_32 as en };
        let uk_32: string;
        export { uk_32 as uk };
    }
    namespace apkDone {
        let en_33: string;
        export { en_33 as en };
        let uk_33: string;
        export { uk_33 as uk };
    }
    namespace apkErr {
        let en_34: string;
        export { en_34 as en };
        let uk_34: string;
        export { uk_34 as uk };
    }
    namespace apkRate {
        let en_35: string;
        export { en_35 as en };
        let uk_35: string;
        export { uk_35 as uk };
    }
    namespace apkNote {
        let en_36: string;
        export { en_36 as en };
        let uk_36: string;
        export { uk_36 as uk };
    }
}
export function sys(key: any, locale: any): any;
export namespace MEDIA {
    export namespace player {
        let en_37: string;
        export { en_37 as en };
        let uk_37: string;
        export { uk_37 as uk };
    }
    export namespace back_1 {
        let en_38: string;
        export { en_38 as en };
        let uk_38: string;
        export { uk_38 as uk };
    }
    export { back_1 as back };
    export namespace loading {
        let en_39: string;
        export { en_39 as en };
        let uk_39: string;
        export { uk_39 as uk };
    }
    export namespace unavailable {
        let en_40: string;
        export { en_40 as en };
        let uk_40: string;
        export { uk_40 as uk };
    }
    export namespace openExternal {
        let en_41: string;
        export { en_41 as en };
        let uk_41: string;
        export { uk_41 as uk };
    }
    export namespace pip {
        let en_42: string;
        export { en_42 as en };
        let uk_42: string;
        export { uk_42 as uk };
    }
    export namespace fullscreen {
        let en_43: string;
        export { en_43 as en };
        let uk_43: string;
        export { uk_43 as uk };
    }
    export namespace exitFullscreen {
        let en_44: string;
        export { en_44 as en };
        let uk_44: string;
        export { uk_44 as uk };
    }
}
export function media(key: any, locale: any): any;
