/**
 * # runtime/imagejob.js — the image race, client side
 *
 * One shape for every generation the edge runs (text→image, image→image, blend, style): a POST starts a
 * job, short polls carry it — a cold Space can take well over a minute and nginx caps a single `/feed`
 * request at 60 s, so the wait lives in polls that each return in milliseconds. Every poll says how many
 * pictures exist; each picture's bytes are one more GET, pulled the moment it lands rather than at the
 * end. Lifted from mirage's `race.js` when a second app (vydyvo, the living screensaver) needed the same
 * protocol — the wire contract belongs to the runtime, not to an app.
 *
 * ![The imagejob module's map: start, follow, cancel, and the edge's slides protocol](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-imagejob.svg)
 *
 * ## Import
 * ```js
 * import { startJob, follow, cancelJob } from "/_rt/imagejob.js";                    // an app's page: the import map resolves /_rt/
 * import { startJob, follow, cancelJob } from "@microspec/core/runtime/imagejob.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link startJob} — `(base, body)` POSTs the job and resolves its id; throws `{ code }` with the i18n key a view should show.
 * - {@link follow} — `({ base, job, alive, onLive, onSlide })` polls until the race ends; resolves `"done" | "error" | "busy" | "timeout" | "stale"`.
 * - {@link followOne} — `({ base, job, alive, onLive })` the ONE-RESULT contract (`k: 1`, and every audio or video job): the status URL itself
 *   turns into the bytes; resolves `{ status, blob?, url?, by? }` with the same status words.
 * - {@link cancelJob} — `(base, job)` tells the edge to stop a race nobody will watch; fire-and-forget.
 * - {@link POLLS} · {@link EVERY} — the poll budget (135 × 1500 ms ≈ 200 s), exported so a caller can size its own timers.
 *
 * ## In practice
 * ```js
 * import { startJob, follow } from "/_rt/imagejob.js";                                 // apps/vydyvo/state.js
 * import { VPS_PROXY } from "/_rt/feed.js";
 *
 * const base = `${VPS_PROXY}/image`;
 * const job = await startJob(base, { prompt, quality: "2k", aspect: "screen", ratio, seed, k: 2 });
 * const status = await follow({ base, job, alive: () => run === runs, onSlide: (s) => frames.push(s) });
 * ```
 *
 * ## How it fits
 * Imports nothing from the runtime. `apps/vydyvo/state.js` consumes it; `apps/mirage/race.js` still carries
 * its own copy of the same protocol (the extension `.ext` of a landed blob is the one thing mirage adds).
 *
 * ## Invariants and pitfalls
 * - The poll budget must OUTLAST the edge's own race budget: a client that gave up at 150 s threw away a
 *   picture that landed at 160 s (measured 2026-08-20). 135 × 1.5 s it is.
 * - `alive()` is the caller's staleness guard — a superseded run resolves `"stale"` and lands nothing.
 * - `k > 1` is the SLIDES protocol and the only one that honours `aspect` + `ratio`; `k: 1` returns the
 *   single result's bytes from the status URL itself — that is {@link followOne}'s contract (`/feed/voice`
 *   answers only this way: one clip, `content-type: audio/*`), and `follow` never reads it.
 * - `"busy"` is capacity, not words: every Space queued out or refused. Back off; do not retry at once.
 * - Running out of polls CANCELS the job on the edge, or it spends the day's quota on pictures nobody reads.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/imagejob.js — edit the JSDoc there, never this file.
/**
 * Start a generation job.
 * @param base the route, e.g. `${VPS_PROXY}/image`
 * @param body the job body (`prompt`, `quality`, `aspect`, `ratio`, `seed`, `k`, `model`, or an edit's `image`/`images`)
 * @returns the job id
 * @throws `{ code }` — `eNetwork` (fetch threw), `eRate` (429), `eBig` (413), `eSignIn` (401), `eFailed` (any other refusal or no id)
 */
export function startJob(base: any, body: any): Promise<any>;
/**
 * Follow a job to its end.
 * @param opts `base` the route · `job` the id · `alive()` the caller's staleness guard · `onLive(meta)` mirrors the worker's progress · `onSlide(slide)` fires per picture as it lands: `{ url, blob, w, h, by, n }`
 * @returns `"done" | "error" | "busy" | "timeout" | "stale"`
 */
export function follow({ base, job, alive, onLive, onSlide }: {
    base: any;
    job: any;
    alive?: () => boolean;
    onLive: any;
    onSlide: any;
}): Promise<any>;
/**
 * Follow a ONE-RESULT job to its end: the status URL answers progress JSON until the bytes themselves arrive.
 * @param opts `base` the route (e.g. `${VPS_PROXY}/voice`) · `job` the id · `alive()` the caller's staleness guard · `onLive(meta)` mirrors progress (`stage`, `phase`, `eta`, `pct`, `elapsed`)
 * @returns `{ status, blob?, url?, by? }` — `status` is `"done" | "error" | "busy" | "timeout" | "stale"`; `blob`/`url`/`by` only on `"done"`
 */
export function followOne({ base, job, alive, onLive }: {
    base: any;
    job: any;
    alive?: () => boolean;
    onLive: any;
}): Promise<{
    status: string;
    blob?: undefined;
    url?: undefined;
    by?: undefined;
} | {
    status: string;
    blob: any;
    url: any;
    by: any;
}>;
/**
 * Cancel a job on the edge (idempotent, fire-and-forget).
 * @param base the route
 * @param job the id; a falsy id is a no-op
 */
export function cancelJob(base: any, job: any): void;
/** Poll count — 135 × {@link EVERY} ≈ 200 s, past the edge's own race budget. */
export const POLLS: 135;
/** Poll period in milliseconds. */
export const EVERY: 1500;
