/**
 * The runtime entry: an app's index.html imports its spec.json + data.js and calls `start()`. It validates
 * the spec, builds the store, wires theme/locale/haptics, installs the sealed fetch, registers the
 * cache-first service worker and owns the Back-button routing invariant (one history entry per open
 * overlay, double-Back-to-exit at the root). Exports `start` only.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/index.js — edit the JSDoc there, never this file.
/**
 * Boot the app: validate the spec, create the store, mount the UI and start loading (or streaming) data.
 * @param spec the app's spec.json object
 * @param arg2 a `load` function (data app) or `{ load?, views?, stream? }` (tool / stream app)
 * @returns nothing; throws when the spec is invalid so a broken app never starts half-way
 */
export function start(spec: any, arg2: any): void;
