/**
 * # @microspec/core — the appless core of DreamStudio
 *
 * ![The portal: a ring of woven light, the four parts of the core beside it](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/hero.svg)
 *
 * A micro-PWA is a `spec.json` plus a `data.js` adapter (and, for an instrument, a view) against a
 * VERIFIED, zero-build runtime. This package is that runtime and everything that verifies it: the systemic
 * modules an app's page imports as `/_rt/<name>.js`, the spec schema, the gates (Deno first, then a real
 * Chromium with axe), the generators, and the tools that run all of it as one pipeline registry (8n8).
 * It carries NO apps — the product, DreamStudio, does, and pins this package.
 *
 * ## Two channels, one version
 *
 * ```json
 * { "imports": { "@microspec/core": "jsr:@microspec/core@<v>", "@microspec/core/": "jsr:@microspec/core@<v>/" } }
 * ```
 * ```json
 * { "dependencies": { "@microspec/core": "npm:@jsr/microspec__core@<v>" } }
 * ```
 *
 * EXECUTION rides the `jsr:` pin — tools and gates run from the registry
 * (`deno run -A jsr:@microspec/core@<v>/8n8 gates`). FILES ride the npm-compat tarball — `deno install`
 * materialises the runtime (js, css, sprites) under node_modules, which the page server and the build read.
 * Bump both, then `deno task install` and `deno task rtmap`. The laws of the three realms a tree runs in
 * (a checkout, the registry, the browser's import map) are on the `rtmap` and `preflight` pages.
 *
 * ## What is in the box
 *
 * - **runtime/** — the systemic modules: the render catalogue (`runtime/render.js`), the UI kit
 *   (`runtime/ui.js`: Sheet · Segmented · Island · Panel · Slider · Transport), the store and routing
 *   (`runtime/store.js`, `runtime/overlay.js`), i18n, the gate fixture switch (`runtime/gate.js`), audio and
 *   DSP (`audio`, `spectrum`, `groove`, `melody`), sensors and geo (`sensors`, `geofix`, `geomag`, `globe`,
 *   `orbit`), the Android shell bridge (`shell`, `shell-actions`, `apk`), identity and the sealed transport
 *   (`auth`, `account`, `sealed`, `sealedfetch`), the service-worker core, and the theme (`theme.css`).
 * - **schema** — `spec.schema.json` and its validator (`schema`): the contract, machine-checked.
 * - **gates** — `preflight` (Deno, no browser), `verify` (Chromium + axe at every breakpoint, per tab),
 *   `dist-eye` (the BUILT site in a real browser), `caps` (declared vs. used capabilities).
 * - **gen** — `scaffold` (spec → a runnable app), `authorless` (recipe → a complete list app, no LLM).
 * - **tools** — `8n8` (the registry and runner), `affected`, `build`, `sw`, `counts`, `readme`, `manifest`,
 *   `rtmap`, `relimports`, `noundef`, `kit`, `shell`, `graph`, `demo`, `dts`.
 *
 * ## The loop
 *
 * `deno task gates` runs the deterministic half of the registry — no network, no Chromium, about twenty
 * seconds — and is the floor before every push. CI runs `verify` for every affected app in a real browser,
 * the deploy builds and judges the built site with `dist-eye`, and a red main never deploys. Every gate
 * names its failing element: a red says WHY, so one CI round returns the whole work list.
 *
 * ## start()
 *
 * An app's page imports its `spec.json` and `data.js` and calls {@link start}: it validates the spec, builds
 * the store, wires theme, locale and haptics, installs the sealed fetch, registers the cache-first service
 * worker and owns the Back-button routing invariant — one history entry per open overlay, double-Back to
 * exit at the root. It is this module's only export.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/index.js — edit the JSDoc there, never this file.
/**
 * Boot the app: validate the spec, create the store, mount the UI and start loading (or streaming) data.
 * @param spec the app's spec.json object
 * @param arg2 a `load` function (data app) or `{ load?, views?, stream? }` (tool / stream app)
 * @returns nothing; throws when the spec is invalid so a broken app never starts half-way
 */
export function start(spec: any, arg2: any): void;
