/**
 * # runtime/intake.js — where a picture comes from
 *
 * Every app that starts from a photo asks the same three questions — upload, camera, or the last picture the
 * farm made — and then needs the same two conversions: a capped JPEG data URL to send, and the true pixel
 * size of what came back. `imagine` carried two copies of each, `mirage` and `zir` one each ("a third app
 * with a photo intake is the signal they belong in the core's kit" — the third was `rukh`, 2026-09-03).
 * This module is that kit: the chooser island, the primed viewfinder, the bitmap helpers, and the gate's
 * deterministic stand-in picture. The copy is built in (en · uk), like `camprime.js` — a shared component
 * that demands an i18n key from every app that mounts it ships the raw key the first time someone forgets.
 *
 * ![The intake module's map: the chooser, the viewfinder, the bitmap helpers and their dependants](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-intake.svg)
 *
 * ## Import
 * ```js
 * import { Chooser, Camera, toDataURL, sizeOf, extOf, mockArt } from "/_rt/intake.js";                    // an app's page: the import map resolves /_rt/
 * import { Chooser, Camera, toDataURL, sizeOf, extOf, mockArt } from "@microspec/core/runtime/intake.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link Chooser} — `({ loc, onPick, onCamera, compact })` the frost island with the three sources; `compact` is one row of glyphs for a half-stage.
 * - {@link Camera} — `({ loc, reason, privacy, onCapture, onClose, onSettings })` the viewfinder, PRIMED before it opens (never a cold camera), one shutter.
 * - {@link toDataURL} — `(url, maxSide)` any same-origin picture → a JPEG data URL capped at {@link MAX_SIDE} on the long side, plus the size sent.
 * - {@link sizeOf} — `(blobOrUrl)` the pixel size of a picture, MEASURED with `createImageBitmap` (naturalWidth lies on a scaled `<img>`).
 * - {@link extOf} — `(blob)` `webp` · `png` · `jpg` from the blob's type, for a filename.
 * - {@link mockArt} — `(seed, scale)` a deterministic SVG data URL for the gate: no network, the same frame for the same seed.
 * - {@link MAX_SIDE} — 1024: the Spaces clamp beyond it, the POST body stays under the proxy's cap, and an upscaler's 4× stays at 4096².
 *
 * ## In practice
 * ```js
 * const [src, setSrc] = useState(null), [cam, setCam] = useState(false);
 * html`<${Stage}>
 *   ${src ? html`<img src=${src} />` : cam
 *     ? html`<${Camera} loc=${loc} reason=${T(t, "camReason")} privacy=${T(t, "primePrivacy")} onCapture=${(d) => { setSrc(d); setCam(false); }} onClose=${() => setCam(false)} onSettings=${() => S.screen.set("perms")} />`
 *     : html`<${Chooser} loc=${loc} onPick=${setSrc} onCamera=${() => setCam(true)} />`}
 * <//>`;
 * const { data, w, h } = await toDataURL(src);   // what goes on the wire
 * ```
 *
 * ## Why
 * The chooser floats on the stage as a frost island because a solid panel would punch a hole in it; the
 * viewfinder never opens cold because the priming screen is where the honest privacy line lives (the frame
 * IS uploaded — say so). The gate has no camera and no network, so `mockArt` stands in for both, marked by
 * the app with `data-live`, and the e2e reads `[data-src-upload]` / `[data-shutter]` — the same hooks every
 * consumer already tests.
 *
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/intake.js — edit the JSDoc there, never this file.
/**
 * Any same-origin image (blob: / data: / svg) → a capped JPEG data URL, the shape the edge forwards to a Space's
 * file input. Same-origin only, so the canvas never taints. Also reports the size it sent.
 * @param url the picture's URL
 * @param maxSide the cap on the long side (default {@link MAX_SIDE})
 * @returns `{ data, w, h }` — the JPEG data URL and the pixel size sent
 */
export function toDataURL(url: any, maxSide?: number): Promise<any>;
/**
 * The pixel size of a picture, measured — `naturalWidth` lies on a scaled `<img>`; a decoded bitmap does not.
 * @param blobOrUrl a Blob, or a URL `fetch` can read
 * @returns `{ w, h }`, or null when the bytes do not decode
 */
export function sizeOf(blobOrUrl: any): Promise<{
    w: any;
    h: any;
}>;
/**
 * The chooser: upload · camera · the last picture the farm made, on a frost island over the stage (a solid
 * panel would punch a hole in it). `compact` is the same three sources as glyphs in one row, for a slot that
 * shares the stage with another (a blend's two pictures): a labelled column needs ~160 px a half-stage lacks.
 * Under the gate the third source is a fixed `mockArt`, so it exists on the shot and in e2e.
 * @param props `{ loc, onPick(url), onCamera(), compact? }`
 * @returns the preact vnode, absolutely positioned over its stage
 */
export function Chooser({ loc, onPick, onCamera, compact }: {
    loc: any;
    onPick: any;
    onCamera: any;
    compact?: boolean;
}): any;
/**
 * The viewfinder: primed before it opens (never a cold camera), the back stream while enabled, one shutter.
 * `privacy` is the honest line for the priming screen — the frame IS uploaded, so the built-in "processed on
 * your device" must be overridden here; `onSettings` opens the app's permissions route when the camera is blocked.
 * @param props `{ loc, reason, privacy, onCapture(dataUrl), onClose(), onSettings() }`
 * @returns the preact vnode, absolutely positioned over its stage
 */
export function Camera({ loc, reason, privacy, onCapture, onClose, onSettings }: {
    loc: any;
    reason: any;
    privacy: any;
    onCapture: any;
    onClose: any;
    onSettings: any;
}): any;
/** The upload cap on the long side: 1024 → an upscaler's 4× is 4096², and the JPEG stays ~300 KB on the wire. */
export const MAX_SIDE: 1024;
/**
 * A deterministic stand-in picture for the gate: no network, the same frame for the same seed, so a shot and an
 * e2e are stable and CI never spends a GPU minute. Fine lines, so "before" and "after" differ visibly when the
 * gate's after is the same picture at a larger `scale`.
 * @param seed any integer — picks the hue
 * @param scale the intrinsic size multiplier (1 = 96×128)
 * @returns an `image/svg+xml` data URL
 */
export function mockArt(seed: any, scale?: number): string;
/**
 * The file extension a blob's type implies, for a filename.
 * @param blob the picture
 * @returns `"webp"` · `"png"` · `"jpg"`
 */
export function extOf(blob: any): "png" | "webp" | "jpg";
