/**
 * # runtime/material.js — the material picker's mechanism: a product's theme registry, applied by one link swap
 *
 * A product may ship several theme MODULES (`rt/theme-<id>.css`, each self-sufficient: `@import
 * "./runtime.css"` then its material) and a registry, `rt/themes.json`, listing them. The core knows no
 * product, so everything here is conditional on that registry existing: {@link loadMaterials} reads
 * `/_rt/themes.json` (an empty list when there is none — the profile then shows no picker), and
 * {@link applyMaterial} switches the page to a material by rewriting the ONE stylesheet link every page
 * carries (`/_rt/theme.css` → `/_rt/theme-<id>.css`) and stamping `html[data-material]`. The chosen id
 * persists farm-wide (`ms:material`, deliberately NOT namespaced by app — a material is the person's, not
 * the app's). Spec: DreamStudio `docs/research/themes.md`.
 *
 * ![The module's map](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-material.svg)
 *
 * ## Import
 * ```js
 * import { loadMaterials, applyMaterial } from "/_rt/material.js";                   // an app's page
 * import { applyMaterial } from "@microspec/core/runtime/material.js";             // a Deno test
 * ```
 *
 * ## What it exports
 * - {@link MATERIAL_KEY} — the localStorage key of the choice, `ms:material`, shared by every app on the origin.
 * - {@link loadMaterials} — fetch the registry; `[]` when the product ships none or the network fails.
 * - {@link applyMaterial} — point the page's theme link at a material's css and stamp the document.
 * - {@link materialHref} — the pure part: the new href for a link, given the old one and the css name.
 *
 * ## In practice
 * ```js
 * // index.js, at boot — the registry decides whether a picker exists at all
 * loadMaterials().then((list) => { S.materials.set(list); if (list.length) applyMaterial(S.material.get() || list[0].id, list); });
 * S.material.listen((id) => applyMaterial(id, S.materials.get()));
 * ```
 *
 * ## How it fits
 * Imports nothing. index.js boots it and store.js holds the atoms (`S.material`, `S.materials`); render.js's
 * profile renders the row and the sheet when the registry has more than one entry. A product's overlay
 * provides the registry, the theme files and their sprites.
 *
 * ## Invariants and pitfalls
 * - One link, rewritten — never a second stylesheet appended: two materials on one page would fight over
 *   the same tokens, and a stale one would keep its sprites in the precache forever.
 * - The registry's first entry is the default: `rt/theme.css` (what a page links before any choice) must
 *   import that same module, or the first paint and the applied state disagree.
 * - An unknown id (a theme removed after being chosen) falls back to the default silently.
 * - The service worker precaches `/_rt/themes.json` when the tree ships one (deploy/sw.mjs), so the row is
 *   there offline; a material's css + sprites are cached on first use.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/material.js — edit the JSDoc there, never this file.
/**
 * Fetch a product's theme registry.
 * @param fetchFn the fetch to use (injected in tests)
 * @returns the registry entries `[{ id, name: { en, uk }, css, thumb? }]`, or `[]` when there is none
 */
export function loadMaterials(fetchFn?: any): Promise<any[]>;
/**
 * Apply a material to the document: rewrite the theme link and stamp `html[data-material]`.
 * @param id the material id; an unknown id falls back to the registry's first entry
 * @param materials the registry (see {@link loadMaterials})
 * @param doc the document (injected in tests)
 * @returns the id actually applied, or null when the registry is empty or the page has no theme link
 */
export function applyMaterial(id: any, materials: any, doc?: any): any;
/**
 * # runtime/material.js — the material picker's mechanism: a product's theme registry, applied by one link swap
 *
 * A product may ship several theme MODULES (`rt/theme-<id>.css`, each self-sufficient: `@import
 * "./runtime.css"` then its material) and a registry, `rt/themes.json`, listing them. The core knows no
 * product, so everything here is conditional on that registry existing: {@link loadMaterials} reads
 * `/_rt/themes.json` (an empty list when there is none — the profile then shows no picker), and
 * {@link applyMaterial} switches the page to a material by rewriting the ONE stylesheet link every page
 * carries (`/_rt/theme.css` → `/_rt/theme-<id>.css`) and stamping `html[data-material]`. The chosen id
 * persists farm-wide (`ms:material`, deliberately NOT namespaced by app — a material is the person's, not
 * the app's). Spec: DreamStudio `docs/research/themes.md`.
 *
 * ![The module's map](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-material.svg)
 *
 * ## Import
 * ```js
 * import { loadMaterials, applyMaterial } from "/_rt/material.js";                   // an app's page
 * import { applyMaterial } from "@microspec/core/runtime/material.js";             // a Deno test
 * ```
 *
 * ## What it exports
 * - {@link MATERIAL_KEY} — the localStorage key of the choice, `ms:material`, shared by every app on the origin.
 * - {@link loadMaterials} — fetch the registry; `[]` when the product ships none or the network fails.
 * - {@link applyMaterial} — point the page's theme link at a material's css and stamp the document.
 * - {@link materialHref} — the pure part: the new href for a link, given the old one and the css name.
 *
 * ## In practice
 * ```js
 * // index.js, at boot — the registry decides whether a picker exists at all
 * loadMaterials().then((list) => { S.materials.set(list); if (list.length) applyMaterial(S.material.get() || list[0].id, list); });
 * S.material.listen((id) => applyMaterial(id, S.materials.get()));
 * ```
 *
 * ## How it fits
 * Imports nothing. index.js boots it and store.js holds the atoms (`S.material`, `S.materials`); render.js's
 * profile renders the row and the sheet when the registry has more than one entry. A product's overlay
 * provides the registry, the theme files and their sprites.
 *
 * ## Invariants and pitfalls
 * - One link, rewritten — never a second stylesheet appended: two materials on one page would fight over
 *   the same tokens, and a stale one would keep its sprites in the precache forever.
 * - The registry's first entry is the default: `rt/theme.css` (what a page links before any choice) must
 *   import that same module, or the first paint and the applied state disagree.
 * - An unknown id (a theme removed after being chosen) falls back to the default silently.
 * - The service worker precaches `/_rt/themes.json` when the tree ships one (deploy/sw.mjs), so the row is
 *   there offline; a material's css + sprites are cached on first use.
 * @module
 */
/** The localStorage key of the chosen material — farm-wide, not per app. */
export const MATERIAL_KEY: "ms:material";
/**
 * The new href for the page's theme link: the file name swapped, the path kept (a built page links
 * `../_rt/theme.css`, a source page `/_rt/theme.css`; both keep their prefix).
 * @param href the link's current href
 * @param css the material's stylesheet name, e.g. `theme-smoke.css`
 * @returns the rewritten href
 */
export function materialHref(href: any, css: any): any;
