/**
 * Background audio + OS media session for SYNTHESISED players: a pure Web Audio page owns no media session,
 * so the OS suspends it in the background. `holdAudio` plays a tiny silent looping element to hold audio
 * focus, wires MediaSession metadata/handlers, and polyfills the session over the shell bridge inside the
 * APK where the web API is absent. Exports `silentWav` and `holdAudio`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/mediasession.js — edit the JSDoc there, never this file.
/**
 * Synthesise a minimal valid silent WAV (16-bit mono PCM, all-zero samples) as a data URI.
 * @param ms duration of silence in milliseconds (default 250)
 * @param rate sample rate in Hz (default 8000)
 * @returns a `data:audio/wav;base64,…` URI (empty payload where `btoa` is absent)
 */
export function silentWav(ms?: number, rate?: number): string;
/**
 * Hold audio focus for a synthesised player: own an OS media session (or its shell polyfill in the APK),
 * publish now-playing metadata and transport handlers, and re-resume the AudioContext on return to the tab.
 * A no-op stub where audio/mediaSession is absent, so callers never branch.
 * @param options `title`, `artist`, `artwork`, transport callbacks `onPlay`/`onPause`/`onPrev`/`onNext`, and
 *   `resumeCtx` — called on visibility return to resume the app's AudioContext
 * @returns a handle `{ supported, setPlaying, setPaused, meta, position, release }`
 */
export function holdAudio({ title, artist, artwork, onPlay, onPause, onPrev, onNext, resumeCtx }?: {
    title?: string;
    artist?: string;
    artwork?: any;
    onPlay?: any;
    onPause?: any;
    onPrev?: any;
    onNext?: any;
    resumeCtx?: any;
}): {
    supported: boolean;
    setPlaying(): void;
    setPaused(): void;
    meta(): void;
    release(): void;
} | {
    supported: any;
    setPlaying(t: any): void;
    setPaused(): void;
    meta(t: any): void;
    position(durationMs: any, positionMs: any, rate?: number): void;
    release(): void;
};
