// microspec runtime — who made this radio, where that question has an answer at all.
//
// The first three bytes of a globally-administered MAC are an IEEE-assigned OUI, so an access point's
// BSSID names its manufacturer. A BLE **random** address does not: it is cryptographic padding with two
// type bits on top, and running it through a vendor table returns a confident, entirely invented
// manufacturer. That is the exact class of lie this app was built to avoid, so the lookup refuses.
//
// What cannot be done, and why the rule below is a heuristic rather than a test: Android never hands an
// app the over-air ADDRESS TYPE (see apps/hive/RESEARCH.md), so a public address and a random one are not
// separable from bytes alone — Espressif's real OUI 24:0A:C4 has the same top two bits as a
// non-resolvable private address. So two independent signals must agree before a name is shown:
//   1. the address is globally administered (the U/L bit, 0x02 of the first octet, is CLEAR);
//   2. the prefix is actually IN the registry.
// A random address hits a registered prefix by chance in roughly 0.2% of cases (≈40k assignments out of
// 16.7M), and resolvable private addresses — the dominant rotating kind — are excluded outright.
//
// The table is an app asset (apps/hive/assets/oui.txt, generated by tools/oui/build.mjs) because it is
// 519 KB and only one app wants it. This module is the pure half: parse + look up, no fetch.

import { addrKind } from "./radar.js";

/** Parse the packed asset. Two splits and no parser, which is why the format is what it is. */
export function parseOui(text) {
  const table = new Map();
  if (typeof text !== "string" || !text) return table;
  const nl1 = text.indexOf("\n");
  const nl2 = text.indexOf("\n", nl1 + 1);
  if (nl1 < 0 || nl2 < 0) return table;
  const deltas = text.slice(0, nl1).split(",");
  const idx = text.slice(nl1 + 1, nl2).split(",");
  const vendors = text.slice(nl2 + 1).split("\n");
  let acc = 0;
  for (let i = 0; i < deltas.length; i++) {
    acc += parseInt(deltas[i], 36);
    const v = vendors[parseInt(idx[i], 36)];
    if (v) table.set(acc, v);
  }
  return table;
}

/** The 24-bit prefix of a `AA:BB:CC:…` address, or null if it is not one. */
export function prefixOf(addr) {
  if (typeof addr !== "string") return null;
  const hex = addr.replace(/[^0-9a-fA-F]/g, "");
  if (hex.length < 6) return null;
  const v = parseInt(hex.slice(0, 6), 16);
  return Number.isFinite(v) ? v : null;
}

/** Locally administered — a randomized or virtual address, never an assigned OUI. */
export function locallyAdministered(addr) {
  const p = prefixOf(addr);
  return p == null ? false : ((p >> 16) & 0x02) !== 0;
}

/**
 * The manufacturer, or **null** where the question has no honest answer.
 *
 * `kind` matters: a cell has no address at all, and a BLE address that rotates is not a vendor prefix
 * however registered the bytes happen to look.
 */
export function vendorOf(addr, kind, table) {
  if (!table || !table.size) return null;
  if (kind === "lte") return null;                       // a cell is identified by PCI, not by a MAC
  if (locallyAdministered(addr)) return null;            // randomized or virtual
  if (kind === "ble" && addrKind(addr) === "resolvable") return null;   // rotates; the prefix means nothing
  const p = prefixOf(addr);
  return p == null ? null : table.get(p) || null;
}
