/**
 * The arithmetic the Back-button routing runs on: how many history entries an overlay atom's value is worth,
 * kept pure and unit-tested so the invariant "system Back closes the top layer and never exits the app by
 * accident" is proven rather than inlined in the bootstrap. Exports `overlayDepth`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/overlay.js — edit the JSDoc there, never this file.
export function overlayDepth(v: any): number;
