/**
 * # runtime/overlay.js — the arithmetic the Back-button routing runs on
 *
 * One pure function: how many history entries an overlay atom's value is worth. The bootstrap (`index.js`)
 * keeps history balanced with the open overlays — one `pushState` per open layer, one `history.go` back per
 * layer closed from the UI — so that system Back closes the top layer and never exits the app by accident.
 * That invariant is the one every farm app inherits without writing a line, so the counting behind it lives
 * here, dependency-free and unit-tested, rather than inline in the bootstrap where nothing could prove it.
 * The lesson is the stack: a drill-down (`S.stack=["a","b"]`) is worth its LENGTH, one entry per level, which
 * is what lets Back unwind a dive one step at a time instead of collapsing the whole dive in a single press.
 *
 * ![The overlay module's map](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-overlay.svg)
 *
 * ## Import
 * ```js
 * import { overlayDepth } from "/_rt/overlay.js";                    // an app's page: the import map resolves /_rt/
 * import { overlayDepth } from "@microspec/core/runtime/overlay.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link overlayDepth} — `overlayDepth(v)`: an array's length, 1 for any other truthy value, 0 for a falsy one.
 *
 * ## In practice
 * ```js
 * import { overlayDepth } from "./overlay.js";                       // runtime/index.js, the bootstrap
 *
 * // [atom, close(), isOpen(value)] — ordered BOTTOM → TOP; Back closes the top one only
 * const overlays = [
 *   [S.stack, () => S.stack.set(S.stack.get().slice(0, -1)), (v) => v],   // one entry PER level
 *   [S.sheet, () => S.sheet.set(false), (v) => v === true],
 *   [S.detail, () => S.detail.set(null), (v) => v != null],
 * ];
 * const depthOf = ([a, , isOpen]) => overlayDepth(isOpen(a.get()));
 * const openCount = () => overlays.reduce((n, o) => n + depthOf(o), 0);
 * // openCount() grew by d → d × history.pushState; shrank by d → history.go(-d)
 * ```
 *
 * ## How it fits
 * Imports nothing. `runtime/index.js` is its one caller: the bootstrap sums `overlayDepth` over every routed
 * atom (clean, stack, sheet, installOpen, qrOpen, detail, screen, player, confirm) to know how many history
 * entries the app currently owes. No farm app imports it directly — all 74 apps inherit the invariant
 * through the bootstrap, and the generated `sw.js` of each precaches it as part of `/_rt/`. The unit gate
 * holds it in `tests/overlay_test.js`.
 *
 * ## Invariants and pitfalls
 * - Depth, not a boolean count: every overlay is worth 1 entry except a stack overlay, worth its length.
 * - An empty stack (`[]`) is closed — 0, not 1. `null`, `false` and `undefined` are 0; a detail object is 1.
 * - A stack can grow by more than one in a tick; the bootstrap pushes that many entries, so the count
 *   must be exact, never clamped to 1.
 * - The function is pure and knows nothing about atoms — it is handed the value the overlay's `isOpen`
 *   predicate produced, which is why `S.stack` passes the array through untouched.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/overlay.js — edit the JSDoc there, never this file.
/**
 * How many history entries an overlay atom's value is worth: a stack's length, 1 for an open plain overlay,
 * 0 when closed.
 * @param v the overlay atom's value (array, truthy, or falsy)
 * @returns the depth as a non-negative integer
 */
export function overlayDepth(v: any): number;
