/**
 * Runtime permissions — ONE registry, TWO backends. A permission is a thing the user grants, not an API, so
 * each entry may carry a browser backend, a shell capability, or both, and `permState` reports the gate that
 * is ACTUALLY blocking (including "needs the app"). Exports the `PERMISSIONS` registry and `GROUPS`,
 * `refreshHeld`/`heldPermissions`, `permState`, `permRequest`, `permAndroid` and the built-in `permLabels`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/permissions.js — edit the JSDoc there, never this file.
/**
 * Refresh the map of Android permissions the app actually holds from the shell's system.info.
 * @returns the held-permission map, or null where there is no shell / the call failed
 */
export function refreshHeld(): Promise<any>;
/**
 * Report the gate that is actually blocking a permission — shell first, then the browser backend.
 * @param name a key of `PERMISSIONS`
 * @returns `{ state, via }` — state: granted | partial | prompt | denied | unsupported | needsApp | staleApp;
 *   via: "shell" | "browser" | ""
 */
export function permState(name: any): Promise<{
    state: any;
    via: string;
}>;
/** Trigger the native prompt where one exists. Shell-only permissions have nothing to ask for. */
export function permRequest(name: any): Promise<any>;
/** The groups the permission registry renders in, in display order. */
export const GROUPS: string[];
export namespace PERMISSIONS {
    namespace geolocation {
        let icon: string;
        let group: string;
        function query(): Promise<any>;
        function request(): Promise<any>;
    }
    namespace notifications {
        let icon_1: string;
        export { icon_1 as icon };
        let group_1: string;
        export { group_1 as group };
        export let capability: string;
        export function query_1(): Promise<any>;
        export { query_1 as query };
        export function request_1(): Promise<any>;
        export { request_1 as request };
    }
    namespace alarm {
        let icon_2: string;
        export { icon_2 as icon };
        let group_2: string;
        export { group_2 as group };
        let capability_1: string;
        export { capability_1 as capability };
    }
    namespace background {
        let icon_3: string;
        export { icon_3 as icon };
        let group_3: string;
        export { group_3 as group };
        let capability_2: string;
        export { capability_2 as capability };
    }
    namespace backgroundLocation {
        let icon_4: string;
        export { icon_4 as icon };
        let group_4: string;
        export { group_4 as group };
        let capability_3: string;
        export { capability_3 as capability };
    }
    namespace wifi {
        let icon_5: string;
        export { icon_5 as icon };
        let group_5: string;
        export { group_5 as group };
        let capability_4: string;
        export { capability_4 as capability };
    }
    namespace cell {
        let icon_6: string;
        export { icon_6 as icon };
        let group_6: string;
        export { group_6 as group };
        let capability_5: string;
        export { capability_5 as capability };
    }
    namespace ble {
        let icon_7: string;
        export { icon_7 as icon };
        let group_7: string;
        export { group_7 as group };
        let capability_6: string;
        export { capability_6 as capability };
    }
    namespace advertise {
        let icon_8: string;
        export { icon_8 as icon };
        let group_8: string;
        export { group_8 as group };
        let capability_7: string;
        export { capability_7 as capability };
    }
    namespace usb {
        let icon_9: string;
        export { icon_9 as icon };
        let group_9: string;
        export { group_9 as group };
        let capability_8: string;
        export { capability_8 as capability };
    }
    namespace server {
        let icon_10: string;
        export { icon_10 as icon };
        let group_10: string;
        export { group_10 as group };
        let capability_9: string;
        export { capability_9 as capability };
    }
    namespace lan {
        let icon_11: string;
        export { icon_11 as icon };
        let group_11: string;
        export { group_11 as group };
        let capability_10: string;
        export { capability_10 as capability };
    }
    namespace files {
        let icon_12: string;
        export { icon_12 as icon };
        let group_12: string;
        export { group_12 as group };
        let capability_11: string;
        export { capability_11 as capability };
    }
    namespace motion {
        let icon_13: string;
        export { icon_13 as icon };
        let group_13: string;
        export { group_13 as group };
        export function query_2(): Promise<"prompt" | "granted" | "unsupported">;
        export { query_2 as query };
        export function request_2(): Promise<any>;
        export { request_2 as request };
    }
    namespace camera {
        let icon_14: string;
        export { icon_14 as icon };
        let group_14: string;
        export { group_14 as group };
        export function query_3(): Promise<any>;
        export { query_3 as query };
        export function request_3(): Promise<"prompt" | "granted" | "denied">;
        export { request_3 as request };
    }
    namespace microphone {
        let icon_15: string;
        export { icon_15 as icon };
        let group_15: string;
        export { group_15 as group };
        export function query_4(): Promise<any>;
        export { query_4 as query };
        export function request_4(): Promise<"prompt" | "granted" | "denied">;
        export { request_4 as request };
    }
}
export function heldPermissions(): any;
export function permAndroid(name: any): any;
export function permLabels(loc: any): any;
