/**
 * QR encoder wrapper — the thin, unit-tested surface over the vendored codec, powering the desktop
 * "open on phone" self-QR. Exports `qrMatrix` (a boolean module grid), `qrSvg` and `qrDataUri`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/qrcode.js — edit the JSDoc there, never this file.
/**
 * Encode text into a boolean module matrix (rows × cols, true = a dark module); throws when the text exceeds every QR version.
 * @param text the text to encode, byte mode
 * @param ecc error-correction level "L" | "M" | "Q" | "H" (default "M")
 * @returns the module matrix as boolean[][]
 */
export function qrMatrix(text: any, ecc?: string): any[][];
/**
 * Render the QR for `text` as an SVG string: one path of dark modules over a light field with a quiet zone.
 * @param text the text to encode
 * @param opts `ecc`, `margin` (quiet zone in modules), `dark` and `light` colours
 * @returns the SVG markup
 */
export function qrSvg(text: any, { ecc, margin, dark, light }?: {
    ecc?: string;
    margin?: number;
    dark?: string;
    light?: string;
}): string;
/**
 * The QR SVG as a `data:image/svg+xml` URI, ready for an <img src>.
 * @param text the text to encode
 * @param opts the same options as qrSvg
 * @returns the data URI string
 */
export function qrDataUri(text: any, opts: any): string;
