/**
 * The Preact render catalogue: reads an app's spec and renders it through an allow-listed set of
 * component families — the shell (app bar, dock, toast, sheets), the list family, profile, detail
 * drill-down, filters and the install flow — so an app declares what it is and never draws chrome.
 * Exports the app root ({@link App}), the context binder ({@link setApp}) and two platform probes.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/render.js — edit the JSDoc there, never this file.
/**
 * Binds the app context the catalogue renders from. Called once by the boot before the first render.
 * @param app the app context — { spec, S (atoms), load, toast, toggleFav, favKey, swap, … }
 * @param views tool-app custom views keyed by `tab.view`, or nothing for declarative apps
 */
export function setApp(app: any, views: any): void;
/**
 * The app root: the chrome (app bar, dock, dock fade, toast), the current tab's view and every systemic
 * overlay (detail, permissions, sign-in, APK, QR, install) driven by the routing atoms in the app context.
 * @returns the Preact tree the boot mounts into `#app`
 */
export function App(): any;
export function isIOS(): boolean;
export function isStandalone(): any;
