/**
 * # tests/runtime — the runtime's unit-test barrel, runnable by a consumer
 *
 * One file per module under `packages/runtime/tests/`, imported here so Deno registers every suite the
 * moment the barrel loads. Exported so a consumer tree runs the SAME suites against the pinned core with a
 * one-line local test file (`deno test` refuses a remote URL as a test module — silently, when a local file
 * rides along): the 8n8 node `unit` in a consumer points at `.microspec/tests/unit_test.js`, which is
 * `import "@microspec/core/tests/runtime";`. It exports nothing.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/runtime_test.js — edit the JSDoc there, never this file.
export {};
