/**
 * Vendored satellite.js v5.0.0 (MIT) — the canonical SGP4/SDP4 propagator, self-contained and kept
 * same-origin so the SW caches it for offline. Exports the satellite.js API as-is (`twoline2satrec`,
 * `propagate`, `sgp4`, `gstime`, the ECI/ECF/geodetic conversions, `constants`); the runtime reaches it
 * through ./orbit.js.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/satellite.js — edit the JSDoc there, never this file.
declare var f1: Readonly<{
    __proto__: any;
    deg2rad: number;
    earthRadius: number;
    j2: number;
    j3: number;
    j3oj2: number;
    j4: number;
    minutesPerDay: number;
    mu: number;
    pi: number;
    rad2deg: number;
    tumin: number;
    twoPi: number;
    vkmpersec: number;
    x2o3: number;
    xke: number;
}>;
declare function y1(a: any): number;
declare function u1(a: any): number;
declare function W2(a: any): number;
declare function e1(a: any, v: any, r: any): number;
declare function t1(a: any, v: any): {
    x: number;
    y: number;
    z: any;
};
declare function T1(a: any, v: any): {
    azimuth: number;
    elevation: number;
    rangeSat: number;
};
declare function j1(a: any, v: any): {
    x: number;
    y: number;
    z: any;
};
declare function w1(a: any, v: any): {
    longitude: number;
    latitude: number;
    height: number;
};
declare function x1(a: any): {
    x: number;
    y: number;
    z: number;
};
declare function a1(...args: any[]): any;
declare function z1(a: any, v: any): number[] | Date;
declare function F2(a: any, v: any, r: any, h: any, d: any, o: any, x: any): any;
declare function M1(...args: any[]): boolean[] | {
    position: boolean;
    velocity: boolean;
} | {
    position: {
        x: number;
        y: number;
        z: number;
    };
    velocity: {
        x: number;
        y: number;
        z: number;
    };
};
declare function b1(a: any): number;
declare function q1(a: any): number;
declare function V2(a: any): number;
declare function Y2(a: any, v: any): boolean[] | {
    position: boolean;
    velocity: boolean;
} | {
    position: {
        x: number;
        y: number;
        z: number;
    };
    velocity: {
        x: number;
        y: number;
        z: number;
    };
};
declare function p1(a: any, v: any): {
    error: number;
    satnum: any;
    epochyr: number;
    epochdays: number;
    ndot: number;
    nddot: number;
    bstar: number;
    inclo: number;
    nodeo: number;
    ecco: number;
    argpo: number;
    mo: number;
    no: number;
    jdsatepoch: any;
};
export { f1 as constants, y1 as degreesLat, u1 as degreesLong, W2 as degreesToRadians, e1 as dopplerFactor, t1 as ecfToEci, T1 as ecfToLookAngles, j1 as eciToEcf, w1 as eciToGeodetic, x1 as geodeticToEcf, a1 as gstime, z1 as invjday, F2 as jday, M1 as propagate, b1 as radiansLat, q1 as radiansLong, V2 as radiansToDegrees, Y2 as sgp4, p1 as twoline2satrec };
