/**
 * The sealed-tunnel interceptor: wraps `fetch` so every request to our proxy travels as one sealed
 * envelope to POST /feed/f and comes back as an ordinary Response — no call site changes shape, and
 * turning the tunnel off is deleting one import. Exports `installSealedFetch`, plus `sealedFrameUrl` /
 * `sealedClipUrl` for the element-loaded URLs a fetch wrapper can never see.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sealedfetch.js — edit the JSDoc there, never this file.
/**
 * Build the /feed/frame GET URL an element can load, with the destination sealed into `?s=`.
 * @param url the target page or media URL
 * @param ref optional referer the proxy should present
 * @returns the proxy URL string
 */
export function sealedFrameUrl(url: any, ref: any): Promise<string>;
/**
 * Build the /feed/clip GET URL for the clip exporter, with the destination sealed into `?s=`.
 * @param url the source video URL
 * @param page optional page URL the video came from
 * @param format "gif" (default) or "mp4"
 * @returns the proxy URL string
 */
export function sealedClipUrl(url: any, page: any, format: any): Promise<string>;
/**
 * Replace globalThis.fetch with the sealing wrapper; anything off VPS_PROXY and the PLAIN routes pass through untouched.
 * @param realFetch the underlying fetch to wrap (default: the global one)
 * @returns an uninstall function that restores `realFetch`
 */
export function installSealedFetch(realFetch?: any): () => void;
