/**
 * Hardware capability layer — one uniform shape per capability (`supported` plus methods that no-op when
 * unavailable) so views can feature-detect and degrade. Exports `haptic` / `hapticFor`, `geo`, `wakeLock`,
 * `compass` with its pure heading projections (`lookHeadingDeg`, `screenHeadingDeg`, `heldHeadingDeg`),
 * `tilt`, `camera`, and `mic` / `MIC_MIMES`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sensors.js — edit the JSDoc there, never this file.
/**
 * Which haptic a tap on this element deserves, honouring data-haptic and the disabled state.
 * @param el the tapped element (the event target)
 * @returns "tick" | "bump" | the element's own data-haptic value, or null for none
 */
export function hapticFor(el: any): any;
/**
 * Heading of the device −z axis (what the rear camera points at), degrees clockwise from north.
 * @param alpha device orientation alpha, degrees
 * @param beta device orientation beta, degrees
 * @param gamma device orientation gamma, degrees
 * @returns heading in [0, 360), or null within ~9° of straight up or down
 */
export function lookHeadingDeg(alpha: any, beta: any, gamma: any): number;
/**
 * Heading of the top edge of the screen, degrees clockwise from north, taken from the spec's rotation matrix.
 * @param alpha device orientation alpha, degrees
 * @param beta device orientation beta, degrees
 * @returns heading in [0, 360), or null within ~9° of upright
 */
export function screenHeadingDeg(alpha: any, beta: any): number;
/**
 * The heading a hand-held compass should show at any pitch: screen-top while flat, camera axis while upright, crossfaded between.
 * @param alpha device orientation alpha, degrees
 * @param beta device orientation beta, degrees
 * @param gamma device orientation gamma, degrees
 * @param screenAngle screen.orientation.angle, applied to the screen-top term only
 * @returns heading in [0, 360); never null while β/γ are numbers
 */
export function heldHeadingDeg(alpha: any, beta: any, gamma: any, screenAngle?: number): number;
/** Short vibration feedback — `buzz(pattern)`, `tick`, `bump`, `ok`; a silent no-op where unsupported. */
export const haptic: {
    buzz(pattern: any): void;
    tick(): void;
    bump(): void;
    ok(): void;
};
/** Geolocation as a callback `watch` or a single promised fix via `once`; errors arrive as "denied" | "unavailable" | "unsupported". */
export const geo: {};
/** Screen wake lock — `acquire()` returns a handle that re-acquires on visibilitychange until `release()`. */
export const wakeLock: {
    supported: boolean;
    acquire(): {
        release: () => void;
        supported: boolean;
    };
};
/** Compass heading in degrees clockwise from TRUE north — `request()` for the gesture-gated permission, `start(onHeading, opts)` → stop fn. */
export const compass: {
    supported: boolean;
    needsPermission: boolean;
    request(): Promise<boolean>;
    start(onHeading: any, { trueNorth, look }?: {
        trueNorth?: boolean;
        look?: boolean;
    }): () => void;
};
/** Raw device pitch/roll (β/γ, degrees) for parallax — `request()` shares the compass permission, `start(onTilt)` → stop fn. */
export const tilt: {
    supported: boolean;
    needsPermission: boolean;
    request(): Promise<boolean>;
    start(onTilt: any): () => void;
};
/** A live camera stream on a <video> — `start(videoEl, onErr, opts)` → stop fn that releases every track. */
export const camera: {
    supported: boolean;
    start(video: any, onErr: any, { facingMode }?: {
        facingMode?: string;
    }): Promise<() => void>;
};
/** Recorder MIME types to try, in preference order. */
export const MIC_MIMES: string[];
/** A short microphone take — `mime()` picks a supported type, `record(opts)` → { done, stop, cancel }. */
export const mic: {
    supported: boolean;
    mime(): string;
    /**
         * Record one take from the microphone.
         * @param {object} [opts]
         * @param [opts.seconds] take length (default 2)
         * @param [opts.timeoutMs] give up waiting for the stream after this long (default 10000)
         * @param [opts.bitsPerSecond] encoder bitrate (default 128000)
         * @param [opts.onStream] called with the live MediaStream once it is granted
         * @param [opts.onErr] called with a short reason string ("denied", "unavailable", "unsupported", "error")
         * @returns `{ done, stop, cancel }` — `done` resolves to `{ blob, mime, settings }` or null
         */
    record({ seconds, timeoutMs, bitsPerSecond, onStream, onErr }?: {
        seconds?: any;
        timeoutMs?: any;
        bitsPerSecond?: any;
        onStream?: any;
        onErr?: any;
    }): {
        done: Promise<any>;
        stop(): void;
        cancel(): void;
    };
};
/**
 * Hardware capability layer — one uniform shape per capability (`supported` plus methods that no-op when
 * unavailable) so views can feature-detect and degrade. Exports `haptic` / `hapticFor`, `geo`, `wakeLock`,
 * `compass` with its pure heading projections (`lookHeadingDeg`, `screenHeadingDeg`, `heldHeadingDeg`),
 * `tilt`, `camera`, and `mic` / `MIC_MIMES`.
 * @module
 */
declare const canVibrate: boolean;
export {};
