/**
 * Hardware capability layer — one uniform shape per capability (`supported` plus methods that no-op when
 * unavailable) so views can feature-detect and degrade. Exports `haptic` / `hapticFor`, `geo`, `wakeLock`,
 * `compass` with its pure heading projections (`lookHeadingDeg`, `screenHeadingDeg`, `heldHeadingDeg`),
 * `tilt`, `camera`, and `mic` / `MIC_MIMES`.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sensors.js — edit the JSDoc there, never this file.
/**
 * Which haptic a tap on this element deserves, honouring data-haptic and the disabled state.
 * @param el the tapped element (the event target)
 * @returns "tick" | "bump" | the element's own data-haptic value, or null for none
 */
export function hapticFor(el: any): any;
/**
 * Heading of the device −z axis (what the rear camera points at), degrees clockwise from north.
 * @param alpha device orientation alpha, degrees
 * @param beta device orientation beta, degrees
 * @param gamma device orientation gamma, degrees
 * @returns heading in [0, 360), or null within ~9° of straight up or down
 */
export function lookHeadingDeg(alpha: any, beta: any, gamma: any): number;
/**
 * Heading of the top edge of the screen, degrees clockwise from north, taken from the spec's rotation matrix.
 * @param alpha device orientation alpha, degrees
 * @param beta device orientation beta, degrees
 * @returns heading in [0, 360), or null within ~9° of upright
 */
export function screenHeadingDeg(alpha: any, beta: any): number;
/**
 * The heading a hand-held compass should show at any pitch: screen-top while flat, camera axis while upright, crossfaded between.
 * @param alpha device orientation alpha, degrees
 * @param beta device orientation beta, degrees
 * @param gamma device orientation gamma, degrees
 * @param screenAngle screen.orientation.angle, applied to the screen-top term only
 * @returns heading in [0, 360); never null while β/γ are numbers
 */
export function heldHeadingDeg(alpha: any, beta: any, gamma: any, screenAngle?: number): number;
export namespace haptic {
    export { canVibrate as supported };
    export function buzz(pattern: any): void;
    export function tick(): void;
    export function bump(): void;
    export function ok(): void;
}
export namespace geo {
    let supported: boolean;
    function watch(onPos: any, onErr: any, opts: any): () => void;
    function once(opts: any): Promise<any>;
}
export namespace wakeLock {
    let supported_1: boolean;
    export { supported_1 as supported };
    export function acquire(): {
        release: () => void;
        supported: boolean;
    };
}
export namespace compass {
    let supported_2: boolean;
    export { supported_2 as supported };
    export let needsPermission: boolean;
    export function request(): Promise<boolean>;
    export function start(onHeading: any, { trueNorth, look }?: {
        trueNorth?: boolean;
        look?: boolean;
    }): () => void;
}
export namespace tilt {
    let supported_3: boolean;
    export { supported_3 as supported };
    let needsPermission_1: boolean;
    export { needsPermission_1 as needsPermission };
    export function request(): Promise<boolean>;
    export function start(onTilt: any): () => void;
}
export namespace camera {
    let supported_4: boolean;
    export { supported_4 as supported };
    export function start(video: any, onErr: any, { facingMode }?: {
        facingMode?: string;
    }): Promise<() => void>;
}
/** Recorder MIME types to try, in preference order. */
export const MIC_MIMES: string[];
export namespace mic {
    let supported_5: boolean;
    export { supported_5 as supported };
    export function mime(): string;
    /**
     * Record one take from the microphone.
     * @param {object} [opts]
     * @param [opts.seconds] take length (default 2)
     * @param [opts.timeoutMs] give up waiting for the stream after this long (default 10000)
     * @param [opts.bitsPerSecond] encoder bitrate (default 128000)
     * @param [opts.onStream] called with the live MediaStream once it is granted
     * @param [opts.onErr] called with a short reason string ("denied", "unavailable", "unsupported", "error")
     * @returns `{ done, stop, cancel }` — `done` resolves to `{ blob, mime, settings }` or null
     */
    export function record({ seconds, timeoutMs, bitsPerSecond, onStream, onErr }?: {
        seconds?: any;
        timeoutMs?: any;
        bitsPerSecond?: any;
        onStream?: any;
        onErr?: any;
    }): {
        done: Promise<any>;
        stop(): void;
        cancel(): void;
    };
}
/**
 * Hardware capability layer — one uniform shape per capability (`supported` plus methods that no-op when
 * unavailable) so views can feature-detect and degrade. Exports `haptic` / `hapticFor`, `geo`, `wakeLock`,
 * `compass` with its pure heading projections (`lookHeadingDeg`, `screenHeadingDeg`, `heldHeadingDeg`),
 * `tilt`, `camera`, and `mic` / `MIC_MIMES`.
 * @module
 */
declare const canVibrate: boolean;
export {};
