/**
 * # runtime/share.js — what another app shared with this one
 *
 * An app with `share: true` in its spec is listed in the OS share sheet; the manifest's share target lands
 * the share on `./?sh_title=…&sh_text=…&sh_url=…` (the APK shell delivers it as a `share.incoming` event
 * instead). This is the one place that reads it: once, before the view mounts, with the parameters stripped
 * from the address bar so a reload or a bookmark does not share it again.
 *
 * ## Import
 * ```js
 * import { takeShared, firstLink } from "/_rt/share.js";
 * ```
 *
 * ## What it exports
 * - {@link takeShared} — `takeShared(fn)`: `fn({ title, text, url, files })` for the share that opened the page (if
 *   any), and for every share the APK shell hands in later. Returns nothing; safe to call at module load.
 * - {@link firstLink} — `firstLink({ title, text, url })` → the first http(s) address in the three fields, or `""`.
 * - {@link takeFiles} — `takeFiles(caches, scope, n)` → the File[] a file share parked; exported for the unit test.
 *
 * ## In practice
 * ```js
 * takeShared((s) => { const link = firstLink(s); if (link) { $link.set(link); find(link); } });
 * ```
 *
 * ## Invariants and pitfalls
 * - The parameters are taken from `location` at import time and removed with `replaceState`; a share is
 *   delivered to every `takeShared` caller registered before or after — it is held until the first one.
 * - A share that carries no link is still delivered: the app decides what text means to it.
 * - FILES (`spec.share.files`): the worker parks them in the `ms-share` cache under the scope and lands the page on
 *   `./?sh_files=<n>`; they are collected here, delivered as `files: [File]`, and the cache entries are deleted —
 *   a share is read once. The APK shell still hands in text only.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/share.js — edit the JSDoc there, never this file.
/**
 * Collect the files a file share parked in the share cache: `${scope}share-target/<i>` for i < n.
 * @param cacheStorage the CacheStorage to read (`caches`)
 * @param scope the app scope href the worker keyed them under
 * @param n how many the worker parked
 * @returns File[] in share order; entries that are missing are skipped, the rest are deleted after reading
 */
export function takeFiles(cacheStorage: any, scope: any, n: any): Promise<any[]>;
/**
 * The first http(s) link inside a share's fields.
 * @param s `{ title, text, url }`
 * @returns the address, trailing punctuation dropped, or `""`
 */
export function firstLink(s: any): string;
/**
 * Registers the app's handler for shares — the one that opened the page and any the APK shell brings later.
 * @param fn called with `{ title, text, url }`
 */
export function takeShared(fn: any): void;
