/* @ts-self-types="./shell-actions.d.ts" */
/**
 * # runtime/shell-actions.js — the Android action catalogue as code
 *
 * Generated from packages/shell/actions.json by tools/shell-gen.mjs so shell.js can negotiate with
 * whatever APK bridge it runs in: every action id with its capability, kind, the bridge version it needs,
 * the Android permissions it costs, and the mock the gate answers with (CI runs Chromium, never the APK).
 * Both sides of the bridge are generated from the one catalogue, so they cannot drift; a doc written into
 * this file by hand is deleted by the next regeneration.
 *
 * ![The module's map: no runtime imports, two exports, read by shell.js](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-shell-actions.svg)
 *
 * ## Import
 * ```js
 * import { ACTIONS, CATALOGUE_BRIDGE } from "/_rt/shell-actions.js";                   // an app's page
 * import { ACTIONS } from "@microspec/core/runtime/shell-actions.js";                  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link CATALOGUE_BRIDGE} — the bridge version this catalogue was generated for (what the PAGE was built against).
 * - {@link ACTIONS} — id → `{ capability, kind, minBridge, android, mock }` for all 54 actions (bridge 34).
 *
 * ## How it fits
 * Imported by runtime/shell.js, which compares CATALOGUE_BRIDGE with the bridge the APK reports and refuses
 * an action whose minBridge is ahead of it; the mock is what the verify gate receives for every action.
 * Regenerate with `deno task shell` after editing the catalogue — the 8n8 node `shell` reds a stale table.
 * @module
 */
// GENERATED by tools/shell-gen.mjs from packages/shell/actions.json — do not edit.
// Run `deno task shell` after changing the catalogue; `--check` gates it before every push.
/** The bridge version this catalogue was generated for — what the PAGE was built against. */
export const CATALOGUE_BRIDGE = 34;
/** Every shell action by id: { capability, kind ("call"|"subscribe"), minBridge, android permissions, mock }. */
export const ACTIONS = {
  "system.info": {
    "capability": "system",
    "kind": "call",
    "minBridge": 1,
    "android": [],
    "mock": {
      "bridge": 1,
      "sdk": 36,
      "release": "16",
      "model": "Gate Device",
      "pkg": "apk.microspec.a0000000000000000",
      "caps": "alarm,background,location,notify,system",
      "version": "1.0",
      "build": 1,
      "installed": 1893479400000,
      "perms": {
        "POST_NOTIFICATIONS": true,
        "RECEIVE_BOOT_COMPLETED": true,
        "FOREGROUND_SERVICE": true,
        "ACCESS_FINE_LOCATION": true,
        "ACCESS_BACKGROUND_LOCATION": false,
        "ACCESS_WIFI_STATE": true,
        "READ_PHONE_STATE": true,
        "BLUETOOTH": true,
        "BLUETOOTH_ADMIN": true,
        "BLUETOOTH_SCAN": false,
        "REQUEST_INSTALL_PACKAGES": true
      },
      "locationOn": true
    }
  },
  "notify.show": {
    "capability": "notify",
    "kind": "call",
    "minBridge": 1,
    "android": [
      "POST_NOTIFICATIONS"
    ],
    "mock": {
      "id": "gate-note"
    }
  },
  "notify.cancel": {
    "capability": "notify",
    "kind": "call",
    "minBridge": 1,
    "android": [
      "POST_NOTIFICATIONS"
    ],
    "mock": {
      "ok": true
    }
  },
  "alarm.set": {
    "capability": "alarm",
    "kind": "call",
    "minBridge": 1,
    "android": [
      "RECEIVE_BOOT_COMPLETED"
    ],
    "mock": {
      "id": "gate-alarm",
      "at": 1893479400000,
      "exact": true
    }
  },
  "alarm.cancel": {
    "capability": "alarm",
    "kind": "call",
    "minBridge": 1,
    "android": [
      "RECEIVE_BOOT_COMPLETED"
    ],
    "mock": {
      "ok": true
    }
  },
  "alarm.list": {
    "capability": "alarm",
    "kind": "call",
    "minBridge": 1,
    "android": [
      "RECEIVE_BOOT_COMPLETED"
    ],
    "mock": {
      "alarms": [
        {
          "id": "gate-alarm",
          "at": 1893479400000,
          "title": "Gate alarm"
        }
      ]
    }
  },
  "system.update": {
    "capability": "system",
    "kind": "call",
    "minBridge": 2,
    "android": [
      "REQUEST_INSTALL_PACKAGES"
    ],
    "mock": {
      "started": true
    }
  },
  "bg.start": {
    "capability": "background",
    "kind": "call",
    "minBridge": 3,
    "android": [
      "FOREGROUND_SERVICE",
      "POST_NOTIFICATIONS"
    ],
    "mock": {
      "running": true
    }
  },
  "bg.stop": {
    "capability": "background",
    "kind": "call",
    "minBridge": 3,
    "android": [
      "FOREGROUND_SERVICE"
    ],
    "mock": {
      "running": false
    }
  },
  "bg.status": {
    "capability": "background",
    "kind": "call",
    "minBridge": 3,
    "android": [],
    "mock": {
      "running": true,
      "since": 1893479400000,
      "fixes": 12
    }
  },
  "location.watch": {
    "capability": "location",
    "kind": "subscribe",
    "minBridge": 3,
    "android": [
      "ACCESS_FINE_LOCATION",
      "ACCESS_BACKGROUND_LOCATION"
    ],
    "mock": {
      "lat": 50.4501,
      "lon": 30.5234,
      "acc": 12.5,
      "at": 1893479400000
    }
  },
  "wifi.scan": {
    "capability": "wifi",
    "kind": "call",
    "minBridge": 4,
    "android": [
      "ACCESS_WIFI_STATE",
      "ACCESS_FINE_LOCATION"
    ],
    "mock": {
      "networks": [
        {
          "ssid": "Gate-AP",
          "bssid": "02:00:00:00:00:01",
          "rssi": -47,
          "freq": 5180,
          "caps": "[WPA2-PSK-CCMP][ESS]"
        },
        {
          "ssid": "Gate-Guest",
          "bssid": "02:00:00:00:00:02",
          "rssi": -71,
          "freq": 2437,
          "caps": "[ESS]"
        }
      ],
      "throttled": false
    }
  },
  "wifi.info": {
    "capability": "wifi",
    "kind": "call",
    "minBridge": 4,
    "android": [
      "ACCESS_WIFI_STATE",
      "ACCESS_FINE_LOCATION"
    ],
    "mock": {
      "connected": true,
      "ssid": "Gate-AP",
      "bssid": "02:00:00:00:00:01",
      "rssi": -47,
      "freq": 5180,
      "ip": "192.168.1.42"
    }
  },
  "cell.info": {
    "capability": "cell",
    "kind": "call",
    "minBridge": 4,
    "android": [
      "READ_PHONE_STATE",
      "ACCESS_FINE_LOCATION"
    ],
    "mock": {
      "cells": [
        {
          "type": "lte",
          "mcc": 255,
          "mnc": 1,
          "lac": 4102,
          "cid": 27183,
          "pci": 301,
          "arfcn": 1300,
          "rssi": -89,
          "serving": true
        },
        {
          "type": "lte",
          "mcc": 255,
          "mnc": 1,
          "pci": 118,
          "arfcn": 1300,
          "rssi": -104,
          "serving": false
        }
      ]
    }
  },
  "system.grant": {
    "capability": "system",
    "kind": "call",
    "minBridge": 5,
    "android": [],
    "mock": {
      "state": "granted"
    }
  },
  "ble.state": {
    "capability": "ble",
    "kind": "call",
    "minBridge": 6,
    "android": [
      "BLUETOOTH_CONNECT"
    ],
    "mock": {
      "supported": true,
      "on": true,
      "advertising": false,
      "extAdv": true,
      "maxAdvLen": 1650,
      "multiAdv": true
    }
  },
  "ble.scan": {
    "capability": "ble",
    "kind": "subscribe",
    "minBridge": 6,
    "android": [
      "BLUETOOTH_SCAN",
      "BLUETOOTH_CONNECT",
      "ACCESS_FINE_LOCATION"
    ],
    "mock": {
      "addr": "02:00:00:00:AA:01",
      "name": "Gate Beacon",
      "rssi": -62,
      "at": 1893479400000,
      "raw": "0201060303b2fc0716b2fc41424344",
      "tx": -8,
      "tns": 41000000000,
      "dstat": 0,
      "legacy": true,
      "conn": true
    }
  },
  "ble.advertise": {
    "capability": "advertise",
    "kind": "call",
    "minBridge": 26,
    "android": [
      "BLUETOOTH_ADVERTISE"
    ],
    "mock": {
      "advertising": true,
      "bytes": 22,
      "replaced": false
    }
  },
  "ble.silence": {
    "capability": "advertise",
    "kind": "call",
    "minBridge": 26,
    "android": [
      "BLUETOOTH_ADVERTISE"
    ],
    "mock": {
      "advertising": false
    }
  },
  "ble.advertiseRaw": {
    "capability": "advertise-raw",
    "kind": "call",
    "minBridge": 27,
    "android": [
      "BLUETOOTH_ADVERTISE"
    ],
    "mock": {
      "advertising": true,
      "bytes": 20,
      "replaced": false
    }
  },
  "usb.list": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 6,
    "android": [],
    "mock": {
      "devices": [
        {
          "vid": 7504,
          "pid": 24596,
          "name": "HackRF One",
          "cls": 255
        }
      ]
    }
  },
  "usb.open": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 30,
    "android": [],
    "mock": {
      "opened": true,
      "vid": 2821,
      "pid": 6551,
      "name": "802.11ac WLAN Adapter"
    }
  },
  "usb.control": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 30,
    "android": [],
    "mock": {
      "len": 4,
      "data": "3725490c"
    }
  },
  "usb.switch": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 30,
    "android": [],
    "mock": {
      "switched": true
    }
  },
  "usb.bulk": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 30,
    "android": [],
    "mock": {
      "len": 0,
      "data": ""
    }
  },
  "usb.batch": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 31,
    "android": [],
    "mock": {
      "count": 0,
      "fail": 0,
      "reads": []
    }
  },
  "rf.attach": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 32,
    "android": [],
    "mock": {
      "attached": true,
      "channel": 6
    }
  },
  "rf.detach": {
    "capability": "usb",
    "kind": "call",
    "minBridge": 32,
    "android": [],
    "mock": {
      "detached": true
    }
  },
  "system.logs": {
    "capability": "system",
    "kind": "call",
    "minBridge": 16,
    "android": [],
    "mock": {
      "lines": [
        "0.4s subscribe id=1 action=ble.scan",
        "0.4s ack sent id=1",
        "0.5s withPermissions ble.scan need=3",
        "0.6s permissions granted=true",
        "0.6s startStream ble.scan live=true caps=alarm,background,ble",
        "0.7s scan started"
      ]
    }
  },
  "server.start": {
    "capability": "server",
    "kind": "call",
    "minBridge": 19,
    "android": [
      "ACCESS_WIFI_STATE"
    ],
    "mock": {
      "running": true,
      "port": 8080,
      "url": "http://192.168.1.42:8080/",
      "hits": 0,
      "routes": 1
    }
  },
  "server.put": {
    "capability": "server",
    "kind": "call",
    "minBridge": 19,
    "android": [],
    "mock": {
      "path": "/",
      "bytes": 128
    }
  },
  "server.stop": {
    "capability": "server",
    "kind": "call",
    "minBridge": 19,
    "android": [],
    "mock": {
      "running": false
    }
  },
  "server.status": {
    "capability": "server",
    "kind": "call",
    "minBridge": 19,
    "android": [
      "ACCESS_WIFI_STATE"
    ],
    "mock": {
      "running": true,
      "port": 8080,
      "url": "http://192.168.1.42:8080/",
      "hits": 3,
      "routes": 1
    }
  },
  "files.grant": {
    "capability": "files",
    "kind": "call",
    "minBridge": 20,
    "android": [],
    "mock": {
      "granted": true,
      "uri": "content://gate/tree/Documents",
      "name": "Documents"
    }
  },
  "files.roots": {
    "capability": "files",
    "kind": "call",
    "minBridge": 20,
    "android": [],
    "mock": {
      "roots": [
        {
          "uri": "content://gate/tree/Documents",
          "name": "Documents"
        }
      ]
    }
  },
  "files.list": {
    "capability": "files",
    "kind": "call",
    "minBridge": 20,
    "android": [],
    "mock": {
      "uri": "content://gate/tree/Documents",
      "docId": "Documents",
      "entries": [
        {
          "docId": "Documents/notes",
          "name": "notes",
          "mime": "vnd.android.document/directory",
          "dir": true,
          "size": 0,
          "at": 1893479400000
        },
        {
          "docId": "Documents/readme.txt",
          "name": "readme.txt",
          "mime": "text/plain",
          "dir": false,
          "size": 128,
          "at": 1893479400000
        }
      ]
    }
  },
  "files.read": {
    "capability": "files",
    "kind": "call",
    "minBridge": 20,
    "android": [],
    "mock": {
      "docId": "Documents/readme.txt",
      "bytes": 11,
      "base64": "Z2F0ZSBzYW1wbGU="
    }
  },
  "files.write": {
    "capability": "files",
    "kind": "call",
    "minBridge": 20,
    "android": [],
    "mock": {
      "docId": "Documents/note.txt",
      "bytes": 11
    }
  },
  "system.settings": {
    "capability": "system",
    "kind": "call",
    "minBridge": 21,
    "android": [],
    "mock": {
      "opened": true,
      "page": "app"
    }
  },
  "system.battery": {
    "capability": "system",
    "kind": "call",
    "minBridge": 21,
    "android": [],
    "mock": {
      "level": 72,
      "charging": false,
      "saver": false,
      "unrestricted": true,
      "temp": 298
    }
  },
  "files.share": {
    "capability": "files",
    "kind": "call",
    "minBridge": 21,
    "android": [],
    "mock": {
      "shared": true,
      "uri": "content://gate/downloads/1",
      "bytes": 11
    }
  },
  "lan.scan": {
    "capability": "lan",
    "kind": "subscribe",
    "minBridge": 22,
    "android": [
      "ACCESS_WIFI_STATE",
      "CHANGE_WIFI_MULTICAST_STATE"
    ],
    "mock": {
      "ip": "192.168.1.1",
      "name": "router.lan",
      "ports": "80,443",
      "via": "tcp",
      "at": 1893479400000
    }
  },
  "lan.ports": {
    "capability": "lan",
    "kind": "subscribe",
    "minBridge": 25,
    "android": [],
    "mock": {
      "port": 8080,
      "family": "4",
      "probe": "http",
      "hex": "485454502f312e3120323030204f4b0d0a5365727665723a206d6963726f737065632d73746174696f6e2f310d0a436f6e74656e742d547970653a20746578742f68746d6c0d0a0d0a3c7469746c653e6d6963726f73706563204f533c2f7469746c653e",
      "tls": "",
      "cert": "",
      "proto": "",
      "ms": 3,
      "at": 1893479400000
    }
  },
  "media.show": {
    "capability": "media",
    "kind": "call",
    "minBridge": 28,
    "android": [
      "FOREGROUND_SERVICE",
      "POST_NOTIFICATIONS"
    ],
    "mock": {
      "ok": true
    }
  },
  "media.hide": {
    "capability": "media",
    "kind": "call",
    "minBridge": 28,
    "android": [
      "FOREGROUND_SERVICE"
    ],
    "mock": {
      "ok": true
    }
  },
  "media.command": {
    "capability": "media",
    "kind": "subscribe",
    "minBridge": 28,
    "android": [],
    "mock": {
      "ack": true
    }
  },
  "share.target": {
    "capability": "share",
    "kind": "call",
    "minBridge": 29,
    "android": [],
    "mock": {
      "kinds": [
        "audio"
      ]
    }
  },
  "share.incoming": {
    "capability": "share",
    "kind": "subscribe",
    "minBridge": 29,
    "android": [],
    "mock": {
      "ack": true
    }
  },
  "godot.start": {
    "capability": "godot",
    "kind": "call",
    "minBridge": 34,
    "android": [
      "CAMERA"
    ],
    "mock": {
      "state": "running",
      "engine": "4.7.2.stable",
      "cached": true
    }
  },
  "godot.stop": {
    "capability": "godot",
    "kind": "call",
    "minBridge": 34,
    "android": [],
    "mock": {
      "state": "stopped"
    }
  },
  "godot.set": {
    "capability": "godot",
    "kind": "call",
    "minBridge": 34,
    "android": [],
    "mock": {
      "ok": true
    }
  },
  "godot.input": {
    "capability": "godot",
    "kind": "call",
    "minBridge": 34,
    "android": [],
    "mock": {
      "ok": true
    }
  },
  "godot.save": {
    "capability": "godot",
    "kind": "call",
    "minBridge": 34,
    "android": [],
    "mock": {
      "name": "portal-1.png",
      "bytes": 245760
    }
  },
  "godot.state": {
    "capability": "godot",
    "kind": "subscribe",
    "minBridge": 34,
    "android": [],
    "mock": {
      "ack": true
    }
  }
};
