/**
 * The shell action catalogue as code — generated from packages/shell/actions.json so shell.js can negotiate
 * with whatever APK bridge it runs in. Exports CATALOGUE_BRIDGE (the bridge version the page was built
 * against) and ACTIONS (every action id with its capability, kind, minBridge, Android permissions and the
 * mock the gate answers with, since CI runs Chromium and never the APK).
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/shell-actions.js — edit the JSDoc there, never this file.
/**
 * The shell action catalogue as code — generated from packages/shell/actions.json so shell.js can negotiate
 * with whatever APK bridge it runs in. Exports CATALOGUE_BRIDGE (the bridge version the page was built
 * against) and ACTIONS (every action id with its capability, kind, minBridge, Android permissions and the
 * mock the gate answers with, since CI runs Chromium and never the APK).
 * @module
 */
/** The bridge version this catalogue was generated for — what the PAGE was built against. */
export const CATALOGUE_BRIDGE: 33;
/** Every shell action by id: { capability, kind ("call"|"subscribe"), minBridge, android permissions, mock }. */
export const ACTIONS: {
    "system.info": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            bridge: number;
            sdk: number;
            release: string;
            model: string;
            pkg: string;
            caps: string;
            version: string;
            build: number;
            installed: number;
            perms: {
                POST_NOTIFICATIONS: boolean;
                RECEIVE_BOOT_COMPLETED: boolean;
                FOREGROUND_SERVICE: boolean;
                ACCESS_FINE_LOCATION: boolean;
                ACCESS_BACKGROUND_LOCATION: boolean;
                ACCESS_WIFI_STATE: boolean;
                READ_PHONE_STATE: boolean;
                BLUETOOTH: boolean;
                BLUETOOTH_ADMIN: boolean;
                BLUETOOTH_SCAN: boolean;
                REQUEST_INSTALL_PACKAGES: boolean;
            };
            locationOn: boolean;
        };
    };
    "notify.show": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            id: string;
        };
    };
    "notify.cancel": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            ok: boolean;
        };
    };
    "alarm.set": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            id: string;
            at: number;
            exact: boolean;
        };
    };
    "alarm.cancel": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            ok: boolean;
        };
    };
    "alarm.list": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            alarms: {
                id: string;
                at: number;
                title: string;
            }[];
        };
    };
    "system.update": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            started: boolean;
        };
    };
    "bg.start": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            running: boolean;
        };
    };
    "bg.stop": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            running: boolean;
        };
    };
    "bg.status": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            running: boolean;
            since: number;
            fixes: number;
        };
    };
    "location.watch": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            lat: number;
            lon: number;
            acc: number;
            at: number;
        };
    };
    "wifi.scan": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            networks: {
                ssid: string;
                bssid: string;
                rssi: number;
                freq: number;
                caps: string;
            }[];
            throttled: boolean;
        };
    };
    "wifi.info": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            connected: boolean;
            ssid: string;
            bssid: string;
            rssi: number;
            freq: number;
            ip: string;
        };
    };
    "cell.info": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            cells: ({
                type: string;
                mcc: number;
                mnc: number;
                lac: number;
                cid: number;
                pci: number;
                arfcn: number;
                rssi: number;
                serving: boolean;
            } | {
                type: string;
                mcc: number;
                mnc: number;
                pci: number;
                arfcn: number;
                rssi: number;
                serving: boolean;
                lac?: undefined;
                cid?: undefined;
            })[];
        };
    };
    "system.grant": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            state: string;
        };
    };
    "ble.state": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            supported: boolean;
            on: boolean;
            advertising: boolean;
            extAdv: boolean;
            maxAdvLen: number;
            multiAdv: boolean;
        };
    };
    "ble.scan": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            addr: string;
            name: string;
            rssi: number;
            at: number;
            raw: string;
            tx: number;
            tns: number;
            dstat: number;
            legacy: boolean;
            conn: boolean;
        };
    };
    "ble.advertise": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            advertising: boolean;
            bytes: number;
            replaced: boolean;
        };
    };
    "ble.silence": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            advertising: boolean;
        };
    };
    "ble.advertiseRaw": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            advertising: boolean;
            bytes: number;
            replaced: boolean;
        };
    };
    "usb.list": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            devices: {
                vid: number;
                pid: number;
                name: string;
                cls: number;
            }[];
        };
    };
    "usb.open": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            opened: boolean;
            vid: number;
            pid: number;
            name: string;
        };
    };
    "usb.control": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            len: number;
            data: string;
        };
    };
    "usb.switch": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            switched: boolean;
        };
    };
    "usb.bulk": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            len: number;
            data: string;
        };
    };
    "usb.batch": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            count: number;
            fail: number;
            reads: any[];
        };
    };
    "rf.attach": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            attached: boolean;
            channel: number;
        };
    };
    "rf.detach": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            detached: boolean;
        };
    };
    "system.logs": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            lines: string[];
        };
    };
    "server.start": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            running: boolean;
            port: number;
            url: string;
            hits: number;
            routes: number;
        };
    };
    "server.put": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            path: string;
            bytes: number;
        };
    };
    "server.stop": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            running: boolean;
        };
    };
    "server.status": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            running: boolean;
            port: number;
            url: string;
            hits: number;
            routes: number;
        };
    };
    "files.grant": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            granted: boolean;
            uri: string;
            name: string;
        };
    };
    "files.roots": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            roots: {
                uri: string;
                name: string;
            }[];
        };
    };
    "files.list": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            uri: string;
            docId: string;
            entries: {
                docId: string;
                name: string;
                mime: string;
                dir: boolean;
                size: number;
                at: number;
            }[];
        };
    };
    "files.read": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            docId: string;
            bytes: number;
            base64: string;
        };
    };
    "files.write": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            docId: string;
            bytes: number;
        };
    };
    "system.settings": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            opened: boolean;
            page: string;
        };
    };
    "system.battery": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            level: number;
            charging: boolean;
            saver: boolean;
            unrestricted: boolean;
            temp: number;
        };
    };
    "files.share": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            shared: boolean;
            uri: string;
            bytes: number;
        };
    };
    "lan.scan": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            ip: string;
            name: string;
            ports: string;
            via: string;
            at: number;
        };
    };
    "lan.ports": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            port: number;
            family: string;
            probe: string;
            hex: string;
            tls: string;
            cert: string;
            proto: string;
            ms: number;
            at: number;
        };
    };
    "media.show": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            ok: boolean;
        };
    };
    "media.hide": {
        capability: string;
        kind: string;
        minBridge: number;
        android: string[];
        mock: {
            ok: boolean;
        };
    };
    "media.command": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            ack: boolean;
        };
    };
    "share.target": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            kinds: string[];
        };
    };
    "share.incoming": {
        capability: string;
        kind: string;
        minBridge: number;
        android: any[];
        mock: {
            ack: boolean;
        };
    };
};
