// GENERATED by tools/shell-gen.mjs from packages/shell/actions.json — do not edit.
// Run `deno task shell` after changing the catalogue; `--check` gates it before every push.
export const CATALOGUE_BRIDGE = 1;
export const ACTIONS = {
  "system.info": {
    "capability": "system",
    "kind": "call",
    "minBridge": 1,
    "android": [],
    "mock": {
      "bridge": 1,
      "sdk": 36,
      "release": "16",
      "model": "Gate Device",
      "pkg": "apk.microspec.a0000000000000000"
    }
  }
};
