/**
 * The sign-in surface — ONE Preact component, `SignIn`, so every app that gates on a session shows the same
 * thing: Google first (the GIS button, One Tap/FedCM once per page), GitHub as the quiet second way, and
 * inside the APK a "sign in via browser" pairing flow, since a WebView has no popups and no GIS. Gate-safe:
 * under `gate` a plain kit button sets the mock Google session.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/signin.js — edit the JSDoc there, never this file.
/**
 * The sign-in surface: Google's GIS button plus a quiet GitHub action in a browser, a browser-pairing button
 * inside the APK, a mock Google button under the gate. Props:
 * @param github   "quiet" (default: a small text action under Google) · "primary" (GitHub is the button, no
 *                 Google — for apps that need a GitHub token) · false (Google only)
 * @param scope    the GitHub scope to ask for (see auth.js SCOPE)
 * @param onDone   called with the session after either provider succeeds
 * @param onError  called with an Error when a sign-in fails (the surface also shows its own line)
 */
export function SignIn({ github, scope, locale, onDone, onError, className }: {
    github?: string;
    scope?: any;
    locale: any;
    onDone: any;
    onError: any;
    className?: string;
}): any;
