/**
 * sitelabel — turn a page URL into something a human reads in a list row, and group pages by the site they
 * belong to. Pure, DOM-free and network-free, so it is unit-tested, deterministic in the gate and correct
 * offline. Exports humanText (decode machine text once, where it enters a label), hostOf/registrableDomain/
 * siteName, pageLabel/pageLabelInfo/isWeakLabel, cleanPageTitle, sourceTitle (THE answer to "what is this
 * page called") and groupByDomain.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sitelabel.js — edit the JSDoc there, never this file.
/**
 * Turn machine text (percent-encoded, entity-laden, or both) into the text a person reads. Never throws.
 * @param raw a URL segment, a scraped title, a filename-derived title
 * @returns the decoded, unmarked-up, single-spaced string
 */
export function humanText(raw: any): any;
/**
 * The hostname of a URL without a leading `www.`; a string that is not a URL comes back as itself.
 * @param url a page URL
 * @returns the bare hostname
 */
export function hostOf(url: any): any;
/**
 * The registrable domain of a host — the site, so subdomains group together (commons.wikimedia.org → wikimedia.org).
 * @param host a hostname
 * @returns the registrable domain, two-label public suffixes respected (bbc.co.uk stays bbc.co.uk)
 */
export function registrableDomain(host: any): string;
/**
 * The site's display name: the capitalised label before the public suffix (mixkit.co → Mixkit).
 * @param url a page URL
 * @returns the site name, or the registrable domain when there is no label to show
 */
export function siteName(url: any): any;
/**
 * Is this label only a URL shape ("View video", "Video81234567") rather than a name? True when every token is weak.
 * @param label a derived label
 * @returns true when the label tells the reader nothing and the page should be asked for its own title
 */
export function isWeakLabel(label: any): boolean;
/**
 * Derive a page's readable title from its URL and say whether the derivation found a name or only a shape.
 * @param url the page URL (a search results page is titled by its term)
 * @param opts `max` — the label's character cap (default 42)
 * @returns `{ label, weak }` — `weak: true` means the caller should ask the page for its own title
 */
export function pageLabelInfo(url: any, { max }?: {
    max?: number;
}): {
    label: any;
    weak: boolean;
};
/**
 * The readable title of THAT page (not the site), derived from its URL.
 * @param url the page URL
 * @param opts `max` — the label's character cap (default 42)
 * @returns the label; the site name for a bare root, the raw string for a non-URL
 */
export function pageLabel(url: any, opts: any): any;
/**
 * A page's OWN title with the site chrome stripped off its ends ("Slow river - TUBE.EXAMPLE" → "Slow river").
 * @param raw the <title>/og:title or extracted clip title
 * @param url the page URL, used to recognise the site's name in the title
 * @param opts `max` — the character cap (default 64)
 * @returns the cleaned title, or "" when nothing worth showing is left
 */
export function cleanPageTitle(raw: any, url: any, { max }?: {
    max?: number;
}): any;
/**
 * THE one answer to "what is this page called": a URL that names the page wins, then the page's own title,
 * then the caller's hint, and only then the shape the URL could manage.
 * @param url the page URL
 * @param opts `pageTitle` (the page's own title), `hint` (the title of the clip dived from), `max` (the caller's room; 0 = each producer's own cap)
 * @returns the name to show
 */
export function sourceTitle(url: any, { pageTitle, hint, max }?: {
    pageTitle?: string;
    hint?: string;
    max?: number;
}): any;
/**
 * Group pages by the site they belong to, in first-appearance order.
 * @param list URL strings or objects with a `url`
 * @returns [{ domain, name, items }] — `items` keep their input order
 */
export function groupByDomain(list: any): any[];
