/**
 * Modern loading placeholders — no content-less spinners and no layout-hiding loading screens: the real
 * structure renders at once and only the not-yet-known VALUES are atomic skeletons in place. Exports the
 * Scramble text decode, the Pixels image placeholder, useReveal (hold a skeleton a minimum time, then
 * reveal), Reveal and a last-resort Loading block. Everything goes instant in the gate and under
 * prefers-reduced-motion so shots and e2e stay deterministic.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/skeleton.js — edit the JSDoc there, never this file.
/**
 * Atomic text value slot: holds a scramble for ~minMs then decodes into `text`; a perpetual placeholder bar without one.
 * @param props `text` (the value, or none for a placeholder), `len` (placeholder length guess), `cls`, `speed` (ms per tick), `minMs` (hold before decoding)
 * @returns the <span> the slot renders into
 */
export function Scramble({ text, len, cls, speed, minMs }: {
    text: any;
    len?: number;
    cls?: string;
    speed?: number;
    minMs?: number;
}): any;
/**
 * A blinking-pixel image placeholder on a <canvas> sized to its box; a single frozen frame in the gate.
 * @param props `cls` — extra classes on the canvas
 * @returns the aria-hidden <canvas>
 */
export function Pixels({ cls }: {
    cls?: string;
}): any;
/**
 * Hold a whole skeleton for a minimum time (no flash on a fast load), then reveal.
 * @param ready whether the real content is available
 * @param minMs the minimum hold since first render
 * @returns false while the skeleton should still show, true once it may reveal
 */
export function useReveal(ready: any, minMs?: number): boolean;
/**
 * Last-resort loading block: a few decoding lines for a view with no meaningful structure to show yet.
 * @param props `lines` — the placeholder length of each line
 * @returns the role="status" block
 */
export function Loading({ lines }?: {
    lines?: number[];
}): any;
/** Wrapper whose children fade in when they replace a skeleton (the `ms-reveal` class); final state in the gate. */
export function Reveal({ children, cls }: {
    children: any;
    cls?: string;
}): any;
