/**
 * Audio-reactive visual DSP and geometry maths, with no browser and no WebGL: a Uint8Array FFT frame in,
 * perceptual log band levels, a bass/mid/treble split, a spectral-centroid hue, an attack/release Envelope,
 * a scrolling terrain height-field and smoothed tilt Parallax out — plus the pure geometry helpers
 * (sampleBand, idle, fib, galaxyDisc, frameFit) the 3D scenes and their Canvas2D fallbacks share, and a
 * deterministic seedFrame for the gate. The maths lives here so `deno test` verifies it.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/spectrum.js — edit the JSDoc there, never this file.
/**
 * Geometric (log-spaced) band edges as FFT-bin indices, so the bar chart reads as a real spectrum.
 * @param bars number of bands
 * @param fMin lowest frequency (Hz)
 * @param fMax highest frequency (Hz)
 * @param sr sample rate
 * @param fftSize the AnalyserNode fftSize
 * @returns bars+1 monotonic bin indices in [1, bins-1]
 */
export function logBandEdges(bars?: number, fMin?: number, fMax?: number, sr?: number, fftSize?: number): number[];
/**
 * Mean magnitude within each band, normalised to 0..1.
 * @param u8 the FFT frame (Uint8Array, 0..255)
 * @param edges bin indices from logBandEdges
 * @returns one level per band
 */
export function bandLevels(u8: any, edges: any): any[];
/**
 * Bass / mid / treble energy (20-150 / 250-2000 / 2000-16000 Hz), each 0..1.
 * @param u8 the FFT frame
 * @param sr sample rate
 * @param fftSize the AnalyserNode fftSize
 * @returns `{ bass, mid, treble }`
 */
export function splitBands(u8: any, sr?: number, fftSize?: number): {
    bass: number;
    mid: number;
    treble: number;
};
/**
 * Energy-weighted mean frequency of the frame, mapped to a hue so the visual depends on the song.
 * @param u8 the FFT frame
 * @param sr sample rate
 * @param fftSize the AnalyserNode fftSize
 * @returns { hz, hue (280..190), t (0..1 log position between 80 Hz and 6 kHz) }
 */
export function spectralCentroid(u8: any, sr?: number, fftSize?: number): number;
/**
 * A stateful asymmetric envelope follower: fast attack, slow release, per band.
 * @param attack rise coefficient per update (0..1)
 * @param release fall coefficient per update (0..1)
 * @param n number of bands
 * @returns { v, update(targets) } — `update` mutates and returns the Float32Array `v`
 */
export function Envelope(attack?: number, release?: number, n?: number): Float32Array;
/**
 * Scroll the audio-terrain height-field back one row (with decay) and inject the current levels as the front row.
 * @param grid caller-owned Float32Array(rows*cols), row-major, row 0 = front
 * @param rows grid rows
 * @param cols grid columns
 * @param front the current band levels
 * @returns the same grid, mutated
 */
export function advanceTerrain(grid: any, rows: any, cols: any, front: any): any;
/**
 * Smoothed, clamped device-tilt to parallax offset in -1..1; eases back to centre when reduced or unread.
 * @param opts `alpha` (EMA factor), `maxDeg` (tilt that maps to full offset), `gain`, `reduced` (prefers-reduced-motion)
 * @returns { x, y, update(beta, gamma) } — `update` feeds a DeviceOrientation reading and returns { x, y }
 */
export function Parallax({ alpha, maxDeg, gain, reduced }?: {
    alpha?: number;
    maxDeg?: number;
    gain?: number;
    reduced?: boolean;
}): number;
/**
 * Sample the band-level array at a 0..1 fraction, clamped.
 * @param levels band levels
 * @param frac position across the bands, 0..1
 * @returns the nearest band's level, 0 for an empty array
 */
export function sampleBand(levels: any, frac: any): any;
/**
 * Idle "breath" pulse so a silent scene is never a dead flatline.
 * @param phase animation phase (radians)
 * @param floor centre of the pulse
 * @param amp amplitude around the floor
 * @returns floor + amp·sin(2·phase)
 */
export function idle(phase: any, floor?: number, amp?: number): number;
/**
 * Point i of n on a unit sphere via the Fibonacci lattice — even, no pole clumping.
 * @param i point index
 * @param n total points
 * @returns [x, y, z] on the unit sphere
 */
export function fib(i: any, n: any): number[];
/**
 * Base positions for a spiral galaxy disc: n points over spun, jittered arms.
 * @param n number of points
 * @param opts `radius`, `branches`, `spin`, `randomness`, `power`, `thin` (y squash)
 * @param rng caller-owned 0..1 source (deterministic → testable)
 * @returns Float32Array(n*3) of xyz triples
 */
export function galaxyDisc(n: any, { radius, branches, spin, randomness, power, thin }?: {
    radius?: number;
    branches?: number;
    spin?: number;
    randomness?: number;
    power?: number;
    thin?: number;
}, rng?: () => number): Float32Array;
/**
 * Camera distance that frames a subject in a perspective camera on BOTH axes, so a portrait viewport never clips it.
 * @param halfW the subject's projected half-width in world units
 * @param halfH the subject's projected half-height in world units
 * @param fovYDeg the camera's vertical field of view (degrees)
 * @param aspect viewport width / height
 * @param opts `margin` (air around the subject, 1 = rim-hugging), `lift` (push up the frame, fraction of height)
 * @returns { dist, drop } — place the camera `dist` away and aim at (0, -drop, 0)
 */
export function frameFit(halfW: any, halfH: any, fovYDeg: any, aspect: any, { margin, lift }?: {
    margin?: number;
    lift?: number;
}): number;
/**
 * A deterministic seeded FFT frame — a bass-heavy descending curve with ripple — for the gate and the Canvas2D fallback.
 * @param bins frame length
 * @param phase animates the ripple without an AudioContext
 * @returns Uint8Array(bins) of 0..255 magnitudes
 */
export function seedFrame(bins?: number, phase?: number): Uint8Array;
/** Default analysis parameters: frequency range, bar count, sample rate and FFT size. */
export const DEFAULTS: {};
