/**
 * # runtime/sse.js — server-sent events off a fetch() body, complete events only
 *
 * EventSource cannot POST and cannot carry a JSON body, so a streamed reply from the edge is read off a
 * fetch() body by hand — and the bug that hides there is a `data:` line cut across two reads, which loses a
 * word in the middle of a sentence and looks like the model stuttered. This module is the one incremental
 * parser the farm feeds that text to, in whatever chunking it arrives; it yields COMPLETE events only. Pure,
 * dependency-free and unit-tested, so the streaming path is verified without a network.
 *
 * ![sse — chunked text in, complete events out](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-sse.svg)
 *
 * ## Import
 * ```js
 * import { parseSse } from "/_rt/sse.js";                    // an app's page: the import map resolves /_rt/
 * import { parseSse } from "@microspec/core/runtime/sse.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link parseSse} — `parseSse()` returns `{ push(text) → events[], end() → events[] }`; an event is `{ event, data }` with `event` defaulting to "message" and `data` JSON-parsed when it parses, else the raw string.
 *
 * ## In practice
 * ```js
 * import { parseSse } from "@microspec/core/runtime/sse.js";                     // rt/characters.js (persona)
 *
 * const r = await fetch(`${BASE}/chat/stream`, { method: "POST", headers: { "content-type": "application/json" }, body, signal });
 * const reader = r.body.getReader(), dec = new TextDecoder(), p = parseSse();
 * let acc = "", meta = null;
 * const handle = (ev) => {
 *   if (ev.event === "meta") meta = ev.data;
 *   else if (ev.data && typeof ev.data.d === "string") { acc += ev.data.d; onDelta?.(ev.data.d, acc); }
 * };
 * while (true) {
 *   const { value, done } = await reader.read();
 *   if (done) break;
 *   for (const ev of p.push(dec.decode(value, { stream: true }))) handle(ev);
 * }
 * for (const ev of p.end()) handle(ev);                                             // the last event has no trailing blank line
 * ```
 *
 * ## How it fits
 * It imports nothing and nothing else in the runtime imports it; `tests/sse_test.js` pins the chunking
 * cases. One farm app reaches it — persona, through the product module `rt/characters.js`, which reads the
 * edge's streamed chat reply with it and re-exports `parseSse`.
 *
 * ## Invariants and pitfalls
 * - Feed the text as it arrives, in any chunking: a `data:` line split across two reads is held in the buffer
 *   until its newline, so no word is lost.
 * - An event is emitted only on the blank line that ends it; call `end()` after the body closes to flush
 *   the final event, which usually has no trailing blank line.
 * - Multi-line `data:` joins with a newline per the spec; a single leading space after `data:` is stripped.
 * - Comment lines (starting with `:`) are dropped; a blank line with no pending data resets the event name
 *   and emits nothing.
 * - `data` is `JSON.parse`d when it parses and left as the raw string otherwise — check the type before
 *   reading fields.
 * - `\r\n` line endings are accepted.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sse.js — edit the JSDoc there, never this file.
/**
 * # runtime/sse.js — server-sent events off a fetch() body, complete events only
 *
 * EventSource cannot POST and cannot carry a JSON body, so a streamed reply from the edge is read off a
 * fetch() body by hand — and the bug that hides there is a `data:` line cut across two reads, which loses a
 * word in the middle of a sentence and looks like the model stuttered. This module is the one incremental
 * parser the farm feeds that text to, in whatever chunking it arrives; it yields COMPLETE events only. Pure,
 * dependency-free and unit-tested, so the streaming path is verified without a network.
 *
 * ![sse — chunked text in, complete events out](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-sse.svg)
 *
 * ## Import
 * ```js
 * import { parseSse } from "/_rt/sse.js";                    // an app's page: the import map resolves /_rt/
 * import { parseSse } from "@microspec/core/runtime/sse.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link parseSse} — `parseSse()` returns `{ push(text) → events[], end() → events[] }`; an event is `{ event, data }` with `event` defaulting to "message" and `data` JSON-parsed when it parses, else the raw string.
 *
 * ## In practice
 * ```js
 * import { parseSse } from "@microspec/core/runtime/sse.js";                     // rt/characters.js (persona)
 *
 * const r = await fetch(`${BASE}/chat/stream`, { method: "POST", headers: { "content-type": "application/json" }, body, signal });
 * const reader = r.body.getReader(), dec = new TextDecoder(), p = parseSse();
 * let acc = "", meta = null;
 * const handle = (ev) => {
 *   if (ev.event === "meta") meta = ev.data;
 *   else if (ev.data && typeof ev.data.d === "string") { acc += ev.data.d; onDelta?.(ev.data.d, acc); }
 * };
 * while (true) {
 *   const { value, done } = await reader.read();
 *   if (done) break;
 *   for (const ev of p.push(dec.decode(value, { stream: true }))) handle(ev);
 * }
 * for (const ev of p.end()) handle(ev);                                             // the last event has no trailing blank line
 * ```
 *
 * ## How it fits
 * It imports nothing and nothing else in the runtime imports it; `tests/sse_test.js` pins the chunking
 * cases. One farm app reaches it — persona, through the product module `rt/characters.js`, which reads the
 * edge's streamed chat reply with it and re-exports `parseSse`.
 *
 * ## Invariants and pitfalls
 * - Feed the text as it arrives, in any chunking: a `data:` line split across two reads is held in the buffer
 *   until its newline, so no word is lost.
 * - An event is emitted only on the blank line that ends it; call `end()` after the body closes to flush
 *   the final event, which usually has no trailing blank line.
 * - Multi-line `data:` joins with a newline per the spec; a single leading space after `data:` is stripped.
 * - Comment lines (starting with `:`) are dropped; a blank line with no pending data resets the event name
 *   and emits nothing.
 * - `data` is `JSON.parse`d when it parses and left as the raw string otherwise — check the type before
 *   reading fields.
 * - `\r\n` line endings are accepted.
 * @module
 */
/**
 * Create an incremental SSE parser: feed it text chunks as they arrive, get back only COMPLETE events.
 * @returns `{ push(text) → events[], end() → events[] }` — an event is `{ event, data }`, `data` JSON-parsed when it parses
 */
export function parseSse(): {
    push(text: any): any[];
    end(): any[];
};
