/**
 * A server-sent-events parser for fetch() bodies — pure, dependency-free, unit-tested. EventSource cannot
 * POST, so a streamed reply from the edge is read off a fetch() body by hand; the one export, parseSse(),
 * takes the text in whatever chunking it arrives and yields COMPLETE events only, so a `data:` line cut
 * across two reads never loses a word.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sse.js — edit the JSDoc there, never this file.
/**
 * A server-sent-events parser for fetch() bodies — pure, dependency-free, unit-tested. EventSource cannot
 * POST, so a streamed reply from the edge is read off a fetch() body by hand; the one export, parseSse(),
 * takes the text in whatever chunking it arrives and yields COMPLETE events only, so a `data:` line cut
 * across two reads never loses a word.
 * @module
 */
/**
 * Create an incremental SSE parser: feed it text chunks as they arrive, get back only COMPLETE events.
 * @returns `{ push(text) → events[], end() → events[] }` — an event is `{ event, data }`, `data` JSON-parsed when it parses
 */
export function parseSse(): {
    push(text: any): any[];
    end(): any[];
};
