/**
 * THE service worker — one implementation shared by every app in the farm. A classic worker script (not an
 * ES module: `importScripts` cannot load one), so it exports nothing; each app's generated `sw.js` stub sets
 * `self.MS = { app, version, precache }` and imports this file. It precaches the shell (own files, /_rt/
 * closure and the pinned CDN graph), serves stale-while-revalidate, never blocks on a dying link, and backs
 * off on a bad one; the manifest alone is network-first because it is the installed app's identity.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sw-core.js — edit the JSDoc there, never this file.
declare function cacheNameFor(url: any): string;
declare function serve(e: any, req: any, url: any, name: any): Promise<any>;
declare function manifestFirst(e: any, cache: any, req: any, url: any): Promise<any>;
declare function lookup(cache: any, req: any): Promise<any>;
declare function timedFetch(req: any, url: any, ms: any, background: any): any;
declare function shouldRevalidate(url: any): boolean;
declare function revalidate(cache: any, req: any, url: any): Promise<void>;
declare function differs(a: any, b: any): boolean;
declare function announce(): Promise<void>;
declare function precache(): Promise<void>;
declare function walk(href: any, seen: any, depth: any): Promise<void>;
declare function readIfSmall(res: any): Promise<{
    type: any;
    text: any;
}>;
declare function references(type: any, text: any): string[];
declare const CFG: any;
declare const APP_CACHE: string;
declare const APP_PREFIX: string;
declare const CDN_CACHE: "ms-cdn-v1";
declare const CDN: string[];
declare const COLD_TIMEOUT: 12000;
declare const REVAL_TIMEOUT: 20000;
declare const WALK_MAX: 90;
declare const WALK_DEPTH: 3;
declare const WALK_PARSE_MAX: number;
declare function isNav(req: any): boolean;
declare function cacheable(res: any): boolean;
declare function isManifest(req: any, url: any): boolean;
declare const revalidated: Set<any>;
declare let announced: boolean;
declare const LOCAL: boolean;
declare const JS_REF: RegExp;
declare const CSS_REF: RegExp;
