/* @ts-self-types="./sw-core.d.ts" */
/**
 * # runtime/sw-core.js — THE service worker, written once for every app in the farm
 *
 * One offline-first implementation shared by all 74 apps. It is a classic worker script, not an ES module
 * (`importScripts` cannot load one), so it exports nothing: each app's generated `sw.js` stub sets
 * `self.MS = { app, version, precache }` and imports this file. The stub is unavoidable — a worker's scope
 * comes from its own script path and GitHub Pages cannot send `Service-Worker-Allowed` — but the logic
 * must exist once: the farm previously carried 57 hand-copied workers, which is how 57 copies of the same
 * four bugs shipped. The contract: precache the shell at install (own files, the /_rt/ closure and the pinned
 * CDN graph, walked through esm.sh's re-export stubs), serve stale-while-revalidate, never block on a dying
 * link, back off on a bad one — and treat the web manifest as the one file that is network-first, because
 * it is the installed app's identity.
 *
 * ![The service worker map: the generated sw.js stub feeding self.MS into install precache, the fetch policy splitting app cache, CDN cache and untouched live data, and the revalidation that announces an update to the page](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-sw-core.svg)
 *
 * ## Import
 * ```js
 * // apps/<id>/sw.js — GENERATED by deploy/sw.mjs, never imported by a page: the browser registers it.
 * self.MS = {
 *   app: "sopilka",
 *   version: "8d641b12c5",
 *   precache: ["./", "./index.html", "./manifest.json", "./spec.json", "./view.js", "/_rt/index.js", "https://esm.sh/preact@10.27.1"],
 * };
 * importScripts("/_rt/sw-core.js");
 * ```
 * The page side is index.js: `navigator.serviceWorker.register("sw.js", { updateViaCache: "none" })`.
 *
 * ## What it exports
 * Nothing — a classic worker script loaded by `importScripts`. Its only surface is `self.MS_POLICY`
 * (`{ cacheNameFor, APP_CACHE, CDN_CACHE, CDN }`), exposed so the unit gate can evaluate the file against a
 * stubbed `self` and prove WHICH origins get cached and which app owns which cache.
 *
 * ## In practice
 * ```js
 * // index.js — the page's half of the update handshake, reduced. The worker never swaps itself in.
 * navigator.serviceWorker.register("sw.js", { updateViaCache: "none" }).then((reg) => {
 *   const offer = () => S.update.set(true);                     // render.js paints the restart snackbar
 *   if (reg.waiting && navigator.serviceWorker.controller) offer();
 *   navigator.serviceWorker.addEventListener("message", (e) => { if (e.data?.type === "ms-update") offer(); });
 *   app.applyUpdate = () => {
 *     if (reg.waiting) reg.waiting.postMessage("ms-skip-waiting");   // → controllerchange → reload
 *     else location.reload();
 *   };
 * });
 * ```
 *
 * ## How it fits
 * Imports nothing and is imported by nothing in the module sense: it reads `self.MS` from the stub that
 * `importScripts` it. `deploy/sw.mjs` (the `sw` 8n8 node, `jsr:@microspec/core/sw`) generates that stub for
 * every app from its import graph and reds a stale one; `gen/scaffold.mjs` writes the placeholder stub a
 * new app starts with. index.js registers the worker and answers `ms-update` / sends `ms-skip-waiting`;
 * notify.js's notifications land in the `notificationclick` handler here. All 74 farm apps ship a stub that
 * loads it; `tests/sw_test.js` evaluates the file under a fake `self` and `CacheStorage`.
 *
 * ## Invariants and pitfalls
 * - Cache names are namespaced per app (`ms-<app>-<version>`) and `activate` deletes only this app's own prefix. CacheStorage
 *   is per ORIGIN and every app shares one — the old "delete every key but mine" cleanup wiped every other app's cache on its
 *   first launch after a version bump. The pinned CDN graph lives in one shared `ms-cdn-v1` instead of 57 copies of tailwind.
 * - Cross-origin precaching is not optional: with no build step the app's dependencies live on esm.sh and jsDelivr. They are
 *   re-issued in `cors` mode with `credentials: "omit"` because an opaque `no-cors` response cannot be cached; every pinned
 *   origin sends `access-control-allow-origin: *`. Precaching only the import-map URL is not enough — esm.sh answers with a
 *   re-export stub, so the walk follows `import`/`from` and CSS `url()` references up to 90 URLs, 3 levels, 512 KB per file.
 * - The manifest is network-first (`cache: "no-cache"`) with the cached copy as the fallback: on Android an install bakes
 *   `name`, `icons`, `display`, `start_url`, `orientation` into a WebAPK, and the browser's 24-hour update check is an
 *   ordinary fetch that lands in this worker — a cache hit would hand it the manifest the app was installed with, forever.
 * - `skipWaiting` is never automatic. A changed same-origin shell file (compared by ETag / Last-Modified / Content-Length,
 *   once per worker lifetime) or a waiting worker tells the page, which offers a restart; only the page's
 *   `ms-skip-waiting` message triggers the swap. No validator on either side means "unchanged" — a false prompt is worse than a late one.
 * - Each URL is revalidated at most once per worker lifetime, and never when offline, `saveData`, or on (slow-)2g — so a weak
 *   link behaves like no link instead of worse than one. A cold miss races a 12 s timeout, then falls back to cache, then to `./`.
 * - Untouched on purpose: non-GET, `range` requests (206 is not cacheable — media streams itself), non-http(s) schemes, `/feed`
 *   and any third-party origin not in the pinned CDN list. Query-insensitive and scope-root lookup applies to NAVIGATIONS only —
 *   for a subresource `?id=5` and `?id=3` are different answers.
 * - On localhost (the Chromium gate) the CDN half of the precache is skipped; the same-origin half still runs, so the code path is exercised.
 * - A notification tap focuses the window already open under this scope, or opens one at the app root — never a second copy.
 * @module
 */
"use strict";

const CFG = self.MS || { app: "app", version: "0", precache: [] };

const APP_CACHE = `ms-${CFG.app}-${CFG.version}`;
const APP_PREFIX = `ms-${CFG.app}-`;
const CDN_CACHE = "ms-cdn-v1";

const CDN = [
  "https://esm.sh",
  "https://cdn.jsdelivr.net",
  "https://code.iconify.design",
  "https://api.iconify.design",
  "https://api.simplesvg.com",
  "https://api.unisvg.com",
  "https://fonts.googleapis.com",
  "https://fonts.gstatic.com",
];

const COLD_TIMEOUT = 12000;
const REVAL_TIMEOUT = 20000;
const WALK_MAX = 90;
const WALK_DEPTH = 3;
const WALK_PARSE_MAX = 512 * 1024;

function cacheNameFor(url) {
  if (url.origin === self.location.origin) {
    const path = url.pathname.replace(/\/+$/, "");
    return path === "/feed" || path.endsWith("/feed") || /\/feed\//.test(url.pathname) ? null : APP_CACHE;
  }
  return CDN.includes(url.origin) ? CDN_CACHE : null;
}
self.MS_POLICY = { cacheNameFor, APP_CACHE, CDN_CACHE, CDN };

const isNav = (req) => req.mode === "navigate" || req.destination === "document";
const cacheable = (res) => !!res && res.status === 200 && (res.type === "basic" || res.type === "cors" || res.type === "default");

const isManifest = (req, url) => req.destination === "manifest" || /\/manifest\.json$/.test(url.pathname);

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  if (req.headers.has("range")) return;
  let url;
  try { url = new URL(req.url); } catch { return; }
  if (url.protocol !== "https:" && url.protocol !== "http:") return;
  const name = cacheNameFor(url);
  if (!name) return;
  e.respondWith(serve(e, req, url, name));
});

async function serve(e, req, url, name) {
  const cache = await caches.open(name);
  if (isManifest(req, url)) return manifestFirst(e, cache, req, url);
  const hit = await lookup(cache, req);
  if (hit) {
    if (shouldRevalidate(req.url)) e.waitUntil(revalidate(cache, req, url));
    return hit;
  }
  try {
    const res = await timedFetch(req, url, COLD_TIMEOUT, false);
    if (cacheable(res)) { const copy = res.clone(); e.waitUntil(cache.put(req, copy).catch(() => {})); }
    return res;
  } catch {
    return (await lookup(cache, req)) || Response.error();
  }
}

async function manifestFirst(e, cache, req, url) {
  try {
    const res = await timedFetch(req, url, COLD_TIMEOUT, true);
    if (!cacheable(res)) return (await cache.match(req, { ignoreVary: true })) || res;
    const copy = res.clone();
    e.waitUntil(cache.put(req, copy).catch(() => {}));
    return res;
  } catch {
    return (await cache.match(req, { ignoreVary: true })) || Response.error();
  }
}

async function lookup(cache, req) {
  const exact = await cache.match(req, { ignoreVary: true });
  if (exact) return exact;
  if (!isNav(req)) return null;
  return (await cache.match(req, { ignoreSearch: true, ignoreVary: true })) ||
    (await cache.match(new URL("./", self.location).href, { ignoreVary: true })) ||
    (await cache.match(new URL("./index.html", self.location).href, { ignoreVary: true })) || null;
}

function timedFetch(req, url, ms, background) {
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), ms);
  const cross = url.origin !== self.location.origin;
  const p = cross
    ? fetch(url.href, { mode: "cors", credentials: "omit", signal: ctl.signal })
    : fetch(req, background ? { cache: "no-cache", signal: ctl.signal } : { signal: ctl.signal });
  return p.finally(() => clearTimeout(timer));
}

const revalidated = new Set();
let announced = false;

function shouldRevalidate(url) {
  if (revalidated.has(url)) return false;
  try {
    if (self.navigator && self.navigator.onLine === false) return false;
    const c = self.navigator && self.navigator.connection;
    if (c && (c.saveData === true || /^(slow-)?2g$/.test(c.effectiveType || ""))) return false;
  } catch { }
  revalidated.add(url);
  return true;
}

async function revalidate(cache, req, url) {
  try {
    const res = await timedFetch(req, url, REVAL_TIMEOUT, true);
    if (!cacheable(res)) return;
    const prev = await cache.match(req, { ignoreVary: true });
    await cache.put(req, res.clone());
    if (prev && url.origin === self.location.origin && differs(prev, res)) announce();
  } catch { }
}

function differs(a, b) {
  for (const h of ["etag", "last-modified", "content-length"]) {
    const x = a.headers.get(h), y = b.headers.get(h);
    if (x && y) return x !== y;
  }
  return false;
}

async function announce() {
  if (announced) return;
  announced = true;
  for (const c of await self.clients.matchAll({ type: "window" })) c.postMessage({ type: "ms-update" });
}

self.addEventListener("install", (e) => e.waitUntil(precache()));

const LOCAL = /^(localhost|127\.0\.0\.1|\[::1\])$/.test(self.location.hostname);

async function precache() {
  const seen = new Set();
  await Promise.allSettled((CFG.precache || []).map((raw) => {
    if (LOCAL && /^https?:\/\//.test(raw)) return Promise.resolve();
    let href;
    try { href = new URL(raw, self.location).href; } catch { return Promise.resolve(); }
    return walk(href, seen, 0);
  }));
}

async function walk(href, seen, depth) {
  if (seen.has(href) || seen.size >= WALK_MAX) return;
  seen.add(href);
  let url;
  try { url = new URL(href); } catch { return; }
  const name = cacheNameFor(url);
  if (!name) return;
  let res;
  try {
    const cross = url.origin !== self.location.origin;
    res = await fetch(url.href, cross ? { mode: "cors", credentials: "omit", cache: "reload" } : { cache: "reload" });
  } catch { return; }
  if (!cacheable(res)) return;
  const cache = await caches.open(name);
  const body = depth < WALK_DEPTH && url.origin !== self.location.origin ? await readIfSmall(res.clone()) : null;
  await cache.put(url.href, res).catch(() => {});
  if (!body) return;
  for (const ref of references(body.type, body.text)) {
    let next;
    try { next = new URL(ref, url).href; } catch { continue; }
    if (!/^https?:/.test(next)) continue;
    await walk(next, seen, depth + 1);
  }
}

async function readIfSmall(res) {
  const type = res.headers.get("content-type") || "";
  const len = parseInt(res.headers.get("content-length") || "0", 10);
  if (len > WALK_PARSE_MAX) return null;
  if (!/javascript|css/.test(type)) return null;
  try {
    const text = await res.text();
    return text.length > WALK_PARSE_MAX ? null : { type, text };
  } catch { return null; }
}

const JS_REF = /(?:\bfrom\s*|\bimport\s+)["']([^"']+)["']/g;
const CSS_REF = /url\(\s*["']?([^"')]+)["']?\s*\)/g;

function references(type, text) {
  const re = /css/.test(type) ? CSS_REF : JS_REF;
  const out = [];
  re.lastIndex = 0;
  let m;
  while ((m = re.exec(text))) {
    const s = m[1];
    if (!s || s.startsWith("data:") || s.startsWith("#")) continue;
    out.push(s);
  }
  return out;
}

self.addEventListener("activate", (e) => e.waitUntil((async () => {
  for (const k of await caches.keys()) {
    if (k === APP_CACHE || k === CDN_CACHE) continue;
    if (k.startsWith(APP_PREFIX) || k === `${CFG.app}-v1` || k === `${CFG.app}-v2`) await caches.delete(k);
  }
  await self.clients.claim();
})()));

self.addEventListener("message", (e) => { if (e.data === "ms-skip-waiting") self.skipWaiting(); });

self.addEventListener("notificationclick", (e) => {
  e.notification.close();
  const scope = self.registration.scope, url = new URL(e.notification.data?.url || "./", scope).href;
  e.waitUntil((async () => {
    for (const c of await self.clients.matchAll({ type: "window", includeUncontrolled: true })) {
      if (c.url.startsWith(scope) && "focus" in c) return c.focus();
    }
    return self.clients.openWindow ? self.clients.openWindow(url) : null;
  })());
});
