/**
 * # runtime/sw-core.js — THE service worker, written once for every app in the farm
 *
 * One offline-first implementation shared by all 74 apps. It is a classic worker script, not an ES module
 * (`importScripts` cannot load one), so it exports nothing: each app's generated `sw.js` stub sets
 * `self.MS = { app, version, precache }` and imports this file. The stub is unavoidable — a worker's scope
 * comes from its own script path and GitHub Pages cannot send `Service-Worker-Allowed` — but the logic
 * must exist once: the farm previously carried 57 hand-copied workers, which is how 57 copies of the same
 * four bugs shipped. The contract: precache the shell at install (own files, the /_rt/ closure and the pinned
 * CDN graph, walked through esm.sh's re-export stubs), serve stale-while-revalidate, never block on a dying
 * link, back off on a bad one — and treat the web manifest as the one file that is network-first, because
 * it is the installed app's identity.
 *
 * ![The service worker map: the generated sw.js stub feeding self.MS into install precache, the fetch policy splitting app cache, CDN cache and untouched live data, and the revalidation that announces an update to the page](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-sw-core.svg)
 *
 * ## Import
 * ```js
 * // apps/<id>/sw.js — GENERATED by deploy/sw.mjs, never imported by a page: the browser registers it.
 * self.MS = {
 *   app: "sopilka",
 *   version: "8d641b12c5",
 *   precache: ["./", "./index.html", "./manifest.json", "./spec.json", "./view.js", "/_rt/index.js", "https://esm.sh/preact@10.27.1"],
 * };
 * importScripts("/_rt/sw-core.js");
 * ```
 * The page side is index.js: `navigator.serviceWorker.register("sw.js", { updateViaCache: "none" })`.
 *
 * ## What it exports
 * Nothing — a classic worker script loaded by `importScripts`. Its only surface is `self.MS_POLICY`
 * (`{ cacheNameFor, APP_CACHE, CDN_CACHE, CDN }`), exposed so the unit gate can evaluate the file against a
 * stubbed `self` and prove WHICH origins get cached and which app owns which cache.
 *
 * ## In practice
 * ```js
 * // index.js — the page's half of the update handshake, reduced. The worker never swaps itself in.
 * navigator.serviceWorker.register("sw.js", { updateViaCache: "none" }).then((reg) => {
 *   const offer = () => S.update.set(true);                     // render.js paints the restart snackbar
 *   if (reg.waiting && navigator.serviceWorker.controller) offer();
 *   navigator.serviceWorker.addEventListener("message", (e) => { if (e.data?.type === "ms-update") offer(); });
 *   app.applyUpdate = () => {
 *     if (reg.waiting) reg.waiting.postMessage("ms-skip-waiting");   // → controllerchange → reload
 *     else location.reload();
 *   };
 * });
 * ```
 *
 * ## How it fits
 * Imports nothing and is imported by nothing in the module sense: it reads `self.MS` from the stub that
 * `importScripts` it. `deploy/sw.mjs` (the `sw` 8n8 node, `jsr:@microspec/core/sw`) generates that stub for
 * every app from its import graph and reds a stale one; `gen/scaffold.mjs` writes the placeholder stub a
 * new app starts with. index.js registers the worker and answers `ms-update` / sends `ms-skip-waiting`;
 * notify.js's notifications land in the `notificationclick` handler here. All 74 farm apps ship a stub that
 * loads it; `tests/sw_test.js` evaluates the file under a fake `self` and `CacheStorage`.
 *
 * ## Invariants and pitfalls
 * - Cache names are namespaced per app (`ms-<app>-<version>`) and `activate` deletes only this app's own prefix. CacheStorage
 *   is per ORIGIN and every app shares one — the old "delete every key but mine" cleanup wiped every other app's cache on its
 *   first launch after a version bump. The pinned CDN graph lives in one shared `ms-cdn-v1` instead of 57 copies of tailwind.
 * - Cross-origin precaching is not optional: with no build step the app's dependencies live on esm.sh and jsDelivr. They are
 *   re-issued in `cors` mode with `credentials: "omit"` because an opaque `no-cors` response cannot be cached; every pinned
 *   origin sends `access-control-allow-origin: *`. Precaching only the import-map URL is not enough — esm.sh answers with a
 *   re-export stub, so the walk follows `import`/`from` and CSS `url()` references up to 90 URLs, 3 levels, 512 KB per file.
 * - The manifest is network-first (`cache: "no-cache"`) with the cached copy as the fallback: on Android an install bakes
 *   `name`, `icons`, `display`, `start_url`, `orientation` into a WebAPK, and the browser's 24-hour update check is an
 *   ordinary fetch that lands in this worker — a cache hit would hand it the manifest the app was installed with, forever.
 * - `skipWaiting` is never automatic. A changed same-origin shell file (compared by ETag / Last-Modified / Content-Length,
 *   once per worker lifetime) or a waiting worker tells the page, which offers a restart; only the page's
 *   `ms-skip-waiting` message triggers the swap. No validator on either side means "unchanged" — a false prompt is worse than a late one.
 * - Each URL is revalidated at most once per worker lifetime, and never when offline, `saveData`, or on (slow-)2g — so a weak
 *   link behaves like no link instead of worse than one. A cold miss races a 12 s timeout, then falls back to cache, then to `./`.
 * - Untouched on purpose: non-GET, `range` requests (206 is not cacheable — media streams itself), non-http(s) schemes, `/feed`
 *   and any third-party origin not in the pinned CDN list. Query-insensitive and scope-root lookup applies to NAVIGATIONS only —
 *   for a subresource `?id=5` and `?id=3` are different answers.
 * - On localhost (the Chromium gate) the CDN half of the precache is skipped; the same-origin half still runs, so the code path is exercised.
 * - A notification tap focuses the window already open under this scope, or opens one at the app root — never a second copy.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/sw-core.js — edit the JSDoc there, never this file.
export {};
