/**
 * The pure decision behind gesture.js useSwipe, kept apart so the unit gate can import it without pulling
 * htm/preact through the browser import map. Exports `swipeDir`, which turns a released pointer's delta into
 * "left" / "right" / "up" / "down", or null for a tap or wobble.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/swipe.js — edit the JSDoc there, never this file.
/**
 * The pure decision behind gesture.js useSwipe, kept apart so the unit gate can import it without pulling
 * htm/preact through the browser import map. Exports `swipeDir`, which turns a released pointer's delta into
 * "left" / "right" / "up" / "down", or null for a tap or wobble.
 * @module
 */
/**
 * Classify a released pointer's travel as a swipe direction; the dominant axis wins, a perfect diagonal
 * reads as horizontal.
 * @param dx horizontal delta in px, right positive
 * @param dy vertical delta in px, down positive
 * @param threshold minimum travel on the dominant axis before it counts as a swipe (default 52)
 * @returns "left" | "right" | "up" | "down", or null for a tap / wobble below the threshold
 */
export function swipeDir(dx: any, dy: any, threshold?: number): "up" | "left" | "right" | "down";
