/**
 * Deterministic first-letter placeholder art. Exports `letterTile`, which renders a self-contained data-URI
 * SVG (no fetch, so the "cards always have a thumbnail" gate stays honest offline) with a hue hashed from the
 * text, so the same title always gets the same tile. Extracted from near-identical copies in cinema, books
 * and wiki.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/tile.js — edit the JSDoc there, never this file.
/**
 * Deterministic first-letter placeholder art. Exports `letterTile`, which renders a self-contained data-URI
 * SVG (no fetch, so the "cards always have a thumbnail" gate stays honest offline) with a hue hashed from the
 * text, so the same title always gets the same tile. Extracted from near-identical copies in cinema, books
 * and wiki.
 * @module
 */
/**
 * Build a data-URI SVG tile showing the first letter of `text` on a solid HSL ground.
 * @param text the title to tile; its first non-blank character is shown upper-cased ("?" when empty)
 * @param opts optional `w`/`h` in px (300×450), `sat`/`light` in percent (30/24), `fontSize` (half the
 *             shorter side) and `hue` (0–359; defaults to a stable hash of `text`)
 * @returns a `data:image/svg+xml,…` string usable directly as an image src
 */
export function letterTile(text: any, { w, h, sat, light, fontSize, hue }?: {
    w?: number;
    h?: number;
    sat?: number;
    light?: number;
    fontSize?: any;
    hue?: any;
}): string;
