/**
 * Dynamic body translation — the text that comes from an API in the source language regardless of the user's
 * locale (UI chrome is translated at author time via the i18n dicts). Exports the sync cache read `tr`,
 * `isTranslated`, the async `warm` that fills the cache and bumps `trTick`, `toEnglish` for image-model
 * prompts, and `CONTENT_LANG`. Fail-open by design: a miss returns the original, so the app is always
 * readable; every unique string is translated once via the keyless gtx endpoint and cached in localStorage.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/translate.js — edit the JSDoc there, never this file.
/**
 * Synchronous cache read for use inside render: the cached translation of `text`, or `text` itself on a
 * miss or passthrough.
 * @param text the original (source-language) string
 * @param target the active locale code
 * @returns the translated string when cached, otherwise the original
 */
export function tr(text: any, target: any): any;
/**
 * Whether `text` already has a cached translation for `target` (false while still in flight, so a caller
 * can show a loading state); passthrough and empty strings count as done.
 * @param text the original string
 * @param target the active locale code
 * @returns true when nothing is left to fetch for this string
 */
export function isTranslated(text: any, target: any): boolean;
/**
 * Translate arbitrary user text into English for the image models (source auto-detected, cached in its own
 * `ms:tr:_en` bucket, fail-open).
 * @param text the user's prompt in any language
 * @returns the English text, or the original on any error / non-string input
 */
export function toEnglish(text: any): Promise<any>;
/**
 * Translate every not-yet-cached string in `texts` (6 in flight at a time, de-duplicated against concurrent
 * warms), persist the cache and bump `trTick` once if anything landed. Cheap no-op when nothing is missing.
 * @param texts the original strings to translate
 * @param target the active locale code
 */
export function warm(texts: any, target: any): Promise<void>;
/** The language the source APIs speak ("en"); a target equal to this is a passthrough. */
export const CONTENT_LANG: "en";
/** Counter atom bumped whenever new translations land, so components subscribed to it re-render. */
export const trTick: any;
