/**
 * The UI kit — the farm's ONE set of interaction nodes: {@link Sheet}, {@link Segmented}, {@link Island},
 * {@link Panel}, {@link Slider}, {@link Transport}, plus {@link Stage} and {@link Row}. Every app composes
 * these instead of hand-rolling its own; each reads the density tokens in theme.css rather than a size.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/ui.js — edit the JSDoc there, never this file.
/**
 * The ONE bottom sheet: a native `<dialog>` with drag-to-dismiss grip, optional title/subtitle/icon header
 * and close button, backdrop, and its own inner scroll (the farm's only sanctioned nested scroll).
 * @param props `open` / `onClose` should come from a routing atom so system Back closes it; `size` "md"|"lg";
 *   `tone` "glass" (opaque base-100) | "frost" (translucent over a stage); `locale` for the close label
 * @returns the sheet element
 */
export function Sheet({ id, open, onClose, title, subtitle, icon, locale, size, tone, children }: {
    id: any;
    open: any;
    onClose: any;
    title: any;
    subtitle: any;
    icon: any;
    locale: any;
    size?: string;
    tone?: string;
    children: any;
}): any;
/**
 * The ONE tab / option strip for a one-of-N choice. Items carry `id`, `label`, and optionally `icon`,
 * `dot` (the option's colour, painted on its mark), `meta` (trailing mono count), `busy`, `title`.
 * @param props `value` the selected id; `onChange(id)`; `variant` "solid" (filled ink pill) | "outline"
 *   (hairline pill, for strips sitting ON content); `size` "md"|"sm"; `scroll` makes it a rail; `attr`
 *   the data attribute each button carries (e2e hook); `label` the group's accessible name; `tone` "inset"|"frost"
 * @returns the strip element
 */
export function Segmented({ items, value, onChange, variant, size, scroll, attr, label, tone }: {
    items: any;
    value: any;
    onChange: any;
    variant?: string;
    size?: string;
    scroll?: boolean;
    attr?: string;
    label: any;
    tone?: string;
}): any;
/**
 * The floating glass panel — the dock's material, reusable for a tool app's persistent controls.
 * @param props `pinned` fixes it to clear the chrome (`at` "bottom" above the dock | "top" under the header,
 *   both off the MEASURED chrome tokens); `tone` "glass" | "dark" (over media) | "frost" (over a stage);
 *   `tag` "div" | "section"; `className` for width/radius/row; other props pass to the element
 * @returns the island element (wrapped in a positioner when pinned)
 */
export function Island({ children, className, tag, pinned, at, tone, ...rest }: {
    [x: string]: any;
    children: any;
    className?: string;
    tag?: string;
    pinned?: boolean;
    at?: string;
    tone?: string;
    rest?: any;
}): any;
/**
 * The solid in-flow surface: the page extruded at the shallow elevation, with an optional mono micro-label.
 * @param props `title` the micro-label; `className` extra classes; other props pass to the element
 * @returns the panel element
 */
export function Panel({ title, children, className, ...rest }: {
    [x: string]: any;
    title: any;
    children: any;
    className?: string;
    rest?: any;
}): any;
/**
 * A labelled range whose mono caption is also the input's accessible name; the value is deliberately not printed.
 * @param props `id`; `label`; `value`; `onInput(number)`; `min`/`max`/`step` (default 0…1 by 0.02);
 *   `attr` the data attribute the label carries (default `data-macro`)
 * @returns the label element wrapping the range input
 */
export function Slider({ id, label, value, onInput, min, max, step, attr }: {
    id: any;
    label: any;
    value: any;
    onInput: any;
    min?: number;
    max?: number;
    step?: number;
    attr?: string;
}): any;
/**
 * The ONE play control. Every part is opt-in by handler: `onToggle` (play/pause), `onPrev`/`onNext`,
 * `onSeek` with `pos`/`dur` (the seek bar), `onRepeat`/`onShuffle`, `title`/`subtitle`, `actions` (the
 * app's own tools, demoted into an overflow sheet when they do not fit). Sizes "md" | "sm" | "hero".
 * @param props see the destructured parameter list; `locale` selects the SYS strings for the labels
 * @returns the transport container (an `@container` that compacts on width and height)
 */
export function Transport({ locale, playing, onToggle, onPrev, onNext, pos, dur, onSeek, repeat, onRepeat, shuffle, onShuffle, title, subtitle, lead, trail, stopIcon, size, disabled, className, actions, keep, moreOpen, onMore, onMoreClose, onScrubStart, onScrub, onScrubEnd, }: {
    locale?: string;
    playing?: boolean;
    onToggle: any;
    onPrev: any;
    onNext: any;
    pos?: number;
    dur?: number;
    onSeek: any;
    repeat: any;
    onRepeat: any;
    shuffle?: boolean;
    onShuffle: any;
    title: any;
    subtitle: any;
    lead: any;
    trail: any;
    stopIcon?: boolean;
    size?: string;
    disabled?: boolean;
    className?: string;
    actions?: any[];
    keep?: number;
    moreOpen: any;
    onMore: any;
    onMoreClose: any;
    onScrubStart: any;
    onScrub: any;
    onScrubEnd: any;
}): any;
/**
 * The visible void between the chrome — the `flex-1 min-h-0` box a fit view's canvas centres in.
 * @param props `children` the canvas/stage content; `className` extra classes
 * @returns the `data-stage-box` element
 */
export function Stage({ children, className }: {
    children: any;
    className?: string;
}): any;
/** The frost recipe (class list): a 60% base-100 wash, xl blur, a 10% hairline and one soft cast — glass over a stage. */
export const FROST: "bg-base-100/60 backdrop-blur-xl border border-base-content/10 sf-frost text-base-content";
/** The sheet box's class list — the shell every bottom sheet in the farm shares (radius, width cap, 88dvh height cap). */
export const SHEET_BOX: "modal-box rounded-t-[1.75rem] max-w-[min(36rem,100vw)] mx-auto min-w-0 flex flex-col gap-[var(--ms-gap)] p-[var(--ms-pad)] pb-8 max-h-[88dvh]";
/** The one-line flex row used inside panels and sheets (label left, control right) at the kit's gap. */
export function Row({ children, className }: {
    children: any;
    className?: string;
}): any;
