/**
 * # runtime/urlquery.js — which query key carries the search term, and the same URL with a new one
 *
 * A scraped source is often just a results page (`…/search?q=cats`). If the runtime can find WHICH query key
 * carries the search term, the app can offer a search box that swaps that value and re-extracts videos for
 * the new query. The resolver is the point: every site names its key differently (`q` for Google, Bing,
 * DuckDuckGo, GitHub, Reddit, Vimeo; `search_query` for YouTube; `SearchText` for AliExpress; `text` Yandex,
 * `wd` Baidu, `p` Yahoo, `k` Amazon, `_nkw` eBay, `s` WordPress and Medium…), so it recognises them by name in
 * a deliberate priority order — the most universal keys win when a URL happens to carry more than one. A URL
 * with query params but NO known key is NOT searchable: the module never guesses which param is the term,
 * because guessing would corrupt the URL. Pure and DOM-free, so it is unit-tested in Deno.
 *
 * ![The urlquery module map: a URL → resolveSearch walks the priority list of known keys → searchable, key, term → buildSearchUrl sets that key and keeps every other param](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-urlquery.svg)
 *
 * ## Import
 * ```js
 * import { resolveSearch, buildSearchUrl } from "/_rt/urlquery.js";                    // an app's page: the import map resolves /_rt/
 * import { resolveSearch, buildSearchUrl } from "@microspec/core/runtime/urlquery.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link resolveSearch} — `resolveSearch(url)` → `{ searchable, key, term }`: `key` is the ORIGINAL-cased param name that carries the term (null when not searchable), `term` its current value ("" when not searchable).
 * - {@link buildSearchUrl} — `buildSearchUrl(url, term)` → string: the URL with its resolved key set to `term`, path and every other param preserved (spaces as `+`); `url` unchanged when it is not searchable.
 *
 * ## In practice
 * ```js
 * import { resolveSearch, buildSearchUrl } from "/_rt/urlquery.js";
 *
 * // A pasted results URL (`…/search?q=…`) is searchable → offer to swap the term and play those results.
 * const sr = resolveSearch(norm());
 * const search = (e) => { e?.preventDefault?.(); const url = norm(), term = q.trim(); if (url && term) goto(buildSearchUrl(url, term)); };
 * ...
 * ${sr.searchable ? html`<input id="sheet-search" type="search" value=${q} onInput=${(e) => setQ(e.target.value)} />` : null}
 *
 * // A saved page row seeds its search box with the term the URL already carries:
 * const [q, setQ] = useState(resolveSearch(s.url).term || "");                // apps/reel/view.js
 * ```
 *
 * ## How it fits
 * Imports nothing — the `URL` global only. `sitelabel.js` imports `resolveSearch` to name a source by its
 * query. 1 farm app imports it directly — reel, in the source sheet and the saved-page rows. Covered by
 * `packages/runtime/tests/urlquery_test.js`.
 *
 * ## Invariants and pitfalls
 * - Never guess: query params with no recognised key ⇒ `searchable: false`; so does a URL with no params or
 *   an unparseable one. `buildSearchUrl` then returns the input untouched.
 * - Priority order is deliberate: `q`, `query`, `search`, `search_query`, `searchtext`, `text`, `keyword`,
 *   `keywords`, `term`, `s`, `k`, `kw`, `wd`, `p`, `_nkw`, `word`, `find`, `key` — the first key present in
 *   that order wins, not the first in the URL.
 * - Matching is case-insensitive but the ORIGINAL casing is preserved on rewrite (AliExpress `SearchText`).
 * - The rewrite goes through `URLSearchParams.set`, so spaces become `+` (form encoding, which every engine
 *   accepts) and every other param and the path survive.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/urlquery.js — edit the JSDoc there, never this file.
/**
 * Find which query parameter of `url` carries the search term, by the module's priority list of known keys.
 * @param url the page URL to inspect
 * @returns `{ searchable, key, term }` — `key` keeps the URL's original casing (null when not searchable),
 *          `term` is its current value ("" when not searchable)
 */
export function resolveSearch(url: any): {
    searchable: boolean;
    key: any;
    term: any;
};
/**
 * Rewrite `url` so its resolved search key carries `term`, preserving the path and every other parameter.
 * @param url the page URL whose search term is to be swapped
 * @param term the new search term
 * @returns the rewritten URL string, or `url` unchanged when it is not searchable
 */
export function buildSearchUrl(url: any, term: any): any;
