/**
 * Resolve a page's "search" query parameter and rewrite it, so an app scraped from a results page can offer
 * a search box that swaps the term and re-extracts. Exports `resolveSearch` (which known key carries the
 * term, by a deliberate priority order across the popular engines) and `buildSearchUrl` (the same URL with
 * that key set). Never guesses an unknown key — guessing would corrupt the URL. Pure and DOM-free.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/urlquery.js — edit the JSDoc there, never this file.
/**
 * Find which query parameter of `url` carries the search term, by the module's priority list of known keys.
 * @param url the page URL to inspect
 * @returns `{ searchable, key, term }` — `key` keeps the URL's original casing (null when not searchable),
 *          `term` is its current value ("" when not searchable)
 */
export function resolveSearch(url: any): {
    searchable: boolean;
    key: any;
    term: any;
};
/**
 * Rewrite `url` so its resolved search key carries `term`, preserving the path and every other parameter.
 * @param url the page URL whose search term is to be swapped
 * @param term the new search term
 * @returns the rewritten URL string, or `url` unchanged when it is not searchable
 */
export function buildSearchUrl(url: any, term: any): any;
