/**
 * # runtime/usage.js — what was used, as a census rather than a stream
 *
 * `telemetry.js` answers "what broke". This answers "what did anyone touch", for every app at once, without
 * an app wiring anything: `start()` installs it, the same way it installs the error hooks.
 *
 * The farm already labels every interactive element with a `data-*` hook, because the e2e suite reads them —
 * `data-generate`, `data-montage`, `data-clip-play`, `data-length`. That labelling is a complete, maintained
 * map of an app's controls, and it is free: this module rides it instead of asking 82 apps to instrument
 * themselves. One delegated listener sees every tap in the app.
 *
 * ![The usage census: one delegated pointerdown over the data-* hooks and the screen atom, counted in memory and rolled up into a single event on hide](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-usage.svg)
 *
 * ## Why a census and not events
 *
 * The budget is 40 events a minute (`telemetry.js` PER_MINUTE) and a person taps faster than that. Sending
 * one event per tap would spend the whole minute inside the first few seconds and then drop the rest
 * silently — the log would be a random prefix of the session and would read as if the person stopped.
 *
 * So nothing is sent per tap. Taps and screens are COUNTED in memory and flushed as ONE rolled-up event:
 * `{ taps: { montage: 3, generate: 1 }, screens: { clips: 2 }, secs: 94 }`. A session of four hundred taps
 * costs one row, and the row says more than four hundred would: which controls were reached at all, how
 * often, and which states were entered.
 *
 * ## What is recorded, and what is not
 *
 * Only the NAME of the `data-*` hook — `montage`, not `data-chunk="7"`, never the value, never the element's
 * text, never a prompt. The names are authored by us and mean nothing outside the farm, so a row carries no
 * user content at all; `telemetry.js` adds the same coarse context it adds to an error row.
 *
 * ## Flush points
 *
 * On `visibilitychange` to hidden and on `pagehide` — the moments a phone actually ends a session — and on a
 * slow interval so a long session is not lost to a battery death. `report()` is a no-op under the gate and in
 * tests, so this is inert there without knowing about either.
 *
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/usage.js — edit the JSDoc there, never this file.
export function hookOf(node: any): any;
/** Roll the census into one event and start a fresh one. Sends nothing when nothing happened. */
export function flushUsage(): void;
/**
 * Install the census. `S` is the app's store: its `screen` atom is the state half of the answer — which
 * sheets and sub-screens were actually opened, which is the one thing a tap census cannot see (a screen can
 * be reached by a swipe or a back gesture as well as by a button).
 */
export function installUsage(S: any): void;
/** How often a long session rolls up even if it never goes to the background. */
export const CENSUS_MS: 120000;
/** A cap on distinct names, so a `data-*` that carries an id cannot grow the row without bound. */
export const MAX_KEYS: 40;
