/**
 * Loud, fail-fast spec guard — the lightweight runtime half of two-tier validation (packages/schema's ajv
 * contract is the exhaustive author-time half, too heavy to ship to the browser). Exports `validateSpec`,
 * which catches the high-value AI footguns and throws an Error naming the exact JSON path so a bad spec
 * fails at boot instead of rendering blank, and `SPEC_MAJOR`. Zero dependencies, so unit tests import it
 * with no import map.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/validate.js — edit the JSDoc there, never this file.
/**
 * Check a spec for the high-value footguns (version, id, tabs, i18n, fav, per-tab card contracts, detail
 * actions, filter controls) and throw an Error naming the exact JSON path on the first failure.
 * @param spec the app spec object as passed to start()
 * @returns the same spec, unchanged, so the call can be inlined
 */
export function validateSpec(spec: any): any;
/**
 * Loud, fail-fast spec guard — the lightweight runtime half of two-tier validation (packages/schema's ajv
 * contract is the exhaustive author-time half, too heavy to ship to the browser). Exports `validateSpec`,
 * which catches the high-value AI footguns and throws an Error naming the exact JSON path so a bad spec
 * fails at boot instead of rendering blank, and `SPEC_MAJOR`. Zero dependencies, so unit tests import it
 * with no import map.
 * @module
 */
/** Spec contract major version; a spec declaring a different `v` is rejected. Bump on a breaking spec change. */
export const SPEC_MAJOR: 1;
