/**
 * # runtime/version.js — three truths in one footer
 *
 * Version chrome. Every app's profile footer shows three things together so you can tell exactly what is
 * running on a device: the app's own version (`spec.version`, read through `appVersion`), the shared
 * runtime version (`CORE`, bumped on a meaningful runtime change) and the deployed git short-SHA (`BUILD`,
 * stamped at build time — the single unambiguous "which commit" for a continuously-deployed farm). The last
 * two are re-exported from the build-time stamp in build.js; this file only adds the app's own number and
 * the one place render.js reads all three from. What it buys the farm is a bug report that names a commit
 * and a core, not a date.
 *
 * ![The version chrome: spec.version, CORE and BUILD from build.js, drawn together in the profile footer](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/module-version.svg)
 *
 * ## Import
 * ```js
 * import { appVersion, CORE, BUILD } from "/_rt/version.js";                    // an app's page: the import map resolves /_rt/
 * import { appVersion, CORE, BUILD } from "@microspec/core/runtime/version.js";  // a product rt/ module or a Deno test
 * ```
 *
 * ## What it exports
 * - {@link appVersion} — `appVersion(spec)` → `spec.version`, or "1.0" when the spec declares none.
 * - {@link CORE} — the shared runtime version, re-exported from build.js ("1.0" in source, stamped at deploy).
 * - {@link BUILD} — the deployed git short-SHA, re-exported from build.js ("dev" in source, stamped at deploy).
 *
 * ## In practice
 * ```js
 * import { CORE, BUILD, appVersion } from "./version.js";   // runtime/render.js — the profile footer
 *
 * html`<div data-version class="text-center text-[11px] text-base-content/70 pt-1 tabular-nums">
 *   v${appVersion(A.spec)} · core ${CORE}${BUILD && BUILD !== "dev" ? ` · ${BUILD}` : ""}
 * </div>`;
 * ```
 *
 * ## How it fits
 * It imports build.js and nothing else. render.js is its only importer — the profile footer is drawn by the
 * shared chrome — so every one of the 74 farm apps reaches it without naming it, and each app's generated
 * sw.js precaches `/_rt/version.js`. The stamping itself lives in deploy/build.mjs, which rewrites build.js
 * into dist/_rt/build.js; this file never changes between local dev and the deployed dist.
 *
 * ## Invariants and pitfalls
 * - `appVersion` never returns empty: a spec without `version` reads as "1.0", so the footer always has a
 *   number to show.
 * - `BUILD` is "dev" in local dev and in the gate (they serve the runtime source, not the built dist); the
 *   footer hides the SHA then, so a placeholder never reads as a deployed commit.
 * - `CORE` is bumped only on a meaningful runtime change — it is the number that tells two devices apart
 *   when both show the same app version.
 * - Add nothing here that must survive a deploy stamp: `CORE` and `BUILD` come from build.js, which
 *   deploy/build.mjs replaces wholesale.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/version.js — edit the JSDoc there, never this file.
/**
 * The app's own version as declared in its spec.
 * @param spec the app spec
 * @returns `spec.version`, or "1.0" when the spec declares none
 */
export function appVersion(spec: any): any;
