/**
 * Version chrome — the three truths every app's profile footer shows together so you can tell exactly what
 * is running on a device: the app's own version (`appVersion`), the shared runtime version (`CORE`) and the
 * deployed git short-SHA (`BUILD`), the last two re-exported from the build-time stamp in build.js.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/version.js — edit the JSDoc there, never this file.
/**
 * The app's own version as declared in its spec.
 * @param spec the app spec
 * @returns `spec.version`, or "1.0" when the spec declares none
 */
export function appVersion(spec: any): any;
