/**
 * Version chrome — the three truths every app's profile footer shows together so you can tell exactly what
 * is running on a device: the app's own version (`appVersion`), the shared runtime version (`CORE`) and the
 * deployed git short-SHA (`BUILD`), the last two re-exported from the build-time stamp in build.js.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/version.js — edit the JSDoc there, never this file.
export function appVersion(spec: any): any;
