/**
 * Weather numbers, dependency-free on purpose: WMO 4677 code tables (`wmoIcon`, `wmoKey`, `isSnowCode`,
 * `isStormCode`), low-precision solar position and moon phase (`solarPosition`, `moonPhase`), the mapping
 * from raw readings to the live-sky shader's channels (`skyVary`, `skyInk`), and the hourly temperature
 * spline (`curvePath`). Nothing here touches the DOM or the network, so every function is unit-tested.
 * @module
 */
// GENERATED by tools/dts.mjs from packages/runtime/weather.js — edit the JSDoc there, never this file.
/**
 * Sun altitude and azimuth for a place and instant.
 * @param lat degrees north · @param lng degrees east · @param ms epoch milliseconds (UTC)
 * @returns {{alt: number, az: number}} altitude in degrees above the horizon, azimuth 0=N clockwise
 */
export function solarPosition(lat: any, lng: any, ms: any): {
    alt: number;
    az: number;
};
/**
 * Moon phase 0..1 — 0 and 1 new, 0.5 full. Mean synodic month from a known new moon; good to about half a
 * day, which is a crescent one pixel off and nobody's evening ruined.
 */
export function moonPhase(ms: any): number;
/**
 * vary = [sun altitude, cloud, wet, wind].
 * Altitude is normalised so -1 is civil twilight's floor (-12°) rather than the nadir: below that the sky
 * stops changing and spending range there would waste the whole night on one flat value.
 */
export function skyVary({ alt, cloudPct, precipMm, precipProb, windKmh }: {
    alt?: number;
    cloudPct?: number;
    precipMm?: number;
    precipProb?: number;
    windKmh?: number;
}): number[];
/**
 * ink = [snow, haze, storm, lightX].
 * `lightX` is the sun's azimuth flattened to a screen position: sunrise (90°) at the left edge, noon (180°,
 * due south) centred, sunset (270°) at the right. Northern hemisphere framing, deliberately — the owner is
 * in Kyiv, and a south-facing convention is the one that matches what is out of the window.
 */
export function skyInk({ code, visibilityM, az }: {
    code?: number;
    visibilityM?: number;
    az?: number;
}): number[];
/**
 * A smooth path through evenly spaced values, as an SVG `d` plus the same path closed into an area.
 * Catmull-Rom converted to cubic Béziers: a polyline reads as a chart of a sensor, a spline reads as
 * temperature, which is the thing being drawn.
 *
 * @returns {{line: string, area: string, points: {x: number, y: number}[], min: number, max: number}}
 *          Empty strings when there is nothing to draw — callers must not have to guard.
 */
export function curvePath(values: any, w: any, h: any, pad?: number): {
    line: string;
    area: string;
    points: {
        x: number;
        y: number;
    }[];
    min: number;
    max: number;
};
/**
 * Lucide icon name for a WMO 4677 present-weather code.
 * @param c the WMO code (0..99)
 * @returns an `lucide:*` icon id
 */
export function wmoIcon(c: any): "lucide:sun" | "lucide:cloud-sun" | "lucide:cloud" | "lucide:cloud-fog" | "lucide:cloud-drizzle" | "lucide:cloud-rain" | "lucide:snowflake" | "lucide:cloud-rain-wind" | "lucide:cloud-snow" | "lucide:cloud-lightning";
/** i18n key for the condition in words. The app owns the strings; this owns the mapping. */
export function wmoKey(c: any): "wClear" | "wPartly" | "wOvercast" | "wFog" | "wDrizzle" | "wRain" | "wSnow" | "wShowers" | "wSnowShowers" | "wThunder";
/** Frozen precipitation: snowfall 71-77, snow grains included, and snow showers 85-86. */
export function isSnowCode(c: any): boolean;
/** Thunderstorm, with or without hail. */
export function isStormCode(c: any): boolean;
