// Store launcher data — the farm's app list. Generated by deploy/manifest.mjs (scans every app's
// spec + brand) into apps.json, so this is offline, zero-network, and always in sync with the farm.
import apps from "./apps.json" with { type: "json" };

export async function load() {
  return { items: apps, meta: {} };
}
