/**
 * # clean — the ship-phase sweep: nothing ships with litter.
 *
 * Runs after the commit, before push. Fatal: untracked files that are not ignored, committed build output,
 * submodules that are not checked out. Warned (the eye decides): tracked files over 2 MB, JS/MD files that no
 * other tracked file mentions.
 *
 * ```sh
 * deno run -A jsr:@microspec/core/clean      # in any farm repo
 * deno task 8n8 clean
 * ```
 * @module
 */
// GENERATED by tools/dts.mjs from tools/clean.mjs — edit the JSDoc there, never this file.
export {};
