/**
 * Affected-app detection from the REAL import graph: pure functions (file IO injected) that resolve
 * specifiers, collect a file's imports, walk an entry's transitive closure and classify a changed-file
 * list into the set of apps CI must re-verify. Exports `RT`/`RT_OVERLAY` (where the core runtime lives in
 * this tree), `resolveSpec`, `importSpecs`, `staticSpecs`, `htmlAssets`, `importMapOf`, `buildClosure`,
 * `isGlobal` and `classifyAffected`; `tools/affected.mjs` is the thin IO wrapper the CI calls.
 * @module
 */
// GENERATED by tools/dts.mjs from tools/graph.mjs — edit the JSDoc there, never this file.
/**
 * Resolves a module specifier to a repo-relative path, or null when it is external (CDN-pinned).
 * @param spec the specifier as written in the import statement
 * @param fromFile repo-relative path of the file that contains the import
 * @returns the repo-relative path of the local module, or null for an external specifier
 */
export function resolveSpec(spec: any, fromFile: any): string;
/**
 * Collects every module specifier a source file references — static, dynamic and side-effect imports.
 * @param src the file's source text
 * @returns the unique specifiers, unresolved, in order of first appearance
 */
export function importSpecs(src: any): any[];
/**
 * Collects the specifiers a file reaches statically (`from "x"` and side-effect imports), excluding dynamic `import()`.
 * @param src the file's source text
 * @returns the unique static specifiers, unresolved
 */
export function staticSpecs(src: any): any[];
/**
 * Lists every URL an index.html actually loads via `<script src>` and stylesheet/preload/icon `<link href>`.
 * @param html the page source
 * @returns the unique asset URLs, verbatim
 */
export function htmlAssets(html: any): any[];
/**
 * Reads the page's inline import map.
 * @param html the page source
 * @returns the map's `imports` object ({ bareSpecifier: url }), or {} when there is none or it fails to parse
 */
export function importMapOf(html: any): any;
/**
 * Walks the transitive local import closure of an entry file, including the entry itself.
 * @param entry repo-relative path of the entry module
 * @param read `(path) => string | null` — returns a file's source, or null when it is missing
 * @returns a Set of repo-relative paths reachable from the entry
 */
export function buildClosure(entry: any, read: any): Set<any>;
/**
 * Decides whether a changed file could plausibly affect every app and must therefore trigger the whole farm.
 * @param f repo-relative path of the changed file
 * @param coreSet the shared bootstrap closure (Set of repo-relative paths)
 * @returns true when the change widens to all apps
 */
export function isGlobal(f: any, coreSet: any): boolean;
/**
 * Computes the affected set: which apps a list of changed files can reach.
 * @param changed repo-relative paths of the changed files
 * @param apps `[{ id, closure: Set<file> }]` — every app with its import closure
 * @param coreSet the shared bootstrap closure (Set of repo-relative paths)
 * @returns a sorted array of app ids; every id when a whole-farm trigger is hit
 */
export function classifyAffected(changed: any, apps: any, coreSet: any): any;
/** Repo-relative prefix of the core runtime directory in this tree (the framework checkout's own, else the JSR package's). */
export const RT: "node_modules/@jsr/microspec__core/packages/runtime/" | "packages/runtime/";
/** File names of the product's own domain modules under rt/ — the overlay that shadows the core for those /_rt/ names. */
export const RT_OVERLAY: Set<any>;
