/**
 * The UI kit manifest generator: a deliberately loud hand-rolled scanner over packages/runtime/ui.js that
 * derives every export's signature (the destructuring pattern) and doctrine (the comment block above it)
 * into tools/mcp/kit.json, so an agent's view of the kit can never drift from the code. A script with no
 * exports; `--check` makes a stale committed manifest a hard gate failure.
 * @module
 */
// GENERATED by tools/dts.mjs from tools/kit-manifest.mjs — edit the JSDoc there, never this file.
export {};
