/**
 * # kit — the UI kit manifest, derived from ui.js so an agent's view of the kit cannot drift
 *
 * A deliberately loud hand-rolled scanner over packages/runtime/ui.js. For every export it derives the
 * signature (a re-print of the destructuring pattern, never a synthesised example) and the doctrine (the
 * comment block above it; a `──` section header becomes the headline) into tools/mcp/kit.json. An agent
 * authoring an app needs both — what does Segmented take, when Island rather than Panel — and both already
 * exist in ui.js. A second copy written by hand into a doc or a prompt drifts silently: nothing fails when
 * a component grows a prop and the doc does not. So the copy is generated, and `--check` in the pre-push
 * gate makes drift a hard failure. The scanner is not a JS parser; it reads one file the farm owns, and its
 * failure mode is a crash, never a plausible partial manifest that the gate would then bless forever.
 *
 * ![The kit node in the 8n8 pipeline](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/pipeline-kit.svg)
 *
 * ## Usage
 * ```sh
 * deno run -A jsr:@microspec/core/kit            # write tools/mcp/kit.json
 * deno run -A jsr:@microspec/core/kit --check    # gate: fail if the committed manifest is stale
 * ```
 * `deno task kit` writes the manifest; `deno task gates` runs `--check` as the 8n8 node `kit`.
 *
 * ## Flags and arguments
 * | Flag | Effect |
 * | --- | --- |
 * | `--check` | Compare the generated JSON byte-for-byte with the committed tools/mcp/kit.json and write nothing. |
 *
 * Without the flag it writes. Source and output are both resolved off the package root (pkgroot.js), so
 * the same ui.js is read from a checkout and from the JSR cache, and the manifest labels its source as
 * `packages/runtime/ui.js` whichever realm produced it.
 *
 * ## What it checks / produces
 * - Writes tools/mcp/kit.json: a GENERATED banner, `source`, `import` (`/_rt/ui.js`), `count`, and one
 *   entry per export — `component` entries carry `line`, `headline`, `doc`, the derived `signature` and
 *   `props` (name, default, note); a string `constant` (SHEET_BOX) carries its `value`.
 * - Comment attribution is physical, not semantic: a comment on an entry's first line trailed the previous
 *   prop; one on its own line further down documents this prop; one after the code trails this prop.
 * - Every failure is named and prefixed `kit-manifest:`: an export with no documentation comment above it;
 *   an export more than 25 lines from its comment block (attribution would be a guess); an export that is
 *   neither a string constant nor callable; a callable that does not take one destructured props object;
 *   an export that parsed to zero props (the scanner is wrong, not the component); an unparsable parameter;
 *   an orphaned or unattached comment; an unterminated parameter list; and a final count check — N export
 *   statements but fewer entries means the scanner dropped one.
 * - `--check` reds when the manifest is missing (it names the generator to run) or stale, and says how:
 *   the exports added, the exports removed, or "a signature or doc changed" when the export set is equal.
 * - Green: `--check` reports that the manifest matches ui.js with its export count; a write lists the
 *   export names it emitted.
 *
 * ## Exit codes
 * - 0 — the manifest was written, or `--check` found it identical to the generated JSON.
 * - 1 — any scanner failure above (both modes), or a missing or stale manifest under `--check`.
 *
 * ## Where it sits
 * gate · script (frozen 2026-07-02) · needs: scaffold · needed by: no node lists it; the `gates` flow
 * targets it directly, and verify.yml runs the same `--check` as its own step ("agents read the manifest,
 * so a stale one is a wrong signature").
 *
 * ## Why
 * The kit manifest matches what the runtime actually exports. Touching the kit without `deno task kit`
 * leaves every agent reading a signature that no longer exists — the same shape as the `sw` gate, one
 * level up.
 * @module
 */
// GENERATED by tools/dts.mjs from tools/kit-manifest.mjs — edit the JSDoc there, never this file.
export {};
