/**
 * Pre-push rule: runtime modules (packages/runtime and the consumer's rt/ overlay) must import each other
 * relatively, never via an absolute "/_rt/…" — that resolves to the domain root and 404s under the
 * GitHub Pages subpath while working locally. Scans the files and exits 1 on a violation. A CLI script — it
 * exports nothing.
 * @module
 */
// GENERATED by tools/dts.mjs from tools/relimports.mjs — edit the JSDoc there, never this file.
export {};
