// microspec — the PRODUCT's preflight import map, GENERATED (like the sw stubs): the browser-free gate
// mounts real app views in Deno, and their /_rt/ imports must route per-file — the domain overlay's names
// to ./rt/, everything else to the CORE ON JSR (https). One realm for the whole mounted graph: the views
// (file), the overlay (file) and the core (https) all resolve their bare deps through THIS map's esm.sh
// pins, so there is exactly one preact. Exact keys beat the prefix key by the import-map spec.
//   deno run -A <core>/tools/rtmap.mjs            # (re)write preflight.map.json at the consumer's root
//   deno run -A <core>/tools/rtmap.mjs --check    # fail if it is stale
// A tree with no rt/ overlay (the framework itself) needs no map and generates none.
const check = Deno.args.includes("--check");

let names = [];
try {
  names = [...Deno.readDirSync("rt")]
    .filter((e) => e.isFile && e.name.endsWith(".js") && !e.name.endsWith("_test.js"))
    .map((e) => e.name).sort();
} catch { /* no overlay */ }
if (!names.length) {
  if (check) console.log("  ✓ no rt/ overlay — no preflight map needed");
  Deno.exit(0);
}

// the consumer's pinned core version — the single source is its own deno.json imports entry
const consumer = JSON.parse(await Deno.readTextFile("deno.json"));
const pin = /jsr:@microspec\/core@([^/"]+)/.exec(JSON.stringify(consumer.imports ?? {}))?.[1];
if (!pin) { console.error("rtmap: deno.json imports carry no jsr:@microspec/core@<version> pin"); Deno.exit(1); }
const base = `https://jsr.io/@microspec/core/${pin}/`;

// the core's own map supplies the CDN pins (fetch cannot read file: URLs — branch on the realm)
const mapUrl = new URL("../packages/gates/preflight.importmap.json", import.meta.url);
const coreMap = mapUrl.protocol === "file:"
  ? JSON.parse(await Deno.readTextFile(mapUrl))
  : await (await fetch(mapUrl)).json();
const imports = {};
for (const [k, v] of Object.entries(coreMap.imports)) {
  if (k === "canvas" || k === "/_rt/") continue; // relocated below — their values were relative to the core's map
  imports[k] = v;
}
imports["canvas"] = `${base}packages/gates/canvas-stub.js`;
for (const n of names) imports[`/_rt/${n}`] = `./rt/${n}`;
imports["/_rt/"] = `${base}packages/runtime/`;
imports["@microspec/core/runtime/"] = `${base}packages/runtime/`;

const want = JSON.stringify({
  "//": "GENERATED by @microspec/core tools/rtmap.mjs — do not edit by hand (--check gates drift). Routes each /_rt/ name: the rt/ overlay's own files exactly, the pinned core on JSR for the rest; one realm, one preact.",
  imports,
}, null, 2) + "\n";

// The test SHIMS. `deno test` refuses a remote URL as a test module ("No test modules found") — and worse,
// it does so SILENTLY when a local file rides along, which once passed a unit node that had run only half
// its suites. So the consumer gets local one-line shims that import the core's suites at the pin; the
// gate nodes point at these. Gitignored, regenerated here, drift-checked with the map.
const SHIMS = {
  ".microspec/tests/unit_test.js": `import "${base}packages/runtime/runtime_test.js";\n`,
  ".microspec/tests/mcp_test.js": `import "${base}tools/mcp/server_test.js";\n`,
  ".microspec/tests/pipeline_test.js": `import "${base}tools/8n8/run_test.js";\n`,
  // gate harnesses that dynamically import CONSUMER files: the import() must originate locally (a remote
  // importer may neither import file:// nor use the import map), so the shim plants a local importer first.
  ".microspec/preflight.mjs": `globalThis.__msImport = (s) => import(s);\nawait import("${base}packages/gates/preflight.mjs");\n`,
  ".microspec/verify.mjs": `globalThis.__msImport = (s) => import(s);\nawait import("${base}packages/gates/verify.mjs");\n`,
};

const have = await Deno.readTextFile("preflight.map.json").catch(() => "");
let shimsStale = false;
for (const [p, body] of Object.entries(SHIMS)) {
  if ((await Deno.readTextFile(p).catch(() => "")) !== body) shimsStale = true;
}
if (check) {
  if (want !== have || shimsStale) { console.error("preflight.map.json / .microspec test shims are stale — run the core's tools/rtmap.mjs"); Deno.exit(1); }
  console.log(`  ✓ preflight map + test shims match rt/ + the ${pin} pin (${names.length} overlay entries)`);
} else {
  await Deno.writeTextFile("preflight.map.json", want);
  await Deno.mkdir(".microspec/tests", { recursive: true });
  for (const [p, body] of Object.entries(SHIMS)) await Deno.writeTextFile(p, body);
  console.log(`preflight.map.json + 3 test shims: core ${pin} on jsr.io, ${names.length} overlay entries`);
}
