/* @ts-self-types="./rtmap.d.mts" */
/**
 * Generates the consumer's preflight import map (preflight.map.json) and its gitignored test shims: each
 * /_rt/ name routes to the rt/ overlay's own file or to the pinned core on JSR, with bare deps pinned from
 * the core's manifest so the whole mounted graph shares one preact. `--check` fails when the committed map
 * is stale. A CLI script — it exports nothing.
 * @module
 */
// microspec — the PRODUCT's preflight import map, GENERATED (like the sw stubs): the browser-free gate
// mounts real app views in Deno, and their /_rt/ imports must route per-file — the domain overlay's names
// to ./rt/, everything else to the CORE ON JSR (https). One realm for the whole mounted graph: the views
// (file), the overlay (file) and the core (https) all resolve their bare deps through THIS map's esm.sh
// pins, so there is exactly one preact. Exact keys beat the prefix key by the import-map spec.
//   deno run -A <core>/tools/rtmap.mjs            # (re)write preflight.map.json at the consumer's root
//   deno run -A <core>/tools/rtmap.mjs --check    # fail if it is stale
// A tree with no rt/ overlay (the framework itself) needs no map and generates none.
const check = Deno.args.includes("--check");

let names = [];
try {
  names = [...Deno.readDirSync("rt")]
    .filter((e) => e.isFile && e.name.endsWith(".js") && !e.name.endsWith("_test.js"))
    .map((e) => e.name).sort();
} catch { /* no overlay */ }
if (!names.length) {
  if (check) console.log("  ✓ no rt/ overlay — no preflight map needed");
  Deno.exit(0);
}

// the consumer's pinned core version — the single source is its own deno.json imports entry
const consumer = JSON.parse(await Deno.readTextFile("deno.json"));
const pin = /jsr:@microspec\/core@([^/"]+)/.exec(JSON.stringify(consumer.imports ?? {}))?.[1];
if (!pin) { console.error("rtmap: deno.json imports carry no jsr:@microspec/core@<version> pin"); Deno.exit(1); }
const base = `https://jsr.io/@microspec/core/${pin}/`;

// The bare-dep pins come from the CORE'S OWN MANIFEST (npm:…), never esm.sh: the core's modules load from
// jsr (https) and resolve their preact through the package manifest — npm's copy. If the consumer's views
// resolved the same names to esm.sh, two preacts would meet in one tree and hooks would crash on `__H`
// (measured: every tool app red, every list app green). One source of pins ⇒ one instance.
const manUrl = new URL("../deno.json", import.meta.url); // tools/ → the package root — NEVER nest a second "../" base (this exact off-by-one 404'd twice)
const manifest = manUrl.protocol === "file:"
  ? JSON.parse(await Deno.readTextFile(manUrl))
  : await (await fetch(manUrl)).json();
const imports = { ...manifest.imports };
// …plus the APP-ONLY pins (motion, lodash-es, …) from the core's own preflight map — names the manifest
// does not carry because no core module imports them. Manifest keys WIN: those must stay one-instance.
const pfUrl = new URL("../packages/gates/preflight.importmap.json", import.meta.url);
const pf = pfUrl.protocol === "file:" ? JSON.parse(await Deno.readTextFile(pfUrl)) : await (await fetch(pfUrl)).json();
for (const [k, v] of Object.entries(pf.imports)) {
  if (!(k in imports) && k !== "canvas" && k !== "/_rt/") imports[k] = v;
}
imports["canvas"] = `${base}packages/gates/canvas-stub.js`;
for (const n of names) imports[`/_rt/${n}`] = `./rt/${n}`;
imports["/_rt/"] = `${base}packages/runtime/`;
imports["@microspec/core/runtime/"] = `${base}packages/runtime/`;

const want = JSON.stringify({
  "//": "GENERATED by @microspec/core tools/rtmap.mjs — do not edit by hand (--check gates drift). Routes each /_rt/ name: the rt/ overlay's own files exactly, the pinned core on JSR for the rest; one realm, one preact.",
  imports,
}, null, 2) + "\n";

// The test SHIMS. `deno test` refuses a remote URL as a test module ("No test modules found") — and worse,
// it does so SILENTLY when a local file rides along, which once passed a unit node that had run only half
// its suites. So the consumer gets local one-line shims that import the core's suites at the pin; the
// gate nodes point at these. Gitignored, regenerated here, drift-checked with the map.
const SHIMS = {
  ".microspec/tests/unit_test.js": `import "${base}packages/runtime/runtime_test.js";\n`,
  ".microspec/tests/mcp_test.js": `import "${base}tools/mcp/server_test.js";\n`,
  ".microspec/tests/pipeline_test.js": `import "${base}tools/8n8/run_test.js";\n`,
  // gate harnesses that dynamically import CONSUMER files: the import() must originate locally (a remote
  // importer may neither import file:// nor use the import map), so the shim plants a local importer first.
  ".microspec/preflight.mjs": `globalThis.__msImport = (s) => import(s);\nawait import("${base}packages/gates/preflight.mjs");\n`,
  ".microspec/verify.mjs": `globalThis.__msImport = (s) => import(s);\nawait import("${base}packages/gates/verify.mjs");\n`,
};

// The shims are gitignored BUILD ARTIFACTS — a fresh checkout (CI) has none, so even --check WRITES them
// (always safe: derived, never committed). Only the COMMITTED map is drift-checked.
await Deno.mkdir(".microspec/tests", { recursive: true });
for (const [p, body] of Object.entries(SHIMS)) await Deno.writeTextFile(p, body);

const have = await Deno.readTextFile("preflight.map.json").catch(() => "");
if (check) {
  if (want !== have) { console.error("preflight.map.json is stale — run the core's tools/rtmap.mjs"); Deno.exit(1); }
  console.log(`  ✓ preflight map matches rt/ + the ${pin} pin (${names.length} overlay entries; shims refreshed)`);
} else {
  await Deno.writeTextFile("preflight.map.json", want);
  console.log(`preflight.map.json + ${Object.keys(SHIMS).length} shims: core ${pin}, ${names.length} overlay entries`);
}
