// microspec — the PRODUCT's preflight import map, GENERATED (like the sw stubs): the browser-free gate
// mounts real app views in Deno, and their /_rt/ imports must route per-file — the domain overlay's names
// to ./rt/, everything else to the core package. Exact keys beat the prefix key by the import-map spec.
//   deno run -A <core>/tools/rtmap.mjs            # (re)write preflight.map.json at the consumer's root
//   deno run -A <core>/tools/rtmap.mjs --check    # fail if it is stale
// A tree with no rt/ overlay (the framework itself) needs no map and generates none.
const check = Deno.args.includes("--check");
const CORE = (() => {
  try { Deno.statSync("packages/gates/preflight.importmap.json"); return "."; } catch { return "./node_modules/@jsr/microspec__core"; }
})();

let names = [];
try {
  names = [...Deno.readDirSync("rt")]
    .filter((e) => e.isFile && e.name.endsWith(".js") && !e.name.endsWith("_test.js"))
    .map((e) => e.name).sort();
} catch { /* no overlay */ }
if (!names.length) {
  if (check) console.log("  ✓ no rt/ overlay — no preflight map needed");
  Deno.exit(0);
}

const base = JSON.parse(Deno.readTextFileSync(`${CORE}/packages/gates/preflight.importmap.json`));
const imports = {};
for (const [k, v] of Object.entries(base.imports)) {
  if (k === "canvas" || k === "/_rt/") continue; // relocated below — their values were relative to the CORE's map
  imports[k] = v;
}
imports["canvas"] = `${CORE}/packages/gates/canvas-stub.js`;
for (const n of names) imports[`/_rt/${n}`] = `./rt/${n}`;
imports["/_rt/"] = `${CORE}/packages/runtime/`;

const want = JSON.stringify({
  "//": "GENERATED by @microspec/core tools/rtmap.mjs — do not edit by hand (--check gates drift). Routes each /_rt/ name: the rt/ overlay's own files exactly, the core package for the rest.",
  imports,
}, null, 2) + "\n";
const have = await Deno.readTextFile("preflight.map.json").catch(() => "");
if (check) {
  if (want !== have) { console.error("preflight.map.json is stale — run: deno run -A " + `${CORE}/tools/rtmap.mjs`); Deno.exit(1); }
  console.log(`  ✓ preflight map matches rt/ (${names.length} overlay entries)`);
} else {
  await Deno.writeTextFile("preflight.map.json", want);
  console.log(`preflight.map.json: ${names.length} overlay entries + the core fallback`);
}
