/**
 * # shell — the Android action catalogue generates both sides, so they cannot drift
 *
 * The APK bridge and the page negotiate over one catalogue, packages/shell/actions.json. This script is
 * the only writer of the runtime's copy of it: it validates the catalogue against its draft 2020-12
 * schema, rejects duplicate ids and actions declared ahead of the bridge version, and emits
 * packages/runtime/shell-actions.js — the table shell.js reads to decide what the bridge it runs in can
 * do, and the mock the gate answers with, since CI runs Chromium and never the APK. The generated module
 * carries its own registry docs; a doc written into it by hand is deleted by the next regeneration.
 *
 * ![The shell node in the 8n8 pipeline](https://cdn.jsdelivr.net/gh/damanoreshkan-beep/microspec@main/docs/art/pipeline-shell.svg)
 *
 * ## Usage
 * ```sh
 * deno run -A jsr:@microspec/core/shell            # write packages/runtime/shell-actions.js
 * deno run -A jsr:@microspec/core/shell --check    # fail if it is stale
 * ```
 * `deno task shell` writes; `deno task gates` runs `--check` as the 8n8 node `shell`.
 *
 * ## Flags and arguments
 * | Flag | Effect |
 * | --- | --- |
 * | `--check` | Compare the generated source with the file on disk; write nothing. |
 *
 * No other arguments. Every path is fixed off the package root (packages/runtime/pkgroot.js): the
 * catalogue at packages/shell/actions.json, its schema at packages/shell/catalogue.schema.json, the
 * output at packages/runtime/shell-actions.js.
 *
 * ## What it checks / produces
 * - `actions.json does not match catalogue.schema.json` — ajv (draft 2020-12, allErrors) lists every
 *   violation with its instance path.
 * - `duplicate action ids` — two actions with one id would silently shadow each other in the table; the
 *   schema cannot express uniqueness, so it is checked here.
 * - `minBridge ahead of bridgeVersion` — an action the current bridge template cannot possibly
 *   implement is a typo, not a plan.
 * - `✗ packages/runtime/shell-actions.js is stale — run deno task shell` (`--check` only) — the file on
 *   disk differs from what the catalogue generates now.
 * - Green: `✓ shell-actions.js matches the catalogue (N actions, bridge V)`.
 * - Written (without `--check`): packages/runtime/shell-actions.js, exporting `CATALOGUE_BRIDGE` (the
 *   bridge version the page was built against) and `ACTIONS` — id to `{ capability, kind, minBridge,
 *   android, mock }` — with its own `@ts-self-types` directive, module doc and a JSDoc per export, so
 *   JSR scores the generated entrypoint like any other.
 *
 * The Java dispatch registry is not generated from here: it lives in the private edge repo, is
 * hand-written against this catalogue, and a disagreement is caught on a real device.
 *
 * ## Exit codes
 * - `0` — the catalogue is valid and the table is written, or (`--check`) current.
 * - `1` — schema violation, duplicate id, minBridge ahead of the bridge, or (`--check`) a stale table.
 *
 * ## Where it sits
 * 8n8 node `shell` · phase gate · script, frozen 2026-07-28 · needs: none · needed by: none — a target of
 * the `gates` flow (the pre-push floor), so it starts the moment the flow does, in parallel with every
 * other root node.
 *
 * ## Why
 * The Android action catalogue generates both sides; `--check` fails when they drift.
 * @module
 */
// GENERATED by tools/dts.mjs from tools/shell-gen.mjs — edit the JSDoc there, never this file.
export {};
