// Generate everything that must agree with the shell action catalogue, so the two sides cannot drift.
//
//   deno run -A tools/shell-gen.mjs           write the generated files
//   deno run -A tools/shell-gen.mjs --check   fail if they are stale (the pre-push gate)
//
// Today it emits the runtime's action table. The Java dispatch registry lives in the PRIVATE edge repo
// and is NOT generated from here yet — that crosses a repo boundary and gets decided in phase 3 rather
// than guessed at now. Until then the Java side is hand-written against this file, and `os` (§6 of the
// plan) is what catches a disagreement on a real device.
import Ajv2020 from "npm:ajv@8/dist/2020.js";   // the catalogue schema is draft 2020-12, like spec.schema.json

const ROOT = new URL("../", import.meta.url);
const CATALOGUE = new URL("packages/shell/actions.json", ROOT);
const SCHEMA = new URL("packages/shell/catalogue.schema.json", ROOT);
const OUT = new URL("packages/runtime/shell-actions.js", ROOT);

const catalogue = JSON.parse(await Deno.readTextFile(CATALOGUE));
const schema = JSON.parse(await Deno.readTextFile(SCHEMA));

const ajv = new Ajv2020({ allErrors: true, strict: false });
if (!ajv.validate(schema, catalogue)) {
  console.error("actions.json does not match catalogue.schema.json:");
  for (const e of ajv.errors) console.error(`  ${e.instancePath || "/"} ${e.message}`);
  Deno.exit(1);
}

// Duplicate ids would silently shadow each other in the table; the schema cannot express it.
const ids = catalogue.actions.map((a) => a.id);
const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
if (dupes.length) { console.error(`duplicate action ids: ${[...new Set(dupes)].join(", ")}`); Deno.exit(1); }

// An action the current template cannot possibly implement is a typo, not a plan.
const ahead = catalogue.actions.filter((a) => a.minBridge > catalogue.bridgeVersion);
if (ahead.length) {
  console.error(`minBridge ahead of bridgeVersion ${catalogue.bridgeVersion}: ${ahead.map((a) => a.id).join(", ")}`);
  Deno.exit(1);
}

const table = Object.fromEntries(catalogue.actions.map((a) => [a.id, {
  capability: a.capability,
  kind: a.kind,
  minBridge: a.minBridge,
  android: a.android,
  mock: a.mock,
}]));

const body = `// GENERATED by tools/shell-gen.mjs from packages/shell/actions.json — do not edit.
// Run \`deno task shell\` after changing the catalogue; \`--check\` gates it before every push.
export const CATALOGUE_BRIDGE = ${catalogue.bridgeVersion};
export const ACTIONS = ${JSON.stringify(table, null, 2)};
`;

const check = Deno.args.includes("--check");
const current = await Deno.readTextFile(OUT).catch(() => null);
if (check) {
  if (current !== body) {
    console.error("✗ packages/runtime/shell-actions.js is stale — run `deno task shell`");
    Deno.exit(1);
  }
  console.log(`  ✓ shell-actions.js matches the catalogue (${ids.length} action${ids.length === 1 ? "" : "s"}, bridge ${catalogue.bridgeVersion})`);
} else {
  await Deno.writeTextFile(OUT, body);
  console.log(`shell: ${ids.length} action(s) → packages/runtime/shell-actions.js (bridge ${catalogue.bridgeVersion})`);
}
